<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Adminhtml\System\Config\Validatevat $block */
?>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function resetOrder() {
            var validationMessage = $('validation_result');
            var txt;
            var r = confirm("Are you sure to delete the orders table ?");

            if (r == true) {
                txt = "You pressed OK!";
            } else {
                txt = "You pressed Cancel!";
            }

            alert(txt);

            params = {
                //country: $('<?= $block->escapeJs($block->getMerchantCountryField()) ?>').value,
                //vat: $('<?= $block->escapeJs($block->getMerchantVatNumberField()) ?>').value
            };

        }

        window.resetOrder = resetOrder;
//]]>

    });
</script>
<div class="actions actions-validate-vat">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:resetOrder(); return false;" class="action-validate-vat primary" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
