<?php
/** @var Stores $block */

use Ls\Omni\Block\Adminhtml\System\Config\Stores;

?>
<div>
    <?= $block->getButtonHtml(); ?>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Ls_Omni/js/system/config/store-config": {
            "ajaxUrl": "<?= $block->getAjaxUrl(); ?>",
            "hierarchyUrl": "<?= $block->getAjaxHierarchyUrl(); ?>",
            "storeTenderTypesUrl": "<?= $block->getAjaxStoreTenderTypesUrl(); ?>",
            "websiteId": "<?= $block->getWebsiteId(); ?>"
        }
    }
}
</script>
