<?php echo $block->getData('jobName') ?><?php echo __("Cron has been executed. Remaining entries"); ?><?php echo $block->getData('remaining') ?>.
<?php if ($block->getData('url') != "") { ?>
    <?php echo __("Do you want to execute More Data?"); ?> <a
            href="<?php echo $block->escapeUrl($block->getData('url')); ?>"><?php echo $block->escapeHtml(__("Click Here")); ?>
        .</a>
<?php } ?>