<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model\ResourceModel\ReplImageLink;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection
{
    public function _construct()
    {
        $this->_init( 'Ls\Replication\Model\ReplImageLink', 'Ls\Replication\Model\ResourceModel\ReplImageLink' );
    }
}

