<?php

use Magento\Framework\Escaper;
use Ls\Customer\Block\Order\Custom\Hyva\Items;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Items $block */
/** @var Escaper $escaper */

$cols = $block->getData('is_context_shipment') ? 3 : 5;
$order = $block->getOrder(true);
?>
<div class="order-items">
    <div class="hidden lg:grid grid-cols-<?= $escaper->escapeHtmlAttr($cols) ?> text-sm mt-2">
        <div class="p-2 col-span-2"><?= $escaper->escapeHtml(__('Product Name')) ?></div>
        <?php if (!$block->getData('is_context_shipment')): ?>
            <div class="p-2"><?= $escaper->escapeHtml(__('Price')) ?></div><?php endif; ?>
        <div class="p-2"><?= $escaper->escapeHtml(__('Qty')) ?></div>
        <?php if (!$block->getData('is_context_shipment')): ?>
            <div class="p-2 text-right"><?= $escaper->escapeHtml(__('Subtotal')) ?></div><?php endif; ?>
    </div>
    <?php $items = $block->getItems(); ?>
    <?php foreach ($items as $item): ?>
        <?php
        if ($item->getEntryType() == 1 || $item->getParentItem()) :
            continue;
        endif;
        ?>
        <?php if ($item instanceof \Magento\Sales\Model\Order\Item): ?>
            <?= /* @noEscape */ $block->getItemHtml($item) ?>
        <?php else: ?>
            <?= /* @noEscape */ $block->getCustomItemRenderer($item); ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<div class="flex justify-end border-t border-gray-300 mt-2">
    <div class="lg:w-1/3">
        <div class="grid grid-cols-2 text-right p-2 gap-2">
            <?= /* @noEscape */ $block->getChildBlock('custom_order_totals')->setCurrentOrder($order)->toHtml() ?>
        </div>
    </div>
</div>
