trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "PR Created - Triggering Integration Tests"
    displayName: "PR Detection"

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $url = "https://dev.azure.com/dev-lsretail/LS%20Ecommerce/_apis/pipelines/1221/runs?api-version=6.0-preview.1"
        $body = @{
          resources = @{
            repositories = @{
              self = @{
                refName = "$(System.PullRequest.SourceBranch)"
              }
            }
          }
        } | ConvertTo-Json -Depth 10
        $headers = @{
          Authorization = "Bearer $(System.AccessToken)"
        }
        Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body -ContentType "application/json"
    displayName: "Trigger Integration Test Pipeline"
