trigger:
  branches:
    include:
      - sample

steps:
  - script: |
      echo step 1
    displayName: 'Check status 1'
  - script: |
      echo step 2
      echo variables['Build.Reason']
    displayName: 'Check status 2'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
