trigger:
  branches:
    include:
      - sample
steps:
  - script: |
      echo step 1
      echo '$(Build.BuildNumber)'
      echo '$(Build.Reason)'
    displayName: 'Check status 1'
  - script: |
      echo step 2
    displayName: 'Check status 2'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
