trigger:
  branches:
    include:
      - sample
steps:
  - checkout: self
    persistCredentials: true
  - script: |
      git config --global user.email umaryo@lsretail.com & git config --global user.name "umaryo"
    displayName: 'Check status 1'
  - script: |
      cd ~
      mkdir release
      cd release
      git clone https://github.com/lsretailomni/lsmag-two.git .
      git checkout -b sample
      git remote -v
      rm -rf !(*.git)
      rsync -rv --exclude=.git /home/vsts/work/1/s/ .
      git push --set-upstream origin sample
    displayName: 'Check status 2'
