trigger:
  branches:
    include:
      - sample
steps:
  - checkout: self
  - script: |
      mkdir release
      cd release
      git clone https://github.com/$(REPO_NAME).git .
      git checkout -b sample
      git remote -v
      git rm -rf .
      git clean -fxd
      rsync -rv --exclude=.git /home/vsts/work/1/s/ .
      cat ~/.gitconfig
      rm -rf ~/.gitconfig
      git config --global user.email $(EMAIL) & git config --global user.name $(USERNAME)
      git add --all
      git commit -m "Deployment $(Build.BuildNumber)"
      git push https://$(USERNAME):$(PERSONAL_ACCESS_TOKEN)@github.com/$(REPO_NAME).git sample
    displayName: 'Publishing Changes to Github Repository'
    workingDirectory: $(System.DefaultWorkingDirectory)
