trigger:
  branches:
    include:
      - staging
variables:
  BRANCH_NAME: staging
steps:
  - checkout: self
  - script: |
      cd /home/vsts/work/1/s/
      git status
      git remote -v
      git remote add github https://github.com/$(REPO_NAME).git
      git remote -v
      git config pull.rebase false
      git pull github staging --strategy=ours
      sudo git config --global user.email $(EMAIL) & git config --global user.name $(USERNAME)
#      git push https://$(USERNAME):$(PERSONAL_ACCESS_TOKEN)@github.com/$(REPO_NAME).git $(BRANCH_NAME)
    displayName: 'Publishing Changes to Github Repository'
    workingDirectory: $(System.DefaultWorkingDirectory)
