trigger:
  branches:
    include:
      - staging
variables:
  BRANCH_NAME: staging
steps:
  - checkout: self
  - script: |
      CORE_MODULE_REPO_URL=$(CORE_MODULE_REPO_URL)
      AUTH=$(echo -n ":$(AZURE_PERSONAL_ACCESS_TOKEN)" | openssl base64 | tr -d '\n')
      git -c http.$CORE_MODULE_REPO_URL.extraheader="AUTHORIZATION: basic $AUTH" clone $CORE_MODULE_REPO_URL --branch $(BRANCH_NAME) lsmag-two
      cd lsmag-two
      git status
      git remote rm origin
      git remote add origin https://github.com/$(REPO_NAME).git
      git remote -v
      sudo git config --global user.email $(EMAIL) & git config --global user.name $(USERNAME)
      git config pull.rebase false
      git pull origin staging --strategy=ours --allow-unrelated-histories
      git push https://$(USERNAME):$(PERSONAL_ACCESS_TOKEN)@github.com/$(REPO_NAME).git $(BRANCH_NAME)
    displayName: 'Publishing Changes to Github Repository'
    workingDirectory: $(System.DefaultWorkingDirectory)
