<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\Ecommerce\Operation;

use Magento\Framework\App\ObjectManager;

class LSCRetailProductGroup
{
    public string $baseUrl;
    public array $connectionParams;
    public string $companyName;
    public \Ls\Omni\Client\Ecommerce\Entity\ODataRequest_GetProductGroup $request;
    public \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroupResponse $response;
    public \Ls\Omni\Helper\Data $dataHelper;

    public function __construct($baseUrl = '', $connectionParams = [], $companyName = '')
    {
        $this->baseUrl = $baseUrl;
        $this->connectionParams = $connectionParams;
        $this->companyName = $companyName;
        $this->dataHelper = $this->createInstance(\Ls\Omni\Helper\Data::class);
        $this->request = $this->createInstance(\Ls\Omni\Client\Ecommerce\Entity\ODataRequest_GetProductGroup::class);
    }

    public function execute(): \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroupResponse
    {
        $response = $this->dataHelper->makeRequest(
            \Ls\Omni\Client\Ecommerce\Entity\ODataRequest_GetProductGroup::ACTION_NAME,
            \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroup::class,
            $this->request,
            $this->baseUrl,
            $this->connectionParams,
            ['company' => $this->companyName]
        );

        $response = $this->formatResponse($response);

        $this->setResponse($response);

        return $response;
    }

    public function formatResponse($data): \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroupResponse
    {
        if (isset($data['TableData']['TableDataUpd']['RecRefJson'])) {
            $recRef = $data['TableData']['TableDataUpd']['RecRefJson'];
        } elseif (isset($data['DataSet']['DataSetUpd']['DynDataSet'])) {
            $recRef = $data['DataSet']['DataSetUpd']['DynDataSet'];
        } else {
            $recRef = [];
        }

        $deletedRows = [];
        if (isset($data['DataSet']['DataSetDel']['DynDataSet']['DataSetRows'])) {
            $deletedRows = $data['DataSet']['DataSetDel']['DynDataSet']['DataSetRows'];
        }

        if (isset($recRef['RecordFields'])) {
            $fieldsDefinition = $recRef['RecordFields'];
        } elseif (isset($recRef['DataSetFields'])) {
            $fieldsDefinition = $recRef['DataSetFields'];
        } else {
            $fieldsDefinition = [];
        }

        $deletedFieldsDefinition = [];
        if (isset($data['DataSet']['DataSetDel']['DynDataSet']['DataSetFields'])) {
            $deletedFieldsDefinition = $data['DataSet']['DataSetDel']['DynDataSet']['DataSetFields'];
        }

        if (isset($recRef['Records'])) {
            $rows = $recRef['Records'];
        } elseif (isset($recRef['DataSetRows'])) {
            $rows = $recRef['DataSetRows'];
        } else {
            $rows = [];
        }


        foreach ($fieldsDefinition as $field) {
            $fields[$field['FieldIndex']] = $field['FieldName'];
        }

        foreach ($deletedFieldsDefinition as $field) {
            $deletedFields[$field['FieldIndex']] = $field['FieldName'];
        }

        $results = [];
        if (!empty($fields)) {
            foreach ($rows as $row) {
                $values = $row['Fields'] ?? [];
                $entry = $this->createInstance(
                    \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroup::class
                );
                foreach ($values as $value) {
                    $entry->setData($fields[$value['FieldIndex']], $value['FieldValue']);
                }
                $results[] = $entry;
            }
        }

        if (!empty($deletedFields)) {
            foreach ($deletedRows as $row) {
                $values = $row['Fields'] ?? [];
                $entry = $this->createInstance(
                    \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroup::class
                );
                $entry->setData('is_deleted', true);
                foreach ($values as $value) {
                    $entry->setData($deletedFields[$value['FieldIndex']], $value['FieldValue']);
                }
                $results[] = $entry;
            }
        }

        return $this->createInstance(
                    \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroupResponse::class,
                     [
                        'data' => [
                        'records' => $results,
                        'status' => $data['Status'] ?? '',
                        'errorText' => $data['ErrorText'] ?? '',
                        'lastKey' => $data['LastKey'] ?? '',
                        'lastEntryNo' => $data['LastEntryNo'] ?? 0,
                        'endOfTable' => $data['EndOfTable'] ?? false
                        ]
                     ]
                );
    }

    public function createInstance(string $entityClassName, array $data = [])
    {
        return ObjectManager::getInstance()->create($entityClassName, $data);
    }

    public function & setOperationInput(array $params = []): \Ls\Omni\Client\Ecommerce\Entity\ODataRequest_GetProductGroup
    {
        $this->setRequest(
            $this->createInstance(
                \Ls\Omni\Client\Ecommerce\Entity\ODataRequest_GetProductGroup::class,
                ['data' => $params]
            )
        );
        $request = $this->getRequest();

        return $request;
    }


    public function setRequest(\Ls\Omni\Client\Ecommerce\Entity\ODataRequest_GetProductGroup $request): self
    {
        $this->request = $request;
        return $this;
    }

    public function setResponse(\Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroupResponse $response): self
    {
        $this->response = $response;
        return $this;
    }

    public function getRequest(): \Ls\Omni\Client\Ecommerce\Entity\ODataRequest_GetProductGroup
    {
        return $this->request;
    }

    public function getResponse(): \Ls\Omni\Client\Ecommerce\Entity\LSCRetailProductGroupResponse
    {
        return $this->response;
    }
}