<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Operation;

use Ls\Omni\Client\RequestInterface;
use Ls\Omni\Client\ResponseInterface;
use Ls\Omni\Client\AbstractOperation;
use Ls\Omni\Service\Service as OmniService;
use Ls\Omni\Service\ServiceType;
use Ls\Omni\Service\Soap\Client as OmniClient;
use Ls\Omni\Client\Ecommerce\ClassMap;
use Ls\Omni\Client\Ecommerce\Entity\MobilePosRetSave as MobilePosRetSaveRequest;
use Ls\Omni\Client\Ecommerce\Entity\MobilePosRetSaveResult as MobilePosRetSaveResponse;

class MobilePosRetSave extends AbstractOperation
{
    public const OPERATION_NAME = 'MobilePosRetSave';

    public const SERVICE_TYPE = 'ecommerce';

    public function __construct($baseUrl = '')
    {
        $serviceType = new ServiceType( self::SERVICE_TYPE );
        parent::__construct( $serviceType );
        $url = OmniService::getUrl( $serviceType, $baseUrl );
        $this->client = new OmniClient( $url, $serviceType );
        $this->client->setClassmap( $this->getClassMap() );
    }

/** @noinspection PhpDocSignatureInspection */
    /**
     * @param MobilePosRetSaveRequest $request
     * @return ResponseInterface|MobilePosRetSaveResponse
     */
    public function execute(RequestInterface $request = null)
    {
        if ( !is_null( $request ) ) {
            $this->setRequest( $request );
        }
        return $this->makeRequest( self::OPERATION_NAME );
    }

    /**
     * @return MobilePosRetSaveRequest
     */
    public function & getOperationInput()
    {
        if ( is_null( $this->request ) ) {
            $this->request = new MobilePosRetSaveRequest();
        }
        return $this->request;
    }

    /**
     * @return array
     */
    public function getClassMap()
    {
        return ClassMap::getClassMap();
    }

    public function isTokenized()
    {
        return FALSE;
    }

    public function setClient(\OmniClient $client)
    {
        $this->setData('client', $client);
        return $this;
    }

    public function getClient() : \OmniClient
    {
        return $this->client;
    }

    public function setRequest(\MobilePosRetSaveRequest $request)
    {
        $this->setData('request', $request);
        return $this;
    }

    public function getRequest() : \MobilePosRetSaveRequest
    {
        return $this->request;
    }

    public function setResponse(\MobilePosRetSaveResponse $response)
    {
        $this->setData('response', $response);
        return $this;
    }

    public function getResponse() : \MobilePosRetSaveResponse
    {
        return $this->response;
    }

    public function setRequestXml(string $requestXml)
    {
        $this->setData('requestXml', $requestXml);
        return $this;
    }

    public function getRequestXml() : string
    {
        return $this->requestXml;
    }

    public function setResponseXml(string $responseXml)
    {
        $this->setData('responseXml', $responseXml);
        return $this;
    }

    public function getResponseXml() : string
    {
        return $this->responseXml;
    }

    public function setError(\Exception $error)
    {
        $this->setData('error', $error);
        return $this;
    }

    public function getError() : \Exception
    {
        return $this->error;
    }
}

