<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\ResponseInterface;

class ActivityReservationsGetResponse implements ResponseInterface
{

    /**
     * @property ArrayOfBooking $ActivityReservationsGetResult
     */
    protected $ActivityReservationsGetResult = null;

    /**
     * @param ArrayOfBooking $ActivityReservationsGetResult
     * @return $this
     */
    public function setActivityReservationsGetResult($ActivityReservationsGetResult)
    {
        $this->ActivityReservationsGetResult = $ActivityReservationsGetResult;
        return $this;
    }

    /**
     * @return ArrayOfBooking
     */
    public function getActivityReservationsGetResult()
    {
        return $this->ActivityReservationsGetResult;
    }

    /**
     * @return ArrayOfBooking
     */
    public function getResult()
    {
        return $this->ActivityReservationsGetResult;
    }


}

