<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class ActivityUpdateGroupHeaderStatus implements RequestInterface
{
    /**
     * @property string $groupNo
     */
    protected $groupNo = null;

    /**
     * @property string $statusCode
     */
    protected $statusCode = null;

    /**
     * @param string $groupNo
     * @return $this
     */
    public function setGroupNo($groupNo)
    {
        $this->groupNo = $groupNo;
        return $this;
    }

    /**
     * @return string
     */
    public function getGroupNo()
    {
        return $this->groupNo;
    }

    /**
     * @param string $statusCode
     * @return $this
     */
    public function setStatusCode($statusCode)
    {
        $this->statusCode = $statusCode;
        return $this;
    }

    /**
     * @return string
     */
    public function getStatusCode()
    {
        return $this->statusCode;
    }
}

