<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use IteratorAggregate;
use ArrayIterator;

class ArrayOfHierarchyNode implements IteratorAggregate
{

    /**
     * @property HierarchyNode[] $HierarchyNode
     */
    protected $HierarchyNode = array(
        
    );

    /**
     * @param HierarchyNode[] $HierarchyNode
     * @return $this
     */
    public function setHierarchyNode($HierarchyNode)
    {
        $this->HierarchyNode = $HierarchyNode;
        return $this;
    }

    /**
     * @return HierarchyNode[]
     */
    public function getIterator()
    {
        return new ArrayIterator( $this->HierarchyNode );
    }

    /**
     * @return HierarchyNode[]
     */
    public function getHierarchyNode()
    {
        return $this->HierarchyNode;
    }


}

