<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use IteratorAggregate;
use ArrayIterator;

class ArrayOfActivityType implements IteratorAggregate
{
    /**
     * @property ActivityType[] $ActivityType
     */
    protected $ActivityType = [
        
    ];

    /**
     * @param ActivityType[] $ActivityType
     * @return $this
     */
    public function setActivityType($ActivityType)
    {
        $this->ActivityType = $ActivityType;
        return $this;
    }

    /**
     * @return \Traversable
     */
    public function getIterator() : \Traversable
    {
        return new ArrayIterator( $this->ActivityType );
    }

    /**
     * @return ActivityType[]
     */
    public function getActivityType()
    {
        return $this->ActivityType;
    }
}

