<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use IteratorAggregate;
use ArrayIterator;

class ArrayOfReplItemVariantRegistration implements IteratorAggregate
{

    /**
     * @property ReplItemVariantRegistration[] $ReplItemVariantRegistration
     */
    protected $ReplItemVariantRegistration = [
        
    ];

    /**
     * @param ReplItemVariantRegistration[] $ReplItemVariantRegistration
     * @return $this
     */
    public function setReplItemVariantRegistration($ReplItemVariantRegistration)
    {
        $this->ReplItemVariantRegistration = $ReplItemVariantRegistration;
        return $this;
    }

    /**
     * @return \Traversable
     */
    public function getIterator() : \Traversable
    {
        return new ArrayIterator( $this->ReplItemVariantRegistration );
    }

    /**
     * @return ReplItemVariantRegistration[]
     */
    public function getReplItemVariantRegistration()
    {
        return $this->ReplItemVariantRegistration;
    }


}

