<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use IteratorAggregate;
use ArrayIterator;

class ArrayOfSalesEntryLine implements IteratorAggregate
{

    /**
     * @property SalesEntryLine[] $SalesEntryLine
     */
    protected $SalesEntryLine = array(
        
    );

    /**
     * @param SalesEntryLine[] $SalesEntryLine
     * @return $this
     */
    public function setSalesEntryLine($SalesEntryLine)
    {
        $this->SalesEntryLine = $SalesEntryLine;
        return $this;
    }

    /**
     * @return SalesEntryLine[]
     */
    public function getIterator()
    {
        return new ArrayIterator( $this->SalesEntryLine );
    }

    /**
     * @return SalesEntryLine[]
     */
    public function getSalesEntryLine()
    {
        return $this->SalesEntryLine;
    }


}

