<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class COMobilePickHeaders extends \Magento\Framework\DataObject
{
    public const CLASS_NAME = 'COMobilePickHeaders';

    public const ENTRY_NO = 'EntryNo';

    public const TERMINAL_NO = 'TerminalNo';

    public const STORE_NO = 'StoreNo';

    public const PICKING_AREA = 'PickingArea';

    public const CREATED = 'Created';

    public const CUSTOMER_NO = 'CustomerNo';

    public const MEMBER_CARD_NO = 'MemberCardNo';

    public const NAME = 'Name';

    public const ADDRESS = 'Address';

    public const CITY = 'City';

    public const POST_CODE = 'PostCode';

    public const PHONE_NO = 'PhoneNo';

    public const EMAIL = 'Email';

    public const EXTERNAL_I_D = 'ExternalID';

    public const REQUESTED_DELIVERY_DATE = 'RequestedDeliveryDate';

    public const SHIP_ORDER = 'ShipOrder';

    public const PICK_BY_METHOD = 'PickByMethod';

    public const PICK_MULTIPLE_ORDER = 'PickMultipleOrder';

    public const SHOW_LINES_AS = 'ShowLinesAs';

    public const QUANTITY_METHOD = 'QuantityMethod';

    public const DOCUMENT_I_D = 'DocumentID';

    public const ORDER_VALUE = 'OrderValue';

    public const NO_OF_LINES = 'NoOfLines';

    public const NOOF_ITEMS = 'NoofItems';

    public const QUNTITY = 'Quntity';

    public const QUANTITY_BASE = 'QuantityBase';

    public const WEIGHT = 'Weight';

    public const VOLUME = 'Volume';

    /**
     * @param int $EntryNo
     * @return $this
     */
    public function setEntryNo($EntryNo)
    {
        $this->setData(self::ENTRY_NO, $EntryNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getEntryNo()
    {
        return $this->getData(self::ENTRY_NO);
    }

    /**
     * @param string $TerminalNo
     * @return $this
     */
    public function setTerminalNo($TerminalNo)
    {
        $this->setData(self::TERMINAL_NO, $TerminalNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getTerminalNo()
    {
        return $this->getData(self::TERMINAL_NO);
    }

    /**
     * @param string $StoreNo
     * @return $this
     */
    public function setStoreNo($StoreNo)
    {
        $this->setData(self::STORE_NO, $StoreNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreNo()
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param string $PickingArea
     * @return $this
     */
    public function setPickingArea($PickingArea)
    {
        $this->setData(self::PICKING_AREA, $PickingArea);
        return $this;
    }

    /**
     * @return string
     */
    public function getPickingArea()
    {
        return $this->getData(self::PICKING_AREA);
    }

    /**
     * @param string $Created
     * @return $this
     */
    public function setCreated($Created)
    {
        $this->setData(self::CREATED, $Created);
        return $this;
    }

    /**
     * @return string
     */
    public function getCreated()
    {
        return $this->getData(self::CREATED);
    }

    /**
     * @param string $CustomerNo
     * @return $this
     */
    public function setCustomerNo($CustomerNo)
    {
        $this->setData(self::CUSTOMER_NO, $CustomerNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getCustomerNo()
    {
        return $this->getData(self::CUSTOMER_NO);
    }

    /**
     * @param string $MemberCardNo
     * @return $this
     */
    public function setMemberCardNo($MemberCardNo)
    {
        $this->setData(self::MEMBER_CARD_NO, $MemberCardNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getMemberCardNo()
    {
        return $this->getData(self::MEMBER_CARD_NO);
    }

    /**
     * @param string $Name
     * @return $this
     */
    public function setName($Name)
    {
        $this->setData(self::NAME, $Name);
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->getData(self::NAME);
    }

    /**
     * @param string $Address
     * @return $this
     */
    public function setAddress($Address)
    {
        $this->setData(self::ADDRESS, $Address);
        return $this;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->getData(self::ADDRESS);
    }

    /**
     * @param string $City
     * @return $this
     */
    public function setCity($City)
    {
        $this->setData(self::CITY, $City);
        return $this;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->getData(self::CITY);
    }

    /**
     * @param string $PostCode
     * @return $this
     */
    public function setPostCode($PostCode)
    {
        $this->setData(self::POST_CODE, $PostCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getPostCode()
    {
        return $this->getData(self::POST_CODE);
    }

    /**
     * @param string $PhoneNo
     * @return $this
     */
    public function setPhoneNo($PhoneNo)
    {
        $this->setData(self::PHONE_NO, $PhoneNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getPhoneNo()
    {
        return $this->getData(self::PHONE_NO);
    }

    /**
     * @param string $Email
     * @return $this
     */
    public function setEmail($Email)
    {
        $this->setData(self::EMAIL, $Email);
        return $this;
    }

    /**
     * @return string
     */
    public function getEmail()
    {
        return $this->getData(self::EMAIL);
    }

    /**
     * @param string $ExternalID
     * @return $this
     */
    public function setExternalID($ExternalID)
    {
        $this->setData(self::EXTERNAL_I_D, $ExternalID);
        return $this;
    }

    /**
     * @return string
     */
    public function getExternalID()
    {
        return $this->getData(self::EXTERNAL_I_D);
    }

    /**
     * @param date $RequestedDeliveryDate
     * @return $this
     */
    public function setRequestedDeliveryDate($RequestedDeliveryDate)
    {
        $this->setData(self::REQUESTED_DELIVERY_DATE, $RequestedDeliveryDate);
        return $this;
    }

    /**
     * @return date
     */
    public function getRequestedDeliveryDate()
    {
        return $this->getData(self::REQUESTED_DELIVERY_DATE);
    }

    /**
     * @param boolean $ShipOrder
     * @return $this
     */
    public function setShipOrder($ShipOrder)
    {
        $this->setData(self::SHIP_ORDER, $ShipOrder);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getShipOrder()
    {
        return $this->getData(self::SHIP_ORDER);
    }

    /**
     * @param string $PickByMethod
     * @return $this
     */
    public function setPickByMethod($PickByMethod)
    {
        $this->setData(self::PICK_BY_METHOD, $PickByMethod);
        return $this;
    }

    /**
     * @return string
     */
    public function getPickByMethod()
    {
        return $this->getData(self::PICK_BY_METHOD);
    }

    /**
     * @param boolean $PickMultipleOrder
     * @return $this
     */
    public function setPickMultipleOrder($PickMultipleOrder)
    {
        $this->setData(self::PICK_MULTIPLE_ORDER, $PickMultipleOrder);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getPickMultipleOrder()
    {
        return $this->getData(self::PICK_MULTIPLE_ORDER);
    }

    /**
     * @param string $ShowLinesAs
     * @return $this
     */
    public function setShowLinesAs($ShowLinesAs)
    {
        $this->setData(self::SHOW_LINES_AS, $ShowLinesAs);
        return $this;
    }

    /**
     * @return string
     */
    public function getShowLinesAs()
    {
        return $this->getData(self::SHOW_LINES_AS);
    }

    /**
     * @param string $QuantityMethod
     * @return $this
     */
    public function setQuantityMethod($QuantityMethod)
    {
        $this->setData(self::QUANTITY_METHOD, $QuantityMethod);
        return $this;
    }

    /**
     * @return string
     */
    public function getQuantityMethod()
    {
        return $this->getData(self::QUANTITY_METHOD);
    }

    /**
     * @param string $DocumentID
     * @return $this
     */
    public function setDocumentID($DocumentID)
    {
        $this->setData(self::DOCUMENT_I_D, $DocumentID);
        return $this;
    }

    /**
     * @return string
     */
    public function getDocumentID()
    {
        return $this->getData(self::DOCUMENT_I_D);
    }

    /**
     * @param float $OrderValue
     * @return $this
     */
    public function setOrderValue($OrderValue)
    {
        $this->setData(self::ORDER_VALUE, $OrderValue);
        return $this;
    }

    /**
     * @return float
     */
    public function getOrderValue()
    {
        return $this->getData(self::ORDER_VALUE);
    }

    /**
     * @param int $NoOfLines
     * @return $this
     */
    public function setNoOfLines($NoOfLines)
    {
        $this->setData(self::NO_OF_LINES, $NoOfLines);
        return $this;
    }

    /**
     * @return int
     */
    public function getNoOfLines()
    {
        return $this->getData(self::NO_OF_LINES);
    }

    /**
     * @param int $NoofItems
     * @return $this
     */
    public function setNoofItems($NoofItems)
    {
        $this->setData(self::NOOF_ITEMS, $NoofItems);
        return $this;
    }

    /**
     * @return int
     */
    public function getNoofItems()
    {
        return $this->getData(self::NOOF_ITEMS);
    }

    /**
     * @param float $Quntity
     * @return $this
     */
    public function setQuntity($Quntity)
    {
        $this->setData(self::QUNTITY, $Quntity);
        return $this;
    }

    /**
     * @return float
     */
    public function getQuntity()
    {
        return $this->getData(self::QUNTITY);
    }

    /**
     * @param float $QuantityBase
     * @return $this
     */
    public function setQuantityBase($QuantityBase)
    {
        $this->setData(self::QUANTITY_BASE, $QuantityBase);
        return $this;
    }

    /**
     * @return float
     */
    public function getQuantityBase()
    {
        return $this->getData(self::QUANTITY_BASE);
    }

    /**
     * @param float $Weight
     * @return $this
     */
    public function setWeight($Weight)
    {
        $this->setData(self::WEIGHT, $Weight);
        return $this;
    }

    /**
     * @return float
     */
    public function getWeight()
    {
        return $this->getData(self::WEIGHT);
    }

    /**
     * @param float $Volume
     * @return $this
     */
    public function setVolume($Volume)
    {
        $this->setData(self::VOLUME, $Volume);
        return $this;
    }

    /**
     * @return float
     */
    public function getVolume()
    {
        return $this->getData(self::VOLUME);
    }
}

