<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\ResponseInterface;

class ContactCreateResponse implements ResponseInterface
{

    /**
     * @property MemberContact $ContactCreateResult
     */
    protected $ContactCreateResult = null;

    /**
     * @param MemberContact $ContactCreateResult
     * @return $this
     */
    public function setContactCreateResult($ContactCreateResult)
    {
        $this->ContactCreateResult = $ContactCreateResult;
        return $this;
    }

    /**
     * @return MemberContact
     */
    public function getContactCreateResult()
    {
        return $this->ContactCreateResult;
    }

    /**
     * @return MemberContact
     */
    public function getResult()
    {
        return $this->ContactCreateResult;
    }


}

