<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\Ecommerce\Entity;

use Magento\Catalog\Model\AbstractModel;

class CountryView extends AbstractModel
{
    public const CODE = 'Code';
    public const NAME = 'Name';
    public const ISO_CODE = 'ISO Code';
    public const ISO_NUMERIC_CODE = 'ISO Numeric Code';
    public const EU_COUNTRYREGION_CODE = 'EU Country/Region Code';
    public const INTRASTAT_CODE = 'Intrastat Code';
    public const ADDRESS_FORMAT = 'Address Format';
    public const CONTACT_ADDRESS_FORMAT = 'Contact Address Format';
    public const VAT_SCHEME = 'VAT Scheme';
    public const LAST_MODIFIED_DATE_TIME = 'Last Modified Date Time';
    public const COUNTY_NAME = 'County Name';
    public const LSC_WEB_STORE_CUSTOMER_NO = 'LSC Web Store Customer No.';
    public const SYSTEMID = '$systemId';
    public const SYSTEMCREATEDAT = 'SystemCreatedAt';
    public const SYSTEMCREATEDBY = 'SystemCreatedBy';
    public const SYSTEMMODIFIEDAT = 'SystemModifiedAt';
    public const SYSTEMMODIFIEDBY = 'SystemModifiedBy';
    public const TAXPOSTGROUP = 'TaxPostGroup';


    public function getCode(): ?string
    {
        return $this->getData(self::CODE);
    }

    public function setCode(string $value)
    {
        return $this->setData(self::CODE, $value);
    }

    public function getName(): ?string
    {
        return $this->getData(self::NAME);
    }

    public function setName(string $value)
    {
        return $this->setData(self::NAME, $value);
    }

    public function getISOCode(): ?string
    {
        return $this->getData(self::ISO_CODE);
    }

    public function setISOCode(string $value)
    {
        return $this->setData(self::ISO_CODE, $value);
    }

    public function getISONumericCode(): ?string
    {
        return $this->getData(self::ISO_NUMERIC_CODE);
    }

    public function setISONumericCode(string $value)
    {
        return $this->setData(self::ISO_NUMERIC_CODE, $value);
    }

    public function getEUCountryRegionCode(): ?string
    {
        return $this->getData(self::EU_COUNTRYREGION_CODE);
    }

    public function setEUCountryRegionCode(string $value)
    {
        return $this->setData(self::EU_COUNTRYREGION_CODE, $value);
    }

    public function getIntrastatCode(): ?string
    {
        return $this->getData(self::INTRASTAT_CODE);
    }

    public function setIntrastatCode(string $value)
    {
        return $this->setData(self::INTRASTAT_CODE, $value);
    }

    public function getAddressFormat(): ?string
    {
        return $this->getData(self::ADDRESS_FORMAT);
    }

    public function setAddressFormat(string $value)
    {
        return $this->setData(self::ADDRESS_FORMAT, $value);
    }

    public function getContactAddressFormat(): ?string
    {
        return $this->getData(self::CONTACT_ADDRESS_FORMAT);
    }

    public function setContactAddressFormat(string $value)
    {
        return $this->setData(self::CONTACT_ADDRESS_FORMAT, $value);
    }

    public function getVATScheme(): ?string
    {
        return $this->getData(self::VAT_SCHEME);
    }

    public function setVATScheme(string $value)
    {
        return $this->setData(self::VAT_SCHEME, $value);
    }

    public function getLastModifiedDateTime(): ?\DateTime
    {
        return $this->getData(self::LAST_MODIFIED_DATE_TIME);
    }

    public function setLastModifiedDateTime(\DateTime $value)
    {
        return $this->setData(self::LAST_MODIFIED_DATE_TIME, $value);
    }

    public function getCountyName(): ?string
    {
        return $this->getData(self::COUNTY_NAME);
    }

    public function setCountyName(string $value)
    {
        return $this->setData(self::COUNTY_NAME, $value);
    }

    public function getLSCWebStoreCustomerNo(): ?string
    {
        return $this->getData(self::LSC_WEB_STORE_CUSTOMER_NO);
    }

    public function setLSCWebStoreCustomerNo(string $value)
    {
        return $this->setData(self::LSC_WEB_STORE_CUSTOMER_NO, $value);
    }

    public function getSystemId(): ?string
    {
        return $this->getData(self::SYSTEMID);
    }

    public function setSystemId(string $value)
    {
        return $this->setData(self::SYSTEMID, $value);
    }

    public function getSystemCreatedAt(): ?\DateTime
    {
        return $this->getData(self::SYSTEMCREATEDAT);
    }

    public function setSystemCreatedAt(\DateTime $value)
    {
        return $this->setData(self::SYSTEMCREATEDAT, $value);
    }

    public function getSystemCreatedBy(): ?string
    {
        return $this->getData(self::SYSTEMCREATEDBY);
    }

    public function setSystemCreatedBy(string $value)
    {
        return $this->setData(self::SYSTEMCREATEDBY, $value);
    }

    public function getSystemModifiedAt(): ?\DateTime
    {
        return $this->getData(self::SYSTEMMODIFIEDAT);
    }

    public function setSystemModifiedAt(\DateTime $value)
    {
        return $this->setData(self::SYSTEMMODIFIEDAT, $value);
    }

    public function getSystemModifiedBy(): ?string
    {
        return $this->getData(self::SYSTEMMODIFIEDBY);
    }

    public function setSystemModifiedBy(string $value)
    {
        return $this->setData(self::SYSTEMMODIFIEDBY, $value);
    }

    public function getTaxPostGroup(): ?string
    {
        return $this->getData(self::TAXPOSTGROUP);
    }

    public function setTaxPostGroup(string $value)
    {
        return $this->setData(self::TAXPOSTGROUP, $value);
    }
}