<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\ResponseInterface;

class CreateHospOrderResult extends \Magento\Catalog\Model\AbstractModel implements ResponseInterface
{
    public const CLASS_NAME = 'CreateHospOrder_Result';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    public const HOSP_ORDER_RECEIPT_NO = 'hospOrderReceiptNo';

    public const CREATE_HOSP_ORDER_X_M_L = 'createHospOrderXML';

    /**
     * @param ?string $responseCode
     * @return $this
     */
    public function setResponseCode(?string $responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResponseCode() : ?string
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param ?string $errorText
     * @return $this
     */
    public function setErrorText(?string $errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getErrorText() : ?string
    {
        return $this->getData(self::ERROR_TEXT);
    }

    /**
     * @param ?string $hospOrderReceiptNo
     * @return $this
     */
    public function setHospOrderReceiptNo(?string $hospOrderReceiptNo)
    {
        $this->setData(self::HOSP_ORDER_RECEIPT_NO, $hospOrderReceiptNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getHospOrderReceiptNo() : ?string
    {
        return $this->getData(self::HOSP_ORDER_RECEIPT_NO);
    }

    /**
     * @param RootHospTransaction $createHospOrderXML
     * @return $this
     */
    public function setCreateHospOrderXML($createHospOrderXML)
    {
        $this->setData(self::CREATE_HOSP_ORDER_X_M_L, $createHospOrderXML);
        return $this;
    }

    /**
     * @return RootHospTransaction
     */
    public function getCreateHospOrderXML()
    {
        return $this->getData(self::CREATE_HOSP_ORDER_X_M_L);
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->responseCode;
    }
}

