<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class GetASNDocumentList extends \Magento\Framework\DataObject implements RequestInterface
{
    public const CLASS_NAME = 'GetASNDocumentList';

    public const VENDOR_NOP = 'vendorNo_p';

    public const LOCATION_CODEP = 'locationCode_p';

    public const GET_A_S_N_DOCUMENT_LIST_X_M_L = 'getASNDocumentListXML';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    /**
     * @param string $vendorNop
     * @return $this
     */
    public function setVendorNoP($vendorNop)
    {
        $this->setData(self::VENDOR_NOP, $vendorNop);
        return $this;
    }

    /**
     * @return string
     */
    public function getVendorNoP()
    {
        return $this->getData(self::VENDOR_NOP);
    }

    /**
     * @param string $locationCodep
     * @return $this
     */
    public function setLocationCodeP($locationCodep)
    {
        $this->setData(self::LOCATION_CODEP, $locationCodep);
        return $this;
    }

    /**
     * @return string
     */
    public function getLocationCodeP()
    {
        return $this->getData(self::LOCATION_CODEP);
    }

    /**
     * @param RootGetDocumentList $getASNDocumentListXML
     * @return $this
     */
    public function setGetASNDocumentListXML($getASNDocumentListXML)
    {
        $this->setData(self::GET_A_S_N_DOCUMENT_LIST_X_M_L, $getASNDocumentListXML);
        return $this;
    }

    /**
     * @return RootGetDocumentList
     */
    public function getGetASNDocumentListXML()
    {
        return $this->getData(self::GET_A_S_N_DOCUMENT_LIST_X_M_L);
    }

    /**
     * @param string $responseCode
     * @return $this
     */
    public function setResponseCode($responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getResponseCode()
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param string $errorText
     * @return $this
     */
    public function setErrorText($errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return string
     */
    public function getErrorText()
    {
        return $this->getData(self::ERROR_TEXT);
    }
}

