<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\ResponseInterface;

class GetDocumentListV2Result extends \Magento\Catalog\Model\AbstractModel implements ResponseInterface
{
    public const CLASS_NAME = 'GetDocumentListV2_Result';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    public const GET_DOCUMENT_LIST_XML = 'getDocumentListXML';

    /**
     * @param ?string $responseCode
     * @return $this
     */
    public function setResponsecode(?string $responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResponsecode() : ?string
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param ?string $errorText
     * @return $this
     */
    public function setErrortext(?string $errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getErrortext() : ?string
    {
        return $this->getData(self::ERROR_TEXT);
    }

    /**
     * @param RootGetDocumentList $getDocumentListXML
     * @return $this
     */
    public function setGetdocumentlistxml($getDocumentListXML)
    {
        $this->setData(self::GET_DOCUMENT_LIST_XML, $getDocumentListXML);
        return $this;
    }

    /**
     * @return RootGetDocumentList
     */
    public function getGetdocumentlistxml()
    {
        return $this->getData(self::GET_DOCUMENT_LIST_XML);
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->responseCode;
    }
}

