<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class GetDirectMarketingInfo extends \Magento\Catalog\Model\AbstractModel implements RequestInterface
{
    public const CLASS_NAME = 'GetDirectMarketingInfo';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    public const CARD_ID = 'cardId';

    public const ITEM_NO = 'itemNo';

    public const STORE_NO = 'storeNo';

    public const LOAD_MEMBER_DIR_MARK_INFO_XML = 'loadMemberDirMarkInfoXML';

    /**
     * @param ?string $responseCode
     * @return $this
     */
    public function setResponsecode(?string $responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResponsecode() : ?string
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param ?string $errorText
     * @return $this
     */
    public function setErrortext(?string $errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getErrortext() : ?string
    {
        return $this->getData(self::ERROR_TEXT);
    }

    /**
     * @param ?string $cardId
     * @return $this
     */
    public function setCardid(?string $cardId)
    {
        $this->setData(self::CARD_ID, $cardId);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getCardid() : ?string
    {
        return $this->getData(self::CARD_ID);
    }

    /**
     * @param ?string $itemNo
     * @return $this
     */
    public function setItemno(?string $itemNo)
    {
        $this->setData(self::ITEM_NO, $itemNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getItemno() : ?string
    {
        return $this->getData(self::ITEM_NO);
    }

    /**
     * @param ?string $storeNo
     * @return $this
     */
    public function setStoreno(?string $storeNo)
    {
        $this->setData(self::STORE_NO, $storeNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStoreno() : ?string
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param RootGetDirectMarketingInfo $loadMemberDirMarkInfoXML
     * @return $this
     */
    public function setLoadmemberdirmarkinfoxml($loadMemberDirMarkInfoXML)
    {
        $this->setData(self::LOAD_MEMBER_DIR_MARK_INFO_XML, $loadMemberDirMarkInfoXML);
        return $this;
    }

    /**
     * @return RootGetDirectMarketingInfo
     */
    public function getLoadmemberdirmarkinfoxml()
    {
        return $this->getData(self::LOAD_MEMBER_DIR_MARK_INFO_XML);
    }
}

