<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class GetItemCard extends \Magento\Framework\DataObject implements RequestInterface
{
    public const CLASS_NAME = 'GetItemCard';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    public const TERMINAL_NO = 'terminalNo';

    public const STORE_NO = 'storeNo';

    public const LOCATION_NO = 'locationNo';

    public const ITEM_NO = 'itemNo';

    public const VARIANT_CODE = 'variantCode';

    public const BARCODE_NO = 'barcodeNo';

    public const VIEW_CODE = 'viewCode';

    public const LEFT_RIGHT_LINE_X_M_L = 'leftRightLineXML';

    /**
     * @param string $responseCode
     * @return $this
     */
    public function setResponseCode($responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getResponseCode()
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param string $errorText
     * @return $this
     */
    public function setErrorText($errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return string
     */
    public function getErrorText()
    {
        return $this->getData(self::ERROR_TEXT);
    }

    /**
     * @param string $terminalNo
     * @return $this
     */
    public function setTerminalNo($terminalNo)
    {
        $this->setData(self::TERMINAL_NO, $terminalNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getTerminalNo()
    {
        return $this->getData(self::TERMINAL_NO);
    }

    /**
     * @param string $storeNo
     * @return $this
     */
    public function setStoreNo($storeNo)
    {
        $this->setData(self::STORE_NO, $storeNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreNo()
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param string $locationNo
     * @return $this
     */
    public function setLocationNo($locationNo)
    {
        $this->setData(self::LOCATION_NO, $locationNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getLocationNo()
    {
        return $this->getData(self::LOCATION_NO);
    }

    /**
     * @param string $itemNo
     * @return $this
     */
    public function setItemNo($itemNo)
    {
        $this->setData(self::ITEM_NO, $itemNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getItemNo()
    {
        return $this->getData(self::ITEM_NO);
    }

    /**
     * @param string $variantCode
     * @return $this
     */
    public function setVariantCode($variantCode)
    {
        $this->setData(self::VARIANT_CODE, $variantCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getVariantCode()
    {
        return $this->getData(self::VARIANT_CODE);
    }

    /**
     * @param string $barcodeNo
     * @return $this
     */
    public function setBarcodeNo($barcodeNo)
    {
        $this->setData(self::BARCODE_NO, $barcodeNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getBarcodeNo()
    {
        return $this->getData(self::BARCODE_NO);
    }

    /**
     * @param string $viewCode
     * @return $this
     */
    public function setViewCode($viewCode)
    {
        $this->setData(self::VIEW_CODE, $viewCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getViewCode()
    {
        return $this->getData(self::VIEW_CODE);
    }

    /**
     * @param RootLeftRightLine $leftRightLineXML
     * @return $this
     */
    public function setLeftRightLineXML($leftRightLineXML)
    {
        $this->setData(self::LEFT_RIGHT_LINE_X_M_L, $leftRightLineXML);
        return $this;
    }

    /**
     * @return RootLeftRightLine
     */
    public function getLeftRightLineXML()
    {
        return $this->getData(self::LEFT_RIGHT_LINE_X_M_L);
    }
}

