<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class GetStoreOpeningHours extends \Magento\Catalog\Model\AbstractModel implements RequestInterface
{
    public const CLASS_NAME = 'GetStoreOpeningHours';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    public const STORE_NO = 'storeNo';

    public const GET_STORE_OPENING_HOURS_XML = 'getStoreOpeningHoursXML';

    /**
     * @param ?string $responseCode
     * @return $this
     */
    public function setResponsecode(?string $responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResponsecode() : ?string
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param ?string $errorText
     * @return $this
     */
    public function setErrortext(?string $errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getErrortext() : ?string
    {
        return $this->getData(self::ERROR_TEXT);
    }

    /**
     * @param ?string $storeNo
     * @return $this
     */
    public function setStoreno(?string $storeNo)
    {
        $this->setData(self::STORE_NO, $storeNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStoreno() : ?string
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param RootGetStoreOpeningHours $getStoreOpeningHoursXML
     * @return $this
     */
    public function setGetstoreopeninghoursxml($getStoreOpeningHoursXML)
    {
        $this->setData(self::GET_STORE_OPENING_HOURS_XML, $getStoreOpeningHoursXML);
        return $this;
    }

    /**
     * @return RootGetStoreOpeningHours
     */
    public function getGetstoreopeninghoursxml()
    {
        return $this->getData(self::GET_STORE_OPENING_HOURS_XML);
    }
}

