<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class HierarchyNodeImageV2 extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'HierarchyNodeImageV2';

    public const KEY_VALUE = 'KeyValue';

    public const DISPLAY_ORDER = 'DisplayOrder';

    public const IMAGE_ID = 'ImageId';

    /**
     * @param ?string $KeyValue
     * @return $this
     */
    public function setKeyValue(?string $KeyValue)
    {
        $this->setData(self::KEY_VALUE, $KeyValue);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getKeyValue() : ?string
    {
        return $this->getData(self::KEY_VALUE);
    }

    /**
     * @param int $DisplayOrder
     * @return $this
     */
    public function setDisplayOrder($DisplayOrder)
    {
        $this->setData(self::DISPLAY_ORDER, $DisplayOrder);
        return $this;
    }

    /**
     * @return int
     */
    public function getDisplayOrder()
    {
        return $this->getData(self::DISPLAY_ORDER);
    }

    /**
     * @param ?string $ImageId
     * @return $this
     */
    public function setImageId(?string $ImageId)
    {
        $this->setData(self::IMAGE_ID, $ImageId);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getImageId() : ?string
    {
        return $this->getData(self::IMAGE_ID);
    }
}

