<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class KotStatus extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'KotStatus';

    public const RECEIPT_NO = 'ReceiptNo';

    public const KOT_NO = 'KotNo';

    public const STATUS = 'Status';

    public const CONFIRMEDBY_EXP = 'ConfirmedbyExp';

    public const KOT_PROD_TIME = 'KotProdTime';

    public const ORDER_I_D = 'OrderID';

    /**
     * @param string $ReceiptNo
     * @return $this
     */
    public function setReceiptNo($ReceiptNo)
    {
        $this->setData(self::RECEIPT_NO, $ReceiptNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getReceiptNo()
    {
        return $this->getData(self::RECEIPT_NO);
    }

    /**
     * @param string $KotNo
     * @return $this
     */
    public function setKotNo($KotNo)
    {
        $this->setData(self::KOT_NO, $KotNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getKotNo()
    {
        return $this->getData(self::KOT_NO);
    }

    /**
     * @param string $Status
     * @return $this
     */
    public function setStatus($Status)
    {
        $this->setData(self::STATUS, $Status);
        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->getData(self::STATUS);
    }

    /**
     * @param boolean $ConfirmedbyExp
     * @return $this
     */
    public function setConfirmedbyExp($ConfirmedbyExp)
    {
        $this->setData(self::CONFIRMEDBY_EXP, $ConfirmedbyExp);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getConfirmedbyExp()
    {
        return $this->getData(self::CONFIRMEDBY_EXP);
    }

    /**
     * @param float $KotProdTime
     * @return $this
     */
    public function setKotProdTime($KotProdTime)
    {
        $this->setData(self::KOT_PROD_TIME, $KotProdTime);
        return $this;
    }

    /**
     * @return float
     */
    public function getKotProdTime()
    {
        return $this->getData(self::KOT_PROD_TIME);
    }

    /**
     * @param string $OrderID
     * @return $this
     */
    public function setOrderID($OrderID)
    {
        $this->setData(self::ORDER_I_D, $OrderID);
        return $this;
    }

    /**
     * @return string
     */
    public function getOrderID()
    {
        return $this->getData(self::ORDER_I_D);
    }
}

