<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\Ecommerce\Entity;

use Magento\Catalog\Model\AbstractModel;

class LSCMobilePlu extends AbstractModel
{
    public const STOREID = 'StoreId';
    public const PAGEID = 'PageId';
    public const PAGEINDEX = 'PageIndex';
    public const ITEMID = 'ItemId';
    public const DESCRIPTION = 'Description';
    public const RETAILIMAGEID = 'RetailImageId';
    public const IMAGEBLOB = 'ImageBlob';
    public const SYSTEMID = '$systemId';
    public const SYSTEMCREATEDAT = 'SystemCreatedAt';
    public const SYSTEMCREATEDBY = 'SystemCreatedBy';
    public const SYSTEMMODIFIEDAT = 'SystemModifiedAt';
    public const SYSTEMMODIFIEDBY = 'SystemModifiedBy';

    public array $dbColumnsMapping = [
	self::STOREID => 'storeid',
	self::PAGEID => 'pageid',
	self::PAGEINDEX => 'pageindex',
	self::ITEMID => 'itemid',
	self::DESCRIPTION => 'description',
	self::RETAILIMAGEID => 'retailimageid',
	self::IMAGEBLOB => 'imageblob',
	self::SYSTEMID => 'systemid',
	self::SYSTEMCREATEDAT => 'systemcreatedat',
	self::SYSTEMCREATEDBY => 'systemcreatedby',
	self::SYSTEMMODIFIEDAT => 'systemmodifiedat',
	self::SYSTEMMODIFIEDBY => 'systemmodifiedby',
    ];

    public function getDbColumnsMapping(): array
    {
        return $this->dbColumnsMapping;
    }


    public function getStoreid(): ?string
    {
        return $this->getData(self::STOREID);
    }

    public function setStoreid(?string $value)
    {
        return $this->setData(self::STOREID, $value);
    }

    public function getPageid(): ?int
    {
        return $this->getData(self::PAGEID);
    }

    public function setPageid(?int $value)
    {
        return $this->setData(self::PAGEID, $value);
    }

    public function getPageindex(): ?int
    {
        return $this->getData(self::PAGEINDEX);
    }

    public function setPageindex(?int $value)
    {
        return $this->setData(self::PAGEINDEX, $value);
    }

    public function getItemid(): ?string
    {
        return $this->getData(self::ITEMID);
    }

    public function setItemid(?string $value)
    {
        return $this->setData(self::ITEMID, $value);
    }

    public function getDescription(): ?string
    {
        return $this->getData(self::DESCRIPTION);
    }

    public function setDescription(?string $value)
    {
        return $this->setData(self::DESCRIPTION, $value);
    }

    public function getRetailimageid(): ?string
    {
        return $this->getData(self::RETAILIMAGEID);
    }

    public function setRetailimageid(?string $value)
    {
        return $this->setData(self::RETAILIMAGEID, $value);
    }

    public function getImageblob(): ?string
    {
        return $this->getData(self::IMAGEBLOB);
    }

    public function setImageblob(?string $value)
    {
        return $this->setData(self::IMAGEBLOB, $value);
    }

    public function getSystemid(): ?string
    {
        return $this->getData(self::SYSTEMID);
    }

    public function setSystemid(?string $value)
    {
        return $this->setData(self::SYSTEMID, $value);
    }

    public function getSystemcreatedat(): ?\DateTime
    {
        return $this->getData(self::SYSTEMCREATEDAT);
    }

    public function setSystemcreatedat(?\DateTime $value)
    {
        return $this->setData(self::SYSTEMCREATEDAT, $value);
    }

    public function getSystemcreatedby(): ?string
    {
        return $this->getData(self::SYSTEMCREATEDBY);
    }

    public function setSystemcreatedby(?string $value)
    {
        return $this->setData(self::SYSTEMCREATEDBY, $value);
    }

    public function getSystemmodifiedat(): ?\DateTime
    {
        return $this->getData(self::SYSTEMMODIFIEDAT);
    }

    public function setSystemmodifiedat(?\DateTime $value)
    {
        return $this->setData(self::SYSTEMMODIFIEDAT, $value);
    }

    public function getSystemmodifiedby(): ?string
    {
        return $this->getData(self::SYSTEMMODIFIEDBY);
    }

    public function setSystemmodifiedby(?string $value)
    {
        return $this->setData(self::SYSTEMMODIFIEDBY, $value);
    }
}