<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\Ecommerce\Entity;

use Magento\Framework\DataObject;

class LSCMemberAccount extends DataObject
{
    public const NO = 'No.';
    public const BLOCKED = 'Blocked';
    public const REASON_BLOCKED = 'Reason Blocked';
    public const DATE_BLOCKED = 'Date Blocked';
    public const BLOCKED_BY = 'Blocked By';
    public const LINKED_TO_CUSTOMER_NO = 'Linked To Customer No.';
    public const CLUB_CODE = 'Club Code';
    public const SCHEME_CODE = 'Scheme Code';
    public const STATUS = 'Status';
    public const ACCOUNT_TYPE = 'Account Type';


    public function getNo(): ?string
    {
        return $this->getData(self::NO);
    }

    public function setNo(string $value): self
    {
        return $this->setData(self::NO, $value);
    }

    public function getBlocked(): ?bool
    {
        return $this->getData(self::BLOCKED);
    }

    public function setBlocked(bool $value): self
    {
        return $this->setData(self::BLOCKED, $value);
    }

    public function getReasonBlocked(): ?string
    {
        return $this->getData(self::REASON_BLOCKED);
    }

    public function setReasonBlocked(string $value): self
    {
        return $this->setData(self::REASON_BLOCKED, $value);
    }

    public function getDateBlocked(): ?string
    {
        return $this->getData(self::DATE_BLOCKED);
    }

    public function setDateBlocked(string $value): self
    {
        return $this->setData(self::DATE_BLOCKED, $value);
    }

    public function getBlockedBy(): ?string
    {
        return $this->getData(self::BLOCKED_BY);
    }

    public function setBlockedBy(string $value): self
    {
        return $this->setData(self::BLOCKED_BY, $value);
    }

    public function getLinkedToCustomerNo(): ?string
    {
        return $this->getData(self::LINKED_TO_CUSTOMER_NO);
    }

    public function setLinkedToCustomerNo(string $value): self
    {
        return $this->setData(self::LINKED_TO_CUSTOMER_NO, $value);
    }

    public function getClubCode(): ?string
    {
        return $this->getData(self::CLUB_CODE);
    }

    public function setClubCode(string $value): self
    {
        return $this->setData(self::CLUB_CODE, $value);
    }

    public function getSchemeCode(): ?string
    {
        return $this->getData(self::SCHEME_CODE);
    }

    public function setSchemeCode(string $value): self
    {
        return $this->setData(self::SCHEME_CODE, $value);
    }

    public function getStatus(): ?string
    {
        return $this->getData(self::STATUS);
    }

    public function setStatus(string $value): self
    {
        return $this->setData(self::STATUS, $value);
    }

    public function getAccountType(): ?string
    {
        return $this->getData(self::ACCOUNT_TYPE);
    }

    public function setAccountType(string $value): self
    {
        return $this->setData(self::ACCOUNT_TYPE, $value);
    }
}