<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\Ecommerce\Entity;

use Magento\Framework\DataObject;

class LSCPOSTerminal extends DataObject
{
    public const STORE_NO = 'Store No.';
    public const NO = 'No.';
    public const TERMINAL_TYPE = 'Terminal Type';
    public const DESCRIPTION = 'Description';
    public const PLACEMENT = 'Placement';
    public const STATEMENT_METHOD = 'Statement Method';
    public const TERMINAL_STATEMENT = 'Terminal Statement';
    public const DEFAULT_PRICE_GROUP = 'Default Price Group';
    public const NOT_ACTIVE = 'Not Active';
    public const TERMINAL_NETWORK_I_D = 'Terminal Network ID';
    public const TERMINAL_I_P_ADDRESS = 'Terminal IP Address';
    public const TERMINAL_CONNECTION = 'Terminal Connection';
    public const SHOW_ITEM_IMAGE = 'Show Item Image';
    public const SHOW_ITEM_HTML = 'Show Item Html';
    public const SHOW_OFFER_HTML = 'Show Offer Html';
    public const DISPLAY_TERMINAL_CLOSED = 'Display Terminal Closed';
    public const DISPLAY_LINKED_ITEM = 'Display Linked Item';
    public const FRAUD_SORT_FIELD = 'Fraud Sort Field';
    public const MANAGER_KEY_ON_RETURN = 'Manager Key on Return';
    public const KEY_LOCK_STAFF_PERM_GROUP = 'KeyLock Staff Perm. Group';
    public const SLIP_IF_RETURN = 'Slip if Return';
    public const OPEN_DRAWER_AT_L_I_L_O = 'Open Drawer at LI/LO';
    public const ONLY_TOTAL_IN_SUSP_TRANS = 'Only Total in Susp. Trans.';
    public const EXIT_AFTER_EACH_TRANS = 'Exit After Each Trans.';
    public const AUTO_LOGOFF_AFTER_MIN = 'AutoLogoff After (Min.)';
    public const ALLOW_AUTO_LOGOFF_IN_SALES_MODE = 'Allow AutoLogoff in Sales Mode';
    public const RETURN_IN_TRANSACTION = 'Return in Transaction';
    public const ITEM_NO_ON_RECEIPT = 'Item No. on Receipt';
    public const PRINT_RECEIPT_FOR_NEG_ADJ = 'Print Receipt for Neg. Adj.';
    public const E_F_T_EMBEDDED_RECEIPT = 'EFT Embedded Receipt';
    public const USE_REFERENCED_REFUNDS = 'Use Referenced Refunds';
    public const LAST_DATE_MODIFIED = 'Last Date Modified';
    public const PRINT_RECEIPT_LOGO = 'Print Receipt Logo';
    public const PRINT_RECEIPT_BITMAP_NO = 'Print Receipt Bitmap No.';
    public const RCPT_TEXT_MAX_LENGTH = 'Rcpt. Text Max. Length';
    public const NO_OF_TOP_BOTTOM_LINES = 'No. of Top/Bottom Lines';
    public const RECEIPT_BARCODE = 'Receipt Barcode';
    public const RECEIPT_SETUP_LOCATION = 'Receipt Setup Location';
    public const DISPLAY_TEXT_MAX_LENGTH = 'Display Text Max. Length';
    public const CUSTOMER_DISPLAY_TEXT_1 = 'Customer Display Text 1';
    public const CUSTOMER_DISPLAY_TEXT_2 = 'Customer Display Text 2';
    public const PRINT_RECEIPT_B_C_TYPE = 'Print Receipt BC Type';
    public const RECEIPT_BARCODE_WIDTH = 'Receipt Barcode Width';
    public const RECEIPT_BARCODE_HEIGHT = 'Receipt Barcode Height';
    public const ONLINE_TRANS_BACKUP = 'Online Trans. Backup';
    public const SUM_OF_TRANS_NO = 'Sum of Trans. No.';
    public const COUNT_OF_TRANS = 'Count of Trans.';
    public const NO_SERIES = 'No. Series';
    public const TABLE_GROUP = 'Table Group';
    public const TABLE_VIEW_AT_LOGON = 'Table View at Logon';
    public const OPERATIONAL_MODE = 'Operational Mode';
    public const REC_PRINTING_OFF_BY_DEFAULT = 'Rec. Printing Off by Default';
    public const DEFAULT_SALES_TYPE = 'Default Sales Type';
    public const F_B_TAKEAWAY_SALES_TYPE = 'F&B Takeaway Sales Type';
    public const DELIVERY_SALES_TYPE = 'Delivery Sales Type';
    public const SAFE_NO = 'Safe No.';
    public const STAFF_LOGIN_VALIDATION = 'Staff Login Validation';
    public const EXCLUDE_FROM_CASH_MGNT = 'Exclude from Cash Mgnt.';
    public const LAST_Z_REPORT = 'Last Z-Report';
    public const LAST_Y_REPORT = 'Last Y-Report';
    public const HARDWARE_PROFILE = 'Hardware Profile';
    public const MENU_PROFILE = 'Menu Profile';
    public const INTERFACE_PROFILE = 'Interface Profile';
    public const FUNCTIONALITY_PROFILE = 'Functionality Profile';
    public const STYLE_PROFILE = 'Style Profile';
    public const S_S_K_PROFILE_I_D = 'SSK Profile ID';
    public const S_S_K_TERMINAL_ENABLED = 'SSK Terminal Enabled';
    public const PRINT_V_A_T_REFUND_CHECKS = 'Print VAT Refund Checks';
    public const PRINT_SUSPEND_WITH_PREPAYMENT = 'Print Suspend with Prepayment';
    public const PRINT_NUMBER_OF_ITEMS = 'Print Number of Items';
    public const PRINT_TOTAL_SAVINGS = 'Print Total Savings';
    public const PRINT_DISCOUNT_DETAIL = 'Print Discount Detail';
    public const SECOND_HARDWARE_PROFILE = 'Second Hardware Profile';
    public const PRINT_SECOND_RECEIPT = 'Print Second Receipt';
    public const SALES_TYPE_FILTER = 'Sales Type Filter';
    public const COPY_OF_MENU_PROFILE = 'Copy of Menu Profile';
    public const COPY_OF_INTERFACE_PROFILE = 'Copy of Interface Profile';
    public const IDLE_TIMER_INTERVAL = 'Idle Timer Interval';
    public const EXTERNAL_PRINTER_I_D = 'External Printer ID';
    public const HOSP_TYPE_POPUP_ON_LOGON = 'Hosp. Type Pop-up on Logon';
    public const RECEIPT_BARCODE_I_D = 'Receipt Barcode ID';
    public const PRINTER_K_O_T_STATUS_AFTER_SENT = 'Printer KOT Status after Sent';
    public const SALES_SLIP = 'Sales Slip';
    public const VOID_SLIP = 'Void Slip';
    public const ONLY_EMAIL_SALES_TRANSACTIONS = 'Only Email Sales Transactions';
    public const B_C_C_E_MAIL_ADDRESS = 'BCC E-Mail Address';
    public const INVENTORY_MAIN_MENU = 'Inventory Main Menu';
    public const INVENTORY_NO_OF_RECORDS = 'Inventory No. of Records';
    public const ALLOW_POST_I_M_DOCUMENTS = 'Allow Post IM Documents';
    public const A_S_N_QUANTITY_METHOD = 'ASN Quantity Method';
    public const DUAL_DISP_ENABLED = 'Dual Disp. Enabled';
    public const DUAL_DISP_STYLE_PROFILE = 'Dual Disp. Style Profile';
    public const DUAL_DISP_INTERFACE_PROFILE = 'Dual Disp. Interface Profile';
    public const DUAL_DISP_MENU_PROFILE = 'Dual Disp. Menu Profile';
    public const DUAL_DISP_SLIDESHOW = 'Dual Disp. Slideshow';
    public const DUAL_DISP_SCREEN = 'Dual Disp. Screen';
    public const SLIP_PRINT_ORDER = 'Slip Print Order';
    public const TIPS_HANDLING = 'Tips handling';
    public const SKIP_MERCHANT_RECEIPT = 'Skip Merchant Receipt';
    public const SKIP_CUSTOMER_RECEIPT = 'Skip Customer Receipt';
    public const DISABLE_VOID_CARD_PROMPT = 'Disable Void Card Prompt';
    public const POST_TRANSACTION_AFTER_VOID = 'Post Transaction after Void';
    public const USE_NUMPAD = 'Use Numpad';
    public const INCLUDE_E_F_T_Z_REPORT = 'Include EFT ZReport';
    public const ALLOW_BLOCKED_ITEMS_MOBILE_P_O_S = 'Allow Blocked Items Mobile POS';
    public const OPEN_DRAWER_THEN_PRINT = 'Open drawer then print';
    public const E_F_T_AUTO_RECOVERY_ATTEMPTS = 'EFT Auto Recovery Attempts';
    public const P_O_S_SEARCH_ENGINE = 'POS Search Engine';
    public const SALES_ORDER_NOS = 'Sales Order Nos.';
    public const ITEM_FILTERING_METHOD = 'Item Filtering Method';
    public const SHOW_NUMBERPAD = 'Show Numberpad';
    public const DEVICE_TYPE = 'Device Type';
    public const DEVICE_LICENSE_KEY = 'Device License Key';
    public const COMPUTER_NAME = 'Computer Name';
    public const POS_TERMINAL_GUID = 'PosTerminalGuid';
    public const EXCLUDE_FROM_L_S_RECOMMEND = 'Exclude from LS Recommend';
    public const SYSTEM_ID = '$systemId';
    public const SYSTEM_CREATED_AT = 'SystemCreatedAt';
    public const SYSTEM_CREATED_BY = 'SystemCreatedBy';
    public const SYSTEM_MODIFIED_AT = 'SystemModifiedAt';
    public const SYSTEM_MODIFIED_BY = 'SystemModifiedBy';

    public function getStoreNo(): ?string
    {
        return $this->getData(self::STORE_NO);
    }

    public function setStoreNo(string $value): self
    {
        return $this->setData(self::STORE_NO, $value);
    }
    public function getNo(): ?string
    {
        return $this->getData(self::NO);
    }

    public function setNo(string $value): self
    {
        return $this->setData(self::NO, $value);
    }
    public function getTerminalType(): ?string
    {
        return $this->getData(self::TERMINAL_TYPE);
    }

    public function setTerminalType(string $value): self
    {
        return $this->setData(self::TERMINAL_TYPE, $value);
    }
    public function getDescription(): ?string
    {
        return $this->getData(self::DESCRIPTION);
    }

    public function setDescription(string $value): self
    {
        return $this->setData(self::DESCRIPTION, $value);
    }
    public function getPlacement(): ?string
    {
        return $this->getData(self::PLACEMENT);
    }

    public function setPlacement(string $value): self
    {
        return $this->setData(self::PLACEMENT, $value);
    }
    public function getStatementMethod(): ?string
    {
        return $this->getData(self::STATEMENT_METHOD);
    }

    public function setStatementMethod(string $value): self
    {
        return $this->setData(self::STATEMENT_METHOD, $value);
    }
    public function getTerminalStatement(): ?bool
    {
        return $this->getData(self::TERMINAL_STATEMENT);
    }

    public function setTerminalStatement(bool $value): self
    {
        return $this->setData(self::TERMINAL_STATEMENT, $value);
    }
    public function getDefaultPriceGroup(): ?string
    {
        return $this->getData(self::DEFAULT_PRICE_GROUP);
    }

    public function setDefaultPriceGroup(string $value): self
    {
        return $this->setData(self::DEFAULT_PRICE_GROUP, $value);
    }
    public function getNotActive(): ?bool
    {
        return $this->getData(self::NOT_ACTIVE);
    }

    public function setNotActive(bool $value): self
    {
        return $this->setData(self::NOT_ACTIVE, $value);
    }
    public function getTerminalNetworkID(): ?string
    {
        return $this->getData(self::TERMINAL_NETWORK_I_D);
    }

    public function setTerminalNetworkID(string $value): self
    {
        return $this->setData(self::TERMINAL_NETWORK_I_D, $value);
    }
    public function getTerminalIPAddress(): ?string
    {
        return $this->getData(self::TERMINAL_I_P_ADDRESS);
    }

    public function setTerminalIPAddress(string $value): self
    {
        return $this->setData(self::TERMINAL_I_P_ADDRESS, $value);
    }
    public function getTerminalConnection(): ?string
    {
        return $this->getData(self::TERMINAL_CONNECTION);
    }

    public function setTerminalConnection(string $value): self
    {
        return $this->setData(self::TERMINAL_CONNECTION, $value);
    }
    public function getShowItemImage(): ?bool
    {
        return $this->getData(self::SHOW_ITEM_IMAGE);
    }

    public function setShowItemImage(bool $value): self
    {
        return $this->setData(self::SHOW_ITEM_IMAGE, $value);
    }
    public function getShowItemHtml(): ?bool
    {
        return $this->getData(self::SHOW_ITEM_HTML);
    }

    public function setShowItemHtml(bool $value): self
    {
        return $this->setData(self::SHOW_ITEM_HTML, $value);
    }
    public function getShowOfferHtml(): ?bool
    {
        return $this->getData(self::SHOW_OFFER_HTML);
    }

    public function setShowOfferHtml(bool $value): self
    {
        return $this->setData(self::SHOW_OFFER_HTML, $value);
    }
    public function getDisplayTerminalClosed(): ?bool
    {
        return $this->getData(self::DISPLAY_TERMINAL_CLOSED);
    }

    public function setDisplayTerminalClosed(bool $value): self
    {
        return $this->setData(self::DISPLAY_TERMINAL_CLOSED, $value);
    }
    public function getDisplayLinkedItem(): ?bool
    {
        return $this->getData(self::DISPLAY_LINKED_ITEM);
    }

    public function setDisplayLinkedItem(bool $value): self
    {
        return $this->setData(self::DISPLAY_LINKED_ITEM, $value);
    }
    public function getFraudSortField(): ?string
    {
        return $this->getData(self::FRAUD_SORT_FIELD);
    }

    public function setFraudSortField(string $value): self
    {
        return $this->setData(self::FRAUD_SORT_FIELD, $value);
    }
    public function getManagerKeyOnReturn(): ?bool
    {
        return $this->getData(self::MANAGER_KEY_ON_RETURN);
    }

    public function setManagerKeyOnReturn(bool $value): self
    {
        return $this->setData(self::MANAGER_KEY_ON_RETURN, $value);
    }
    public function getKeyLockStaffPermGroup(): ?string
    {
        return $this->getData(self::KEY_LOCK_STAFF_PERM_GROUP);
    }

    public function setKeyLockStaffPermGroup(string $value): self
    {
        return $this->setData(self::KEY_LOCK_STAFF_PERM_GROUP, $value);
    }
    public function getSlipIfReturn(): ?string
    {
        return $this->getData(self::SLIP_IF_RETURN);
    }

    public function setSlipIfReturn(string $value): self
    {
        return $this->setData(self::SLIP_IF_RETURN, $value);
    }
    public function getOpenDrawerAtLILO(): ?bool
    {
        return $this->getData(self::OPEN_DRAWER_AT_L_I_L_O);
    }

    public function setOpenDrawerAtLILO(bool $value): self
    {
        return $this->setData(self::OPEN_DRAWER_AT_L_I_L_O, $value);
    }
    public function getOnlyTotalInSuspTrans(): ?bool
    {
        return $this->getData(self::ONLY_TOTAL_IN_SUSP_TRANS);
    }

    public function setOnlyTotalInSuspTrans(bool $value): self
    {
        return $this->setData(self::ONLY_TOTAL_IN_SUSP_TRANS, $value);
    }
    public function getExitAfterEachTrans(): ?bool
    {
        return $this->getData(self::EXIT_AFTER_EACH_TRANS);
    }

    public function setExitAfterEachTrans(bool $value): self
    {
        return $this->setData(self::EXIT_AFTER_EACH_TRANS, $value);
    }
    public function getAutoLogoffAfterMin(): ?int
    {
        return $this->getData(self::AUTO_LOGOFF_AFTER_MIN);
    }

    public function setAutoLogoffAfterMin(int $value): self
    {
        return $this->setData(self::AUTO_LOGOFF_AFTER_MIN, $value);
    }
    public function getAllowAutoLogoffInSalesMode(): ?bool
    {
        return $this->getData(self::ALLOW_AUTO_LOGOFF_IN_SALES_MODE);
    }

    public function setAllowAutoLogoffInSalesMode(bool $value): self
    {
        return $this->setData(self::ALLOW_AUTO_LOGOFF_IN_SALES_MODE, $value);
    }
    public function getReturnInTransaction(): ?bool
    {
        return $this->getData(self::RETURN_IN_TRANSACTION);
    }

    public function setReturnInTransaction(bool $value): self
    {
        return $this->setData(self::RETURN_IN_TRANSACTION, $value);
    }
    public function getItemNoOnReceipt(): ?string
    {
        return $this->getData(self::ITEM_NO_ON_RECEIPT);
    }

    public function setItemNoOnReceipt(string $value): self
    {
        return $this->setData(self::ITEM_NO_ON_RECEIPT, $value);
    }
    public function getPrintReceiptForNegAdj(): ?bool
    {
        return $this->getData(self::PRINT_RECEIPT_FOR_NEG_ADJ);
    }

    public function setPrintReceiptForNegAdj(bool $value): self
    {
        return $this->setData(self::PRINT_RECEIPT_FOR_NEG_ADJ, $value);
    }
    public function getEFTEmbeddedReceipt(): ?bool
    {
        return $this->getData(self::E_F_T_EMBEDDED_RECEIPT);
    }

    public function setEFTEmbeddedReceipt(bool $value): self
    {
        return $this->setData(self::E_F_T_EMBEDDED_RECEIPT, $value);
    }
    public function getUseReferencedRefunds(): ?bool
    {
        return $this->getData(self::USE_REFERENCED_REFUNDS);
    }

    public function setUseReferencedRefunds(bool $value): self
    {
        return $this->setData(self::USE_REFERENCED_REFUNDS, $value);
    }
    public function getLastDateModified(): ?string
    {
        return $this->getData(self::LAST_DATE_MODIFIED);
    }

    public function setLastDateModified(string $value): self
    {
        return $this->setData(self::LAST_DATE_MODIFIED, $value);
    }
    public function getPrintReceiptLogo(): ?string
    {
        return $this->getData(self::PRINT_RECEIPT_LOGO);
    }

    public function setPrintReceiptLogo(string $value): self
    {
        return $this->setData(self::PRINT_RECEIPT_LOGO, $value);
    }
    public function getPrintReceiptBitmapNo(): ?int
    {
        return $this->getData(self::PRINT_RECEIPT_BITMAP_NO);
    }

    public function setPrintReceiptBitmapNo(int $value): self
    {
        return $this->setData(self::PRINT_RECEIPT_BITMAP_NO, $value);
    }
    public function getRcptTextMaxLength(): ?int
    {
        return $this->getData(self::RCPT_TEXT_MAX_LENGTH);
    }

    public function setRcptTextMaxLength(int $value): self
    {
        return $this->setData(self::RCPT_TEXT_MAX_LENGTH, $value);
    }
    public function getNoOfTopBottomLines(): ?int
    {
        return $this->getData(self::NO_OF_TOP_BOTTOM_LINES);
    }

    public function setNoOfTopBottomLines(int $value): self
    {
        return $this->setData(self::NO_OF_TOP_BOTTOM_LINES, $value);
    }
    public function getReceiptBarcode(): ?bool
    {
        return $this->getData(self::RECEIPT_BARCODE);
    }

    public function setReceiptBarcode(bool $value): self
    {
        return $this->setData(self::RECEIPT_BARCODE, $value);
    }
    public function getReceiptSetupLocation(): ?string
    {
        return $this->getData(self::RECEIPT_SETUP_LOCATION);
    }

    public function setReceiptSetupLocation(string $value): self
    {
        return $this->setData(self::RECEIPT_SETUP_LOCATION, $value);
    }
    public function getDisplayTextMaxLength(): ?int
    {
        return $this->getData(self::DISPLAY_TEXT_MAX_LENGTH);
    }

    public function setDisplayTextMaxLength(int $value): self
    {
        return $this->setData(self::DISPLAY_TEXT_MAX_LENGTH, $value);
    }
    public function getCustomerDisplayText1(): ?string
    {
        return $this->getData(self::CUSTOMER_DISPLAY_TEXT_1);
    }

    public function setCustomerDisplayText1(string $value): self
    {
        return $this->setData(self::CUSTOMER_DISPLAY_TEXT_1, $value);
    }
    public function getCustomerDisplayText2(): ?string
    {
        return $this->getData(self::CUSTOMER_DISPLAY_TEXT_2);
    }

    public function setCustomerDisplayText2(string $value): self
    {
        return $this->setData(self::CUSTOMER_DISPLAY_TEXT_2, $value);
    }
    public function getPrintReceiptBCType(): ?string
    {
        return $this->getData(self::PRINT_RECEIPT_B_C_TYPE);
    }

    public function setPrintReceiptBCType(string $value): self
    {
        return $this->setData(self::PRINT_RECEIPT_B_C_TYPE, $value);
    }
    public function getReceiptBarcodeWidth(): ?int
    {
        return $this->getData(self::RECEIPT_BARCODE_WIDTH);
    }

    public function setReceiptBarcodeWidth(int $value): self
    {
        return $this->setData(self::RECEIPT_BARCODE_WIDTH, $value);
    }
    public function getReceiptBarcodeHeight(): ?int
    {
        return $this->getData(self::RECEIPT_BARCODE_HEIGHT);
    }

    public function setReceiptBarcodeHeight(int $value): self
    {
        return $this->setData(self::RECEIPT_BARCODE_HEIGHT, $value);
    }
    public function getOnlineTransBackup(): ?bool
    {
        return $this->getData(self::ONLINE_TRANS_BACKUP);
    }

    public function setOnlineTransBackup(bool $value): self
    {
        return $this->setData(self::ONLINE_TRANS_BACKUP, $value);
    }
    public function getSumOfTransNo(): ?string
    {
        return $this->getData(self::SUM_OF_TRANS_NO);
    }

    public function setSumOfTransNo(string $value): self
    {
        return $this->setData(self::SUM_OF_TRANS_NO, $value);
    }
    public function getCountOfTrans(): ?int
    {
        return $this->getData(self::COUNT_OF_TRANS);
    }

    public function setCountOfTrans(int $value): self
    {
        return $this->setData(self::COUNT_OF_TRANS, $value);
    }
    public function getNoSeries(): ?string
    {
        return $this->getData(self::NO_SERIES);
    }

    public function setNoSeries(string $value): self
    {
        return $this->setData(self::NO_SERIES, $value);
    }
    public function getTableGroup(): ?string
    {
        return $this->getData(self::TABLE_GROUP);
    }

    public function setTableGroup(string $value): self
    {
        return $this->setData(self::TABLE_GROUP, $value);
    }
    public function getTableViewAtLogon(): ?bool
    {
        return $this->getData(self::TABLE_VIEW_AT_LOGON);
    }

    public function setTableViewAtLogon(bool $value): self
    {
        return $this->setData(self::TABLE_VIEW_AT_LOGON, $value);
    }
    public function getOperationalMode(): ?string
    {
        return $this->getData(self::OPERATIONAL_MODE);
    }

    public function setOperationalMode(string $value): self
    {
        return $this->setData(self::OPERATIONAL_MODE, $value);
    }
    public function getRecPrintingOffByDefault(): ?bool
    {
        return $this->getData(self::REC_PRINTING_OFF_BY_DEFAULT);
    }

    public function setRecPrintingOffByDefault(bool $value): self
    {
        return $this->setData(self::REC_PRINTING_OFF_BY_DEFAULT, $value);
    }
    public function getDefaultSalesType(): ?string
    {
        return $this->getData(self::DEFAULT_SALES_TYPE);
    }

    public function setDefaultSalesType(string $value): self
    {
        return $this->setData(self::DEFAULT_SALES_TYPE, $value);
    }
    public function getFBTakeawaySalesType(): ?string
    {
        return $this->getData(self::F_B_TAKEAWAY_SALES_TYPE);
    }

    public function setFBTakeawaySalesType(string $value): self
    {
        return $this->setData(self::F_B_TAKEAWAY_SALES_TYPE, $value);
    }
    public function getDeliverySalesType(): ?string
    {
        return $this->getData(self::DELIVERY_SALES_TYPE);
    }

    public function setDeliverySalesType(string $value): self
    {
        return $this->setData(self::DELIVERY_SALES_TYPE, $value);
    }
    public function getSafeNo(): ?string
    {
        return $this->getData(self::SAFE_NO);
    }

    public function setSafeNo(string $value): self
    {
        return $this->setData(self::SAFE_NO, $value);
    }
    public function getStaffLoginValidation(): ?string
    {
        return $this->getData(self::STAFF_LOGIN_VALIDATION);
    }

    public function setStaffLoginValidation(string $value): self
    {
        return $this->setData(self::STAFF_LOGIN_VALIDATION, $value);
    }
    public function getExcludeFromCashMgnt(): ?bool
    {
        return $this->getData(self::EXCLUDE_FROM_CASH_MGNT);
    }

    public function setExcludeFromCashMgnt(bool $value): self
    {
        return $this->setData(self::EXCLUDE_FROM_CASH_MGNT, $value);
    }
    public function getLastZReport(): ?string
    {
        return $this->getData(self::LAST_Z_REPORT);
    }

    public function setLastZReport(string $value): self
    {
        return $this->setData(self::LAST_Z_REPORT, $value);
    }
    public function getLastYReport(): ?string
    {
        return $this->getData(self::LAST_Y_REPORT);
    }

    public function setLastYReport(string $value): self
    {
        return $this->setData(self::LAST_Y_REPORT, $value);
    }
    public function getHardwareProfile(): ?string
    {
        return $this->getData(self::HARDWARE_PROFILE);
    }

    public function setHardwareProfile(string $value): self
    {
        return $this->setData(self::HARDWARE_PROFILE, $value);
    }
    public function getMenuProfile(): ?string
    {
        return $this->getData(self::MENU_PROFILE);
    }

    public function setMenuProfile(string $value): self
    {
        return $this->setData(self::MENU_PROFILE, $value);
    }
    public function getInterfaceProfile(): ?string
    {
        return $this->getData(self::INTERFACE_PROFILE);
    }

    public function setInterfaceProfile(string $value): self
    {
        return $this->setData(self::INTERFACE_PROFILE, $value);
    }
    public function getFunctionalityProfile(): ?string
    {
        return $this->getData(self::FUNCTIONALITY_PROFILE);
    }

    public function setFunctionalityProfile(string $value): self
    {
        return $this->setData(self::FUNCTIONALITY_PROFILE, $value);
    }
    public function getStyleProfile(): ?string
    {
        return $this->getData(self::STYLE_PROFILE);
    }

    public function setStyleProfile(string $value): self
    {
        return $this->setData(self::STYLE_PROFILE, $value);
    }
    public function getSSKProfileID(): ?string
    {
        return $this->getData(self::S_S_K_PROFILE_I_D);
    }

    public function setSSKProfileID(string $value): self
    {
        return $this->setData(self::S_S_K_PROFILE_I_D, $value);
    }
    public function getSSKTerminalEnabled(): ?bool
    {
        return $this->getData(self::S_S_K_TERMINAL_ENABLED);
    }

    public function setSSKTerminalEnabled(bool $value): self
    {
        return $this->setData(self::S_S_K_TERMINAL_ENABLED, $value);
    }
    public function getPrintVATRefundChecks(): ?bool
    {
        return $this->getData(self::PRINT_V_A_T_REFUND_CHECKS);
    }

    public function setPrintVATRefundChecks(bool $value): self
    {
        return $this->setData(self::PRINT_V_A_T_REFUND_CHECKS, $value);
    }
    public function getPrintSuspendWithPrepayment(): ?bool
    {
        return $this->getData(self::PRINT_SUSPEND_WITH_PREPAYMENT);
    }

    public function setPrintSuspendWithPrepayment(bool $value): self
    {
        return $this->setData(self::PRINT_SUSPEND_WITH_PREPAYMENT, $value);
    }
    public function getPrintNumberOfItems(): ?bool
    {
        return $this->getData(self::PRINT_NUMBER_OF_ITEMS);
    }

    public function setPrintNumberOfItems(bool $value): self
    {
        return $this->setData(self::PRINT_NUMBER_OF_ITEMS, $value);
    }
    public function getPrintTotalSavings(): ?bool
    {
        return $this->getData(self::PRINT_TOTAL_SAVINGS);
    }

    public function setPrintTotalSavings(bool $value): self
    {
        return $this->setData(self::PRINT_TOTAL_SAVINGS, $value);
    }
    public function getPrintDiscountDetail(): ?bool
    {
        return $this->getData(self::PRINT_DISCOUNT_DETAIL);
    }

    public function setPrintDiscountDetail(bool $value): self
    {
        return $this->setData(self::PRINT_DISCOUNT_DETAIL, $value);
    }
    public function getSecondHardwareProfile(): ?string
    {
        return $this->getData(self::SECOND_HARDWARE_PROFILE);
    }

    public function setSecondHardwareProfile(string $value): self
    {
        return $this->setData(self::SECOND_HARDWARE_PROFILE, $value);
    }
    public function getPrintSecondReceipt(): ?bool
    {
        return $this->getData(self::PRINT_SECOND_RECEIPT);
    }

    public function setPrintSecondReceipt(bool $value): self
    {
        return $this->setData(self::PRINT_SECOND_RECEIPT, $value);
    }
    public function getSalesTypeFilter(): ?string
    {
        return $this->getData(self::SALES_TYPE_FILTER);
    }

    public function setSalesTypeFilter(string $value): self
    {
        return $this->setData(self::SALES_TYPE_FILTER, $value);
    }
    public function getCopyOfMenuProfile(): ?string
    {
        return $this->getData(self::COPY_OF_MENU_PROFILE);
    }

    public function setCopyOfMenuProfile(string $value): self
    {
        return $this->setData(self::COPY_OF_MENU_PROFILE, $value);
    }
    public function getCopyOfInterfaceProfile(): ?string
    {
        return $this->getData(self::COPY_OF_INTERFACE_PROFILE);
    }

    public function setCopyOfInterfaceProfile(string $value): self
    {
        return $this->setData(self::COPY_OF_INTERFACE_PROFILE, $value);
    }
    public function getIdleTimerInterval(): ?string
    {
        return $this->getData(self::IDLE_TIMER_INTERVAL);
    }

    public function setIdleTimerInterval(string $value): self
    {
        return $this->setData(self::IDLE_TIMER_INTERVAL, $value);
    }
    public function getExternalPrinterID(): ?string
    {
        return $this->getData(self::EXTERNAL_PRINTER_I_D);
    }

    public function setExternalPrinterID(string $value): self
    {
        return $this->setData(self::EXTERNAL_PRINTER_I_D, $value);
    }
    public function getHospTypePopUpOnLogon(): ?string
    {
        return $this->getData(self::HOSP_TYPE_POPUP_ON_LOGON);
    }

    public function setHospTypePopUpOnLogon(string $value): self
    {
        return $this->setData(self::HOSP_TYPE_POPUP_ON_LOGON, $value);
    }
    public function getReceiptBarcodeID(): ?int
    {
        return $this->getData(self::RECEIPT_BARCODE_I_D);
    }

    public function setReceiptBarcodeID(int $value): self
    {
        return $this->setData(self::RECEIPT_BARCODE_I_D, $value);
    }
    public function getPrinterKOTStatusAfterSent(): ?string
    {
        return $this->getData(self::PRINTER_K_O_T_STATUS_AFTER_SENT);
    }

    public function setPrinterKOTStatusAfterSent(string $value): self
    {
        return $this->setData(self::PRINTER_K_O_T_STATUS_AFTER_SENT, $value);
    }
    public function getSalesSlip(): ?string
    {
        return $this->getData(self::SALES_SLIP);
    }

    public function setSalesSlip(string $value): self
    {
        return $this->setData(self::SALES_SLIP, $value);
    }
    public function getVoidSlip(): ?string
    {
        return $this->getData(self::VOID_SLIP);
    }

    public function setVoidSlip(string $value): self
    {
        return $this->setData(self::VOID_SLIP, $value);
    }
    public function getOnlyEmailSalesTransactions(): ?bool
    {
        return $this->getData(self::ONLY_EMAIL_SALES_TRANSACTIONS);
    }

    public function setOnlyEmailSalesTransactions(bool $value): self
    {
        return $this->setData(self::ONLY_EMAIL_SALES_TRANSACTIONS, $value);
    }
    public function getBCCEMailAddress(): ?string
    {
        return $this->getData(self::B_C_C_E_MAIL_ADDRESS);
    }

    public function setBCCEMailAddress(string $value): self
    {
        return $this->setData(self::B_C_C_E_MAIL_ADDRESS, $value);
    }
    public function getInventoryMainMenu(): ?string
    {
        return $this->getData(self::INVENTORY_MAIN_MENU);
    }

    public function setInventoryMainMenu(string $value): self
    {
        return $this->setData(self::INVENTORY_MAIN_MENU, $value);
    }
    public function getInventoryNoOfRecords(): ?int
    {
        return $this->getData(self::INVENTORY_NO_OF_RECORDS);
    }

    public function setInventoryNoOfRecords(int $value): self
    {
        return $this->setData(self::INVENTORY_NO_OF_RECORDS, $value);
    }
    public function getAllowPostIMDocuments(): ?bool
    {
        return $this->getData(self::ALLOW_POST_I_M_DOCUMENTS);
    }

    public function setAllowPostIMDocuments(bool $value): self
    {
        return $this->setData(self::ALLOW_POST_I_M_DOCUMENTS, $value);
    }
    public function getASNQuantityMethod(): ?string
    {
        return $this->getData(self::A_S_N_QUANTITY_METHOD);
    }

    public function setASNQuantityMethod(string $value): self
    {
        return $this->setData(self::A_S_N_QUANTITY_METHOD, $value);
    }
    public function getDualDispEnabled(): ?bool
    {
        return $this->getData(self::DUAL_DISP_ENABLED);
    }

    public function setDualDispEnabled(bool $value): self
    {
        return $this->setData(self::DUAL_DISP_ENABLED, $value);
    }
    public function getDualDispStyleProfile(): ?string
    {
        return $this->getData(self::DUAL_DISP_STYLE_PROFILE);
    }

    public function setDualDispStyleProfile(string $value): self
    {
        return $this->setData(self::DUAL_DISP_STYLE_PROFILE, $value);
    }
    public function getDualDispInterfaceProfile(): ?string
    {
        return $this->getData(self::DUAL_DISP_INTERFACE_PROFILE);
    }

    public function setDualDispInterfaceProfile(string $value): self
    {
        return $this->setData(self::DUAL_DISP_INTERFACE_PROFILE, $value);
    }
    public function getDualDispMenuProfile(): ?string
    {
        return $this->getData(self::DUAL_DISP_MENU_PROFILE);
    }

    public function setDualDispMenuProfile(string $value): self
    {
        return $this->setData(self::DUAL_DISP_MENU_PROFILE, $value);
    }
    public function getDualDispSlideshow(): ?string
    {
        return $this->getData(self::DUAL_DISP_SLIDESHOW);
    }

    public function setDualDispSlideshow(string $value): self
    {
        return $this->setData(self::DUAL_DISP_SLIDESHOW, $value);
    }
    public function getDualDispScreen(): ?int
    {
        return $this->getData(self::DUAL_DISP_SCREEN);
    }

    public function setDualDispScreen(int $value): self
    {
        return $this->setData(self::DUAL_DISP_SCREEN, $value);
    }
    public function getSlipPrintOrder(): ?string
    {
        return $this->getData(self::SLIP_PRINT_ORDER);
    }

    public function setSlipPrintOrder(string $value): self
    {
        return $this->setData(self::SLIP_PRINT_ORDER, $value);
    }
    public function getTipsHandling(): ?string
    {
        return $this->getData(self::TIPS_HANDLING);
    }

    public function setTipsHandling(string $value): self
    {
        return $this->setData(self::TIPS_HANDLING, $value);
    }
    public function getSkipMerchantReceipt(): ?bool
    {
        return $this->getData(self::SKIP_MERCHANT_RECEIPT);
    }

    public function setSkipMerchantReceipt(bool $value): self
    {
        return $this->setData(self::SKIP_MERCHANT_RECEIPT, $value);
    }
    public function getSkipCustomerReceipt(): ?bool
    {
        return $this->getData(self::SKIP_CUSTOMER_RECEIPT);
    }

    public function setSkipCustomerReceipt(bool $value): self
    {
        return $this->setData(self::SKIP_CUSTOMER_RECEIPT, $value);
    }
    public function getDisableVoidCardPrompt(): ?bool
    {
        return $this->getData(self::DISABLE_VOID_CARD_PROMPT);
    }

    public function setDisableVoidCardPrompt(bool $value): self
    {
        return $this->setData(self::DISABLE_VOID_CARD_PROMPT, $value);
    }
    public function getPostTransactionAfterVoid(): ?bool
    {
        return $this->getData(self::POST_TRANSACTION_AFTER_VOID);
    }

    public function setPostTransactionAfterVoid(bool $value): self
    {
        return $this->setData(self::POST_TRANSACTION_AFTER_VOID, $value);
    }
    public function getUseNumpad(): ?bool
    {
        return $this->getData(self::USE_NUMPAD);
    }

    public function setUseNumpad(bool $value): self
    {
        return $this->setData(self::USE_NUMPAD, $value);
    }
    public function getIncludeEFTZReport(): ?string
    {
        return $this->getData(self::INCLUDE_E_F_T_Z_REPORT);
    }

    public function setIncludeEFTZReport(string $value): self
    {
        return $this->setData(self::INCLUDE_E_F_T_Z_REPORT, $value);
    }
    public function getAllowBlockedItemsMobilePOS(): ?bool
    {
        return $this->getData(self::ALLOW_BLOCKED_ITEMS_MOBILE_P_O_S);
    }

    public function setAllowBlockedItemsMobilePOS(bool $value): self
    {
        return $this->setData(self::ALLOW_BLOCKED_ITEMS_MOBILE_P_O_S, $value);
    }
    public function getOpenDrawerThenPrint(): ?bool
    {
        return $this->getData(self::OPEN_DRAWER_THEN_PRINT);
    }

    public function setOpenDrawerThenPrint(bool $value): self
    {
        return $this->setData(self::OPEN_DRAWER_THEN_PRINT, $value);
    }
    public function getEFTAutoRecoveryAttempts(): ?int
    {
        return $this->getData(self::E_F_T_AUTO_RECOVERY_ATTEMPTS);
    }

    public function setEFTAutoRecoveryAttempts(int $value): self
    {
        return $this->setData(self::E_F_T_AUTO_RECOVERY_ATTEMPTS, $value);
    }
    public function getPOSSearchEngine(): ?string
    {
        return $this->getData(self::P_O_S_SEARCH_ENGINE);
    }

    public function setPOSSearchEngine(string $value): self
    {
        return $this->setData(self::P_O_S_SEARCH_ENGINE, $value);
    }
    public function getSalesOrderNos(): ?string
    {
        return $this->getData(self::SALES_ORDER_NOS);
    }

    public function setSalesOrderNos(string $value): self
    {
        return $this->setData(self::SALES_ORDER_NOS, $value);
    }
    public function getItemFilteringMethod(): ?string
    {
        return $this->getData(self::ITEM_FILTERING_METHOD);
    }

    public function setItemFilteringMethod(string $value): self
    {
        return $this->setData(self::ITEM_FILTERING_METHOD, $value);
    }
    public function getShowNumberpad(): ?bool
    {
        return $this->getData(self::SHOW_NUMBERPAD);
    }

    public function setShowNumberpad(bool $value): self
    {
        return $this->setData(self::SHOW_NUMBERPAD, $value);
    }
    public function getDeviceType(): ?string
    {
        return $this->getData(self::DEVICE_TYPE);
    }

    public function setDeviceType(string $value): self
    {
        return $this->setData(self::DEVICE_TYPE, $value);
    }
    public function getDeviceLicenseKey(): ?string
    {
        return $this->getData(self::DEVICE_LICENSE_KEY);
    }

    public function setDeviceLicenseKey(string $value): self
    {
        return $this->setData(self::DEVICE_LICENSE_KEY, $value);
    }
    public function getComputerName(): ?string
    {
        return $this->getData(self::COMPUTER_NAME);
    }

    public function setComputerName(string $value): self
    {
        return $this->setData(self::COMPUTER_NAME, $value);
    }
    public function getPosTerminalGuid(): ?string
    {
        return $this->getData(self::POS_TERMINAL_GUID);
    }

    public function setPosTerminalGuid(string $value): self
    {
        return $this->setData(self::POS_TERMINAL_GUID, $value);
    }
    public function getExcludeFromLSRecommend(): ?bool
    {
        return $this->getData(self::EXCLUDE_FROM_L_S_RECOMMEND);
    }

    public function setExcludeFromLSRecommend(bool $value): self
    {
        return $this->setData(self::EXCLUDE_FROM_L_S_RECOMMEND, $value);
    }
    public function getSystemId(): ?string
    {
        return $this->getData(self::SYSTEM_ID);
    }

    public function setSystemId(string $value): self
    {
        return $this->setData(self::SYSTEM_ID, $value);
    }
    public function getSystemCreatedAt(): ?\DateTime
    {
        return $this->getData(self::SYSTEM_CREATED_AT);
    }

    public function setSystemCreatedAt(\DateTime $value): self
    {
        return $this->setData(self::SYSTEM_CREATED_AT, $value);
    }
    public function getSystemCreatedBy(): ?string
    {
        return $this->getData(self::SYSTEM_CREATED_BY);
    }

    public function setSystemCreatedBy(string $value): self
    {
        return $this->setData(self::SYSTEM_CREATED_BY, $value);
    }
    public function getSystemModifiedAt(): ?\DateTime
    {
        return $this->getData(self::SYSTEM_MODIFIED_AT);
    }

    public function setSystemModifiedAt(\DateTime $value): self
    {
        return $this->setData(self::SYSTEM_MODIFIED_AT, $value);
    }
    public function getSystemModifiedBy(): ?string
    {
        return $this->getData(self::SYSTEM_MODIFIED_BY);
    }

    public function setSystemModifiedBy(string $value): self
    {
        return $this->setData(self::SYSTEM_MODIFIED_BY, $value);
    }
}