<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\Ecommerce\Entity;

use Magento\Framework\DataObject;

class LSCWIMixMatchOfferExt extends DataObject
{
    public const OFFER_NO = 'Offer No.';
    public const STORE_NO = 'Store No.';
    public const ITEM_NO = 'Item No.';
    public const VARIANT_CODE = 'Variant Code';
    public const DESCRIPTION = 'Description';
    public const TYPE = 'Type';
    public const CUSTOMER_DISC_GROUP = 'Customer Disc. Group';
    public const LOYALTY_SCHEME_CODE = 'Loyalty Scheme Code';
    public const FROM_DATE = 'From Date';
    public const TO_DATE = 'To Date';
    public const PRIORITY = 'Priority';
    public const VALIDATION_PERIOD_I_D = 'Validation Period ID';
    public const POPUP_LINE_1 = 'Pop-up Line 1';
    public const POPUP_LINE_2 = 'Pop-up Line 2';
    public const POPUP_LINE_3 = 'Pop-up Line 3';


    public function getOfferNo(): ?string
    {
        return $this->getData(self::OFFER_NO);
    }

    public function setOfferNo(string $value): self
    {
        return $this->setData(self::OFFER_NO, $value);
    }

    public function getStoreNo(): ?string
    {
        return $this->getData(self::STORE_NO);
    }

    public function setStoreNo(string $value): self
    {
        return $this->setData(self::STORE_NO, $value);
    }

    public function getItemNo(): ?string
    {
        return $this->getData(self::ITEM_NO);
    }

    public function setItemNo(string $value): self
    {
        return $this->setData(self::ITEM_NO, $value);
    }

    public function getVariantCode(): ?string
    {
        return $this->getData(self::VARIANT_CODE);
    }

    public function setVariantCode(string $value): self
    {
        return $this->setData(self::VARIANT_CODE, $value);
    }

    public function getDescription(): ?string
    {
        return $this->getData(self::DESCRIPTION);
    }

    public function setDescription(string $value): self
    {
        return $this->setData(self::DESCRIPTION, $value);
    }

    public function getType(): ?string
    {
        return $this->getData(self::TYPE);
    }

    public function setType(string $value): self
    {
        return $this->setData(self::TYPE, $value);
    }

    public function getCustomerDiscGroup(): ?string
    {
        return $this->getData(self::CUSTOMER_DISC_GROUP);
    }

    public function setCustomerDiscGroup(string $value): self
    {
        return $this->setData(self::CUSTOMER_DISC_GROUP, $value);
    }

    public function getLoyaltySchemeCode(): ?string
    {
        return $this->getData(self::LOYALTY_SCHEME_CODE);
    }

    public function setLoyaltySchemeCode(string $value): self
    {
        return $this->setData(self::LOYALTY_SCHEME_CODE, $value);
    }

    public function getFromDate(): ?string
    {
        return $this->getData(self::FROM_DATE);
    }

    public function setFromDate(string $value): self
    {
        return $this->setData(self::FROM_DATE, $value);
    }

    public function getToDate(): ?string
    {
        return $this->getData(self::TO_DATE);
    }

    public function setToDate(string $value): self
    {
        return $this->setData(self::TO_DATE, $value);
    }

    public function getPriority(): ?int
    {
        return $this->getData(self::PRIORITY);
    }

    public function setPriority(int $value): self
    {
        return $this->setData(self::PRIORITY, $value);
    }

    public function getValidationPeriodID(): ?string
    {
        return $this->getData(self::VALIDATION_PERIOD_I_D);
    }

    public function setValidationPeriodID(string $value): self
    {
        return $this->setData(self::VALIDATION_PERIOD_I_D, $value);
    }

    public function getPopUpLine1(): ?string
    {
        return $this->getData(self::POPUP_LINE_1);
    }

    public function setPopUpLine1(string $value): self
    {
        return $this->setData(self::POPUP_LINE_1, $value);
    }

    public function getPopUpLine2(): ?string
    {
        return $this->getData(self::POPUP_LINE_2);
    }

    public function setPopUpLine2(string $value): self
    {
        return $this->setData(self::POPUP_LINE_2, $value);
    }

    public function getPopUpLine3(): ?string
    {
        return $this->getData(self::POPUP_LINE_3);
    }

    public function setPopUpLine3(string $value): self
    {
        return $this->setData(self::POPUP_LINE_3, $value);
    }
}