<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class MemberContactUpdate extends \Magento\Catalog\Model\AbstractModel implements RequestInterface
{
    public const CLASS_NAME = 'MemberContactUpdate';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    public const MEMBER_CONTACT_UPDATE_X_M_L = 'memberContactUpdateXML';

    /**
     * @param ?string $responseCode
     * @return $this
     */
    public function setResponseCode(?string $responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResponseCode() : ?string
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param ?string $errorText
     * @return $this
     */
    public function setErrorText(?string $errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getErrorText() : ?string
    {
        return $this->getData(self::ERROR_TEXT);
    }

    /**
     * @param RootMemberContactCreate $memberContactUpdateXML
     * @return $this
     */
    public function setMemberContactUpdateXML($memberContactUpdateXML)
    {
        $this->setData(self::MEMBER_CONTACT_UPDATE_X_M_L, $memberContactUpdateXML);
        return $this;
    }

    /**
     * @return RootMemberContactCreate
     */
    public function getMemberContactUpdateXML()
    {
        return $this->getData(self::MEMBER_CONTACT_UPDATE_X_M_L);
    }
}

