<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

require_once __DIR__ . '/BaseODataRequest.php';

class ODataRequest_GetDiscountSetup extends BaseODataRequest
{
    public function getActionName(): string
    {
        return 'ODataRequest_GetDiscountSetup';
    }
}