<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\ResponseInterface;

class OrderEditResponse implements ResponseInterface
{
    /**
     * @property SalesEntry $OrderEditResult
     */
    protected $OrderEditResult = null;

    /**
     * @param SalesEntry $OrderEditResult
     * @return $this
     */
    public function setOrderEditResult($OrderEditResult)
    {
        $this->OrderEditResult = $OrderEditResult;
        return $this;
    }

    /**
     * @return SalesEntry
     */
    public function getOrderEditResult()
    {
        return $this->OrderEditResult;
    }

    /**
     * @return SalesEntry
     */
    public function getResult()
    {
        return $this->OrderEditResult;
    }
}

