<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class ReplStore
{

    /**
     * @property string $City
     */
    protected $City = null;

    /**
     * @property boolean $ClickAndCollect
     */
    protected $ClickAndCollect = null;

    /**
     * @property string $Country
     */
    protected $Country = null;

    /**
     * @property string $County
     */
    protected $County = null;

    /**
     * @property string $CultureName
     */
    protected $CultureName = null;

    /**
     * @property string $Currency
     */
    protected $Currency = null;

    /**
     * @property string $DefaultCustomerAccount
     */
    protected $DefaultCustomerAccount = null;

    /**
     * @property string $FunctionalityProfile
     */
    protected $FunctionalityProfile = null;

    /**
     * @property string $Id
     */
    protected $Id = null;

    /**
     * @property boolean $IsDeleted
     */
    protected $IsDeleted = null;

    /**
     * @property float $Latitute
     */
    protected $Latitute = null;

    /**
     * @property float $Longitude
     */
    protected $Longitude = null;

    /**
     * @property string $MainMenuID
     */
    protected $MainMenuID = null;

    /**
     * @property string $Name
     */
    protected $Name = null;

    /**
     * @property string $Phone
     */
    protected $Phone = null;

    /**
     * @property string $State
     */
    protected $State = null;

    /**
     * @property string $Street
     */
    protected $Street = null;

    /**
     * @property string $TaxGroup
     */
    protected $TaxGroup = null;

    /**
     * @property int $UserDefaultCustomerAccount
     */
    protected $UserDefaultCustomerAccount = null;

    /**
     * @property string $ZipCode
     */
    protected $ZipCode = null;

    /**
     * @property string $scope
     */
    protected $scope = null;

    /**
     * @property int $scope_id
     */
    protected $scope_id = null;

    /**
     * @param string $City
     * @return $this
     */
    public function setCity($City)
    {
        $this->City = $City;
        return $this;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->City;
    }

    /**
     * @param boolean $ClickAndCollect
     * @return $this
     */
    public function setClickAndCollect($ClickAndCollect)
    {
        $this->ClickAndCollect = $ClickAndCollect;
        return $this;
    }

    /**
     * @return boolean
     */
    public function getClickAndCollect()
    {
        return $this->ClickAndCollect;
    }

    /**
     * @param string $Country
     * @return $this
     */
    public function setCountry($Country)
    {
        $this->Country = $Country;
        return $this;
    }

    /**
     * @return string
     */
    public function getCountry()
    {
        return $this->Country;
    }

    /**
     * @param string $County
     * @return $this
     */
    public function setCounty($County)
    {
        $this->County = $County;
        return $this;
    }

    /**
     * @return string
     */
    public function getCounty()
    {
        return $this->County;
    }

    /**
     * @param string $CultureName
     * @return $this
     */
    public function setCultureName($CultureName)
    {
        $this->CultureName = $CultureName;
        return $this;
    }

    /**
     * @return string
     */
    public function getCultureName()
    {
        return $this->CultureName;
    }

    /**
     * @param string $Currency
     * @return $this
     */
    public function setCurrency($Currency)
    {
        $this->Currency = $Currency;
        return $this;
    }

    /**
     * @return string
     */
    public function getCurrency()
    {
        return $this->Currency;
    }

    /**
     * @param string $DefaultCustomerAccount
     * @return $this
     */
    public function setDefaultCustomerAccount($DefaultCustomerAccount)
    {
        $this->DefaultCustomerAccount = $DefaultCustomerAccount;
        return $this;
    }

    /**
     * @return string
     */
    public function getDefaultCustomerAccount()
    {
        return $this->DefaultCustomerAccount;
    }

    /**
     * @param string $FunctionalityProfile
     * @return $this
     */
    public function setFunctionalityProfile($FunctionalityProfile)
    {
        $this->FunctionalityProfile = $FunctionalityProfile;
        return $this;
    }

    /**
     * @return string
     */
    public function getFunctionalityProfile()
    {
        return $this->FunctionalityProfile;
    }

    /**
     * @param string $Id
     * @return $this
     */
    public function setId($Id)
    {
        $this->Id = $Id;
        return $this;
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * @param boolean $IsDeleted
     * @return $this
     */
    public function setIsDeleted($IsDeleted)
    {
        $this->IsDeleted = $IsDeleted;
        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->IsDeleted;
    }

    /**
     * @param float $Latitute
     * @return $this
     */
    public function setLatitute($Latitute)
    {
        $this->Latitute = $Latitute;
        return $this;
    }

    /**
     * @return float
     */
    public function getLatitute()
    {
        return $this->Latitute;
    }

    /**
     * @param float $Longitude
     * @return $this
     */
    public function setLongitude($Longitude)
    {
        $this->Longitude = $Longitude;
        return $this;
    }

    /**
     * @return float
     */
    public function getLongitude()
    {
        return $this->Longitude;
    }

    /**
     * @param string $MainMenuID
     * @return $this
     */
    public function setMainMenuID($MainMenuID)
    {
        $this->MainMenuID = $MainMenuID;
        return $this;
    }

    /**
     * @return string
     */
    public function getMainMenuID()
    {
        return $this->MainMenuID;
    }

    /**
     * @param string $Name
     * @return $this
     */
    public function setName($Name)
    {
        $this->Name = $Name;
        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * @param string $Phone
     * @return $this
     */
    public function setPhone($Phone)
    {
        $this->Phone = $Phone;
        return $this;
    }

    /**
     * @return string
     */
    public function getPhone()
    {
        return $this->Phone;
    }

    /**
     * @param string $State
     * @return $this
     */
    public function setState($State)
    {
        $this->State = $State;
        return $this;
    }

    /**
     * @return string
     */
    public function getState()
    {
        return $this->State;
    }

    /**
     * @param string $Street
     * @return $this
     */
    public function setStreet($Street)
    {
        $this->Street = $Street;
        return $this;
    }

    /**
     * @return string
     */
    public function getStreet()
    {
        return $this->Street;
    }

    /**
     * @param string $TaxGroup
     * @return $this
     */
    public function setTaxGroup($TaxGroup)
    {
        $this->TaxGroup = $TaxGroup;
        return $this;
    }

    /**
     * @return string
     */
    public function getTaxGroup()
    {
        return $this->TaxGroup;
    }

    /**
     * @param int $UserDefaultCustomerAccount
     * @return $this
     */
    public function setUserDefaultCustomerAccount($UserDefaultCustomerAccount)
    {
        $this->UserDefaultCustomerAccount = $UserDefaultCustomerAccount;
        return $this;
    }

    /**
     * @return int
     */
    public function getUserDefaultCustomerAccount()
    {
        return $this->UserDefaultCustomerAccount;
    }

    /**
     * @param string $ZipCode
     * @return $this
     */
    public function setZipCode($ZipCode)
    {
        $this->ZipCode = $ZipCode;
        return $this;
    }

    /**
     * @return string
     */
    public function getZipCode()
    {
        return $this->ZipCode;
    }

    /**
     * @param string $scope
     * @return $this
     */
    public function setScope($scope)
    {
        $this->scope = $scope;
        return $this;
    }

    /**
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * @param int $scope_id
     * @return $this
     */
    public function setScope_id($scope_id)
    {
        $this->scope_id = $scope_id;
        return $this;
    }

    /**
     * @return int
     */
    public function getScope_id()
    {
        return $this->scope_id;
    }


}

