<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\ResponseInterface;

class ReturnPolicyGetResponse implements ResponseInterface
{
    /**
     * @property ArrayOfReturnPolicy $ReturnPolicyGetResult
     */
    protected $ReturnPolicyGetResult = null;

    /**
     * @param ArrayOfReturnPolicy $ReturnPolicyGetResult
     * @return $this
     */
    public function setReturnPolicyGetResult($ReturnPolicyGetResult)
    {
        $this->ReturnPolicyGetResult = $ReturnPolicyGetResult;
        return $this;
    }

    /**
     * @return ArrayOfReturnPolicy
     */
    public function getReturnPolicyGetResult()
    {
        return $this->ReturnPolicyGetResult;
    }

    /**
     * @return ArrayOfReturnPolicy
     */
    public function getResult()
    {
        return $this->ReturnPolicyGetResult;
    }
}

