<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class RootGetDocumentList extends \Magento\Framework\DataObject
{
    public const CLASS_NAME = 'RootGetDocumentList';

    public const A_S_N_DELIVERY_DOCUMENT = 'ASNDeliveryDocument';

    public const P_O_S_TRANS_INV_HEADER = 'POSTrans.Inv.Header';

    /**
     * @param ASNDeliveryDocument $ASNDeliveryDocument
     * @return $this
     */
    public function setASNDeliveryDocument($ASNDeliveryDocument)
    {
        $this->setData(self::A_S_N_DELIVERY_DOCUMENT, $ASNDeliveryDocument);
        return $this;
    }

    /**
     * @return ASNDeliveryDocument
     */
    public function getASNDeliveryDocument()
    {
        return $this->getData(self::A_S_N_DELIVERY_DOCUMENT);
    }

    /**
     * @param POSTrans.Inv.Header $POSTransInvHeader
     * @return $this
     */
    public function setPOSTransInvHeader($POSTransInvHeader)
    {
        $this->setData(self::P_O_S_TRANS_INV_HEADER, $POSTransInvHeader);
        return $this;
    }

    /**
     * @return POSTrans.Inv.Header
     */
    public function getPOSTransInvHeader()
    {
        return $this->getData(self::P_O_S_TRANS_INV_HEADER);
    }
}

