<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\Ecommerce\Entity;

use Magento\Catalog\Model\AbstractModel;

class SalesPrice extends AbstractModel
{
    public const ITEM_NO = 'Item No.';
    public const SALES_CODE = 'Sales Code';
    public const CURRENCY_CODE = 'Currency Code';
    public const STARTING_DATE = 'Starting Date';
    public const UNIT_PRICE = 'Unit Price';
    public const PRICE_INCLUDES_VAT = 'Price Includes VAT';
    public const ALLOW_INVOICE_DISC = 'Allow Invoice Disc.';
    public const VAT_BUS_POSTING_GR_PRICE = 'VAT Bus. Posting Gr. (Price)';
    public const SALES_TYPE = 'Sales Type';
    public const MINIMUM_QUANTITY = 'Minimum Quantity';
    public const ENDING_DATE = 'Ending Date';
    public const UNIT_OF_MEASURE_CODE = 'Unit of Measure Code';
    public const VARIANT_CODE = 'Variant Code';
    public const ALLOW_LINE_DISC = 'Allow Line Disc.';
    public const LSC_MARKUP = 'LSC Markup %';
    public const LSC_PROFIT = 'LSC Profit %';
    public const LSC_PROFIT_LCY = 'LSC Profit (LCY)';
    public const LSC_UNIT_PRICE_INCLUDING_VAT = 'LSC Unit Price Including VAT';
    public const SYSTEMID = '$systemId';
    public const SYSTEMCREATEDAT = 'SystemCreatedAt';
    public const SYSTEMCREATEDBY = 'SystemCreatedBy';
    public const SYSTEMMODIFIEDAT = 'SystemModifiedAt';
    public const SYSTEMMODIFIEDBY = 'SystemModifiedBy';


    public function getItemNo(): ?string
    {
        return $this->getData(self::ITEM_NO);
    }

    public function setItemNo(string $value)
    {
        return $this->setData(self::ITEM_NO, $value);
    }

    public function getSalesCode(): ?string
    {
        return $this->getData(self::SALES_CODE);
    }

    public function setSalesCode(string $value)
    {
        return $this->setData(self::SALES_CODE, $value);
    }

    public function getCurrencyCode(): ?string
    {
        return $this->getData(self::CURRENCY_CODE);
    }

    public function setCurrencyCode(string $value)
    {
        return $this->setData(self::CURRENCY_CODE, $value);
    }

    public function getStartingDate(): ?string
    {
        return $this->getData(self::STARTING_DATE);
    }

    public function setStartingDate(string $value)
    {
        return $this->setData(self::STARTING_DATE, $value);
    }

    public function getUnitPrice(): ?string
    {
        return $this->getData(self::UNIT_PRICE);
    }

    public function setUnitPrice(string $value)
    {
        return $this->setData(self::UNIT_PRICE, $value);
    }

    public function getPriceIncludesVAT(): ?bool
    {
        return $this->getData(self::PRICE_INCLUDES_VAT);
    }

    public function setPriceIncludesVAT(bool $value)
    {
        return $this->setData(self::PRICE_INCLUDES_VAT, $value);
    }

    public function getAllowInvoiceDisc(): ?bool
    {
        return $this->getData(self::ALLOW_INVOICE_DISC);
    }

    public function setAllowInvoiceDisc(bool $value)
    {
        return $this->setData(self::ALLOW_INVOICE_DISC, $value);
    }

    public function getVATBusPostingGrPrice(): ?string
    {
        return $this->getData(self::VAT_BUS_POSTING_GR_PRICE);
    }

    public function setVATBusPostingGrPrice(string $value)
    {
        return $this->setData(self::VAT_BUS_POSTING_GR_PRICE, $value);
    }

    public function getSalesType(): ?string
    {
        return $this->getData(self::SALES_TYPE);
    }

    public function setSalesType(string $value)
    {
        return $this->setData(self::SALES_TYPE, $value);
    }

    public function getMinimumQuantity(): ?string
    {
        return $this->getData(self::MINIMUM_QUANTITY);
    }

    public function setMinimumQuantity(string $value)
    {
        return $this->setData(self::MINIMUM_QUANTITY, $value);
    }

    public function getEndingDate(): ?string
    {
        return $this->getData(self::ENDING_DATE);
    }

    public function setEndingDate(string $value)
    {
        return $this->setData(self::ENDING_DATE, $value);
    }

    public function getUnitOfMeasureCode(): ?string
    {
        return $this->getData(self::UNIT_OF_MEASURE_CODE);
    }

    public function setUnitOfMeasureCode(string $value)
    {
        return $this->setData(self::UNIT_OF_MEASURE_CODE, $value);
    }

    public function getVariantCode(): ?string
    {
        return $this->getData(self::VARIANT_CODE);
    }

    public function setVariantCode(string $value)
    {
        return $this->setData(self::VARIANT_CODE, $value);
    }

    public function getAllowLineDisc(): ?bool
    {
        return $this->getData(self::ALLOW_LINE_DISC);
    }

    public function setAllowLineDisc(bool $value)
    {
        return $this->setData(self::ALLOW_LINE_DISC, $value);
    }

    public function getLSCMarkup(): ?string
    {
        return $this->getData(self::LSC_MARKUP);
    }

    public function setLSCMarkup(string $value)
    {
        return $this->setData(self::LSC_MARKUP, $value);
    }

    public function getLSCProfit(): ?string
    {
        return $this->getData(self::LSC_PROFIT);
    }

    public function setLSCProfit(string $value)
    {
        return $this->setData(self::LSC_PROFIT, $value);
    }

    public function getLSCProfitLCY(): ?string
    {
        return $this->getData(self::LSC_PROFIT_LCY);
    }

    public function setLSCProfitLCY(string $value)
    {
        return $this->setData(self::LSC_PROFIT_LCY, $value);
    }

    public function getLSCUnitPriceIncludingVAT(): ?string
    {
        return $this->getData(self::LSC_UNIT_PRICE_INCLUDING_VAT);
    }

    public function setLSCUnitPriceIncludingVAT(string $value)
    {
        return $this->setData(self::LSC_UNIT_PRICE_INCLUDING_VAT, $value);
    }

    public function getSystemId(): ?string
    {
        return $this->getData(self::SYSTEMID);
    }

    public function setSystemId(string $value)
    {
        return $this->setData(self::SYSTEMID, $value);
    }

    public function getSystemCreatedAt(): ?\DateTime
    {
        return $this->getData(self::SYSTEMCREATEDAT);
    }

    public function setSystemCreatedAt(\DateTime $value)
    {
        return $this->setData(self::SYSTEMCREATEDAT, $value);
    }

    public function getSystemCreatedBy(): ?string
    {
        return $this->getData(self::SYSTEMCREATEDBY);
    }

    public function setSystemCreatedBy(string $value)
    {
        return $this->setData(self::SYSTEMCREATEDBY, $value);
    }

    public function getSystemModifiedAt(): ?\DateTime
    {
        return $this->getData(self::SYSTEMMODIFIEDAT);
    }

    public function setSystemModifiedAt(\DateTime $value)
    {
        return $this->setData(self::SYSTEMMODIFIEDAT, $value);
    }

    public function getSystemModifiedBy(): ?string
    {
        return $this->getData(self::SYSTEMMODIFIEDBY);
    }

    public function setSystemModifiedBy(string $value)
    {
        return $this->setData(self::SYSTEMMODIFIEDBY, $value);
    }
}