<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class Staff extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'Staff';

    public const I_D = 'ID';

    public const PASSWORD = 'Password';

    public const CHANGE_PASSWORD = 'Change_Password';

    public const STORE_NO = 'Store_No.';

    public const VOID_TRANSACTION = 'Void_Transaction';

    public const MANAGER_PRIVILEGES = 'Manager_Privileges';

    public const X_Z_Y_REPORT_PRINTING = 'XZY-Report_Printing';

    public const TENDER_DECLARATION = 'Tender_Declaration';

    public const FLOATING_DECLARATION = 'Floating_Declaration';

    public const PRICE_OVERRIDE = 'Price_Override';

    public const MAX_DISCOUNTTO_GIVE = 'Max._Discount_to_Give__';

    public const SUSPEND_TRANSACTION = 'Suspend_Transaction';

    public const MAX_TOTAL_DISCOUNT = 'Max._Total_Discount__';

    public const OPEN_DRAWWITHOUT_SALE = 'Open_Draw._without_Sale';

    public const FIRST_NAME = 'First_Name';

    public const LAST_NAME = 'Last_Name';

    public const EMPLOYMENT_TYPE = 'Employment_Type';

    public const LAST_DATE_MODIFIED = 'Last_Date_Modified';

    public const NAMEON_RECEIPT = 'Name_on_Receipt';

    public const ADDRESS = 'Address';

    public const ADDRESS2 = 'Address_2';

    public const CITY = 'City';

    public const POST_CODE = 'Post_Code';

    public const HOME_PHONE_NO = 'Home_Phone_No.';

    public const WORK_PHONE_NO = 'Work_Phone_No.';

    public const HOURLY_RATE = 'Hourly_Rate';

    public const PAYROLL_NO = 'Payroll_No.';

    public const BLOCKED = 'Blocked';

    public const DATETO_BE_BLOCKED = 'Date_to_Be_Blocked';

    public const LEFT_HANDED = 'Left_Handed';

    public const SALES_PERSON = 'Sales_Person';

    public const NO_SERIES = 'No._Series';

    public const PERMISSION_GROUP = 'Permission_Group';

    public const RETURNIN_TRANSACTION = 'Return_in_Transaction';

    public const VOID_PREPAYMENT = 'Void_Prepayment';

    public const VOID_PREPAYMENT_LINE = 'Void_Prepayment_Line';

    public const CHANGE_PREPMT_AMT = 'Change_Prepmt._Amt.';

    public const ADD_PREPMT_AMT = 'Add_Prepmt._Amt.';

    public const VOID_LINE = 'Void_Line';

    public const ADD_PAYMENT = 'Add_Payment';

    public const TRANSFER_ORDERS = 'Transfer_Orders';

    public const SPLIT_BILL = 'Split_Bill';

    public const SWITCH_DINING_TABLE_LAYOUT = 'Switch_Dining_Table_Layout';

    public const ADJUST_DINING_TABLES = 'Adjust_Dining_Tables';

    public const DESIGN_DINING_TABLE_LAYOUT = 'Design_Dining_Table_Layout';

    public const CONTINUEON_T_SERRORS = 'Continue_on_TS_errors';

    public const LAST_Z_REPORT = 'Last_Z-Report';

    public const P_O_S_INTERFACE_PROFILE = 'POS_Interface_Profile';

    public const P_O_S_STYLE_PROFILE = 'POSStyleProfile';

    public const P_O_S_MENU_PROFILE = 'POSMenuProfile';

    public const LANGUAGE = 'Language';

    public const CREATE_CUSTOMERS = 'Create_Customers';

    public const VIEW_SALESHISTORY = 'View_Sales_history';

    public const CUSTOMER_COMMENTS = 'Customer_Comments';

    public const MAX_TENDER_DECL_DIFFERENCE = 'Max._Tender_Decl._Difference';

    public const MAX_WARNING_COUNT = 'Max._Warning_Count';

    public const SHOW_DIFFERENCEIN_WARNING = 'Show_Difference_in_Warning';

    public const ACTION_AFTER_DIFF_WARNING = 'Action_After_Diff._Warning';

    public const C_I_D_REPORT_PRINTING_ALLOWED = 'CID-Report_Printing_Allowed';

    public const SHOW_TRANS_AMOUNT = 'Show_Trans._Amount';

    public const UPDATE_CUSTOMERS = 'Update_Customers';

    public const DISCOUNTFROM_PERM_GROUP = 'Discount_from_Perm._Group';

    public const MAX_DIFF_WARNFROM_PERM_GR = 'Max._Diff.Warn._from_Perm._Gr';

    /**
     * @param string $ID
     * @return $this
     */
    public function setID($ID)
    {
        $this->setData(self::I_D, $ID);
        return $this;
    }

    /**
     * @return string
     */
    public function getID()
    {
        return $this->getData(self::I_D);
    }

    /**
     * @param string $Password
     * @return $this
     */
    public function setPassword($Password)
    {
        $this->setData(self::PASSWORD, $Password);
        return $this;
    }

    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->getData(self::PASSWORD);
    }

    /**
     * @param boolean $ChangePassword
     * @return $this
     */
    public function setChangePassword($ChangePassword)
    {
        $this->setData(self::CHANGE_PASSWORD, $ChangePassword);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getChangePassword()
    {
        return $this->getData(self::CHANGE_PASSWORD);
    }

    /**
     * @param string $StoreNo
     * @return $this
     */
    public function setStoreNo($StoreNo)
    {
        $this->setData(self::STORE_NO, $StoreNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreNo()
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param string $VoidTransaction
     * @return $this
     */
    public function setVoidTransaction($VoidTransaction)
    {
        $this->setData(self::VOID_TRANSACTION, $VoidTransaction);
        return $this;
    }

    /**
     * @return string
     */
    public function getVoidTransaction()
    {
        return $this->getData(self::VOID_TRANSACTION);
    }

    /**
     * @param string $ManagerPrivileges
     * @return $this
     */
    public function setManagerPrivileges($ManagerPrivileges)
    {
        $this->setData(self::MANAGER_PRIVILEGES, $ManagerPrivileges);
        return $this;
    }

    /**
     * @return string
     */
    public function getManagerPrivileges()
    {
        return $this->getData(self::MANAGER_PRIVILEGES);
    }

    /**
     * @param string $XZYReportPrinting
     * @return $this
     */
    public function setXZYReportPrinting($XZYReportPrinting)
    {
        $this->setData(self::X_Z_Y_REPORT_PRINTING, $XZYReportPrinting);
        return $this;
    }

    /**
     * @return string
     */
    public function getXZYReportPrinting()
    {
        return $this->getData(self::X_Z_Y_REPORT_PRINTING);
    }

    /**
     * @param string $TenderDeclaration
     * @return $this
     */
    public function setTenderDeclaration($TenderDeclaration)
    {
        $this->setData(self::TENDER_DECLARATION, $TenderDeclaration);
        return $this;
    }

    /**
     * @return string
     */
    public function getTenderDeclaration()
    {
        return $this->getData(self::TENDER_DECLARATION);
    }

    /**
     * @param string $FloatingDeclaration
     * @return $this
     */
    public function setFloatingDeclaration($FloatingDeclaration)
    {
        $this->setData(self::FLOATING_DECLARATION, $FloatingDeclaration);
        return $this;
    }

    /**
     * @return string
     */
    public function getFloatingDeclaration()
    {
        return $this->getData(self::FLOATING_DECLARATION);
    }

    /**
     * @param string $PriceOverride
     * @return $this
     */
    public function setPriceOverride($PriceOverride)
    {
        $this->setData(self::PRICE_OVERRIDE, $PriceOverride);
        return $this;
    }

    /**
     * @return string
     */
    public function getPriceOverride()
    {
        return $this->getData(self::PRICE_OVERRIDE);
    }

    /**
     * @param float $MaxDiscounttoGive
     * @return $this
     */
    public function setMaxDiscountToGive($MaxDiscounttoGive)
    {
        $this->setData(self::MAX_DISCOUNTTO_GIVE, $MaxDiscounttoGive);
        return $this;
    }

    /**
     * @return float
     */
    public function getMaxDiscountToGive()
    {
        return $this->getData(self::MAX_DISCOUNTTO_GIVE);
    }

    /**
     * @param string $SuspendTransaction
     * @return $this
     */
    public function setSuspendTransaction($SuspendTransaction)
    {
        $this->setData(self::SUSPEND_TRANSACTION, $SuspendTransaction);
        return $this;
    }

    /**
     * @return string
     */
    public function getSuspendTransaction()
    {
        return $this->getData(self::SUSPEND_TRANSACTION);
    }

    /**
     * @param float $MaxTotalDiscount
     * @return $this
     */
    public function setMaxTotalDiscount($MaxTotalDiscount)
    {
        $this->setData(self::MAX_TOTAL_DISCOUNT, $MaxTotalDiscount);
        return $this;
    }

    /**
     * @return float
     */
    public function getMaxTotalDiscount()
    {
        return $this->getData(self::MAX_TOTAL_DISCOUNT);
    }

    /**
     * @param string $OpenDrawwithoutSale
     * @return $this
     */
    public function setOpenDrawWithoutSale($OpenDrawwithoutSale)
    {
        $this->setData(self::OPEN_DRAWWITHOUT_SALE, $OpenDrawwithoutSale);
        return $this;
    }

    /**
     * @return string
     */
    public function getOpenDrawWithoutSale()
    {
        return $this->getData(self::OPEN_DRAWWITHOUT_SALE);
    }

    /**
     * @param string $FirstName
     * @return $this
     */
    public function setFirstName($FirstName)
    {
        $this->setData(self::FIRST_NAME, $FirstName);
        return $this;
    }

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->getData(self::FIRST_NAME);
    }

    /**
     * @param string $LastName
     * @return $this
     */
    public function setLastName($LastName)
    {
        $this->setData(self::LAST_NAME, $LastName);
        return $this;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->getData(self::LAST_NAME);
    }

    /**
     * @param string $EmploymentType
     * @return $this
     */
    public function setEmploymentType($EmploymentType)
    {
        $this->setData(self::EMPLOYMENT_TYPE, $EmploymentType);
        return $this;
    }

    /**
     * @return string
     */
    public function getEmploymentType()
    {
        return $this->getData(self::EMPLOYMENT_TYPE);
    }

    /**
     * @param date $LastDateModified
     * @return $this
     */
    public function setLastDateModified($LastDateModified)
    {
        $this->setData(self::LAST_DATE_MODIFIED, $LastDateModified);
        return $this;
    }

    /**
     * @return date
     */
    public function getLastDateModified()
    {
        return $this->getData(self::LAST_DATE_MODIFIED);
    }

    /**
     * @param string $NameonReceipt
     * @return $this
     */
    public function setNameOnReceipt($NameonReceipt)
    {
        $this->setData(self::NAMEON_RECEIPT, $NameonReceipt);
        return $this;
    }

    /**
     * @return string
     */
    public function getNameOnReceipt()
    {
        return $this->getData(self::NAMEON_RECEIPT);
    }

    /**
     * @param string $Address
     * @return $this
     */
    public function setAddress($Address)
    {
        $this->setData(self::ADDRESS, $Address);
        return $this;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->getData(self::ADDRESS);
    }

    /**
     * @param string $Address2
     * @return $this
     */
    public function setAddress2($Address2)
    {
        $this->setData(self::ADDRESS2, $Address2);
        return $this;
    }

    /**
     * @return string
     */
    public function getAddress2()
    {
        return $this->getData(self::ADDRESS2);
    }

    /**
     * @param string $City
     * @return $this
     */
    public function setCity($City)
    {
        $this->setData(self::CITY, $City);
        return $this;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->getData(self::CITY);
    }

    /**
     * @param string $PostCode
     * @return $this
     */
    public function setPostCode($PostCode)
    {
        $this->setData(self::POST_CODE, $PostCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getPostCode()
    {
        return $this->getData(self::POST_CODE);
    }

    /**
     * @param string $HomePhoneNo
     * @return $this
     */
    public function setHomePhoneNo($HomePhoneNo)
    {
        $this->setData(self::HOME_PHONE_NO, $HomePhoneNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getHomePhoneNo()
    {
        return $this->getData(self::HOME_PHONE_NO);
    }

    /**
     * @param string $WorkPhoneNo
     * @return $this
     */
    public function setWorkPhoneNo($WorkPhoneNo)
    {
        $this->setData(self::WORK_PHONE_NO, $WorkPhoneNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getWorkPhoneNo()
    {
        return $this->getData(self::WORK_PHONE_NO);
    }

    /**
     * @param float $HourlyRate
     * @return $this
     */
    public function setHourlyRate($HourlyRate)
    {
        $this->setData(self::HOURLY_RATE, $HourlyRate);
        return $this;
    }

    /**
     * @return float
     */
    public function getHourlyRate()
    {
        return $this->getData(self::HOURLY_RATE);
    }

    /**
     * @param string $PayrollNo
     * @return $this
     */
    public function setPayrollNo($PayrollNo)
    {
        $this->setData(self::PAYROLL_NO, $PayrollNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getPayrollNo()
    {
        return $this->getData(self::PAYROLL_NO);
    }

    /**
     * @param boolean $Blocked
     * @return $this
     */
    public function setBlocked($Blocked)
    {
        $this->setData(self::BLOCKED, $Blocked);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getBlocked()
    {
        return $this->getData(self::BLOCKED);
    }

    /**
     * @param date $DatetoBeBlocked
     * @return $this
     */
    public function setDateToBeBlocked($DatetoBeBlocked)
    {
        $this->setData(self::DATETO_BE_BLOCKED, $DatetoBeBlocked);
        return $this;
    }

    /**
     * @return date
     */
    public function getDateToBeBlocked()
    {
        return $this->getData(self::DATETO_BE_BLOCKED);
    }

    /**
     * @param boolean $LeftHanded
     * @return $this
     */
    public function setLeftHanded($LeftHanded)
    {
        $this->setData(self::LEFT_HANDED, $LeftHanded);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getLeftHanded()
    {
        return $this->getData(self::LEFT_HANDED);
    }

    /**
     * @param string $SalesPerson
     * @return $this
     */
    public function setSalesPerson($SalesPerson)
    {
        $this->setData(self::SALES_PERSON, $SalesPerson);
        return $this;
    }

    /**
     * @return string
     */
    public function getSalesPerson()
    {
        return $this->getData(self::SALES_PERSON);
    }

    /**
     * @param string $NoSeries
     * @return $this
     */
    public function setNoSeries($NoSeries)
    {
        $this->setData(self::NO_SERIES, $NoSeries);
        return $this;
    }

    /**
     * @return string
     */
    public function getNoSeries()
    {
        return $this->getData(self::NO_SERIES);
    }

    /**
     * @param string $PermissionGroup
     * @return $this
     */
    public function setPermissionGroup($PermissionGroup)
    {
        $this->setData(self::PERMISSION_GROUP, $PermissionGroup);
        return $this;
    }

    /**
     * @return string
     */
    public function getPermissionGroup()
    {
        return $this->getData(self::PERMISSION_GROUP);
    }

    /**
     * @param string $ReturninTransaction
     * @return $this
     */
    public function setReturnInTransaction($ReturninTransaction)
    {
        $this->setData(self::RETURNIN_TRANSACTION, $ReturninTransaction);
        return $this;
    }

    /**
     * @return string
     */
    public function getReturnInTransaction()
    {
        return $this->getData(self::RETURNIN_TRANSACTION);
    }

    /**
     * @param string $VoidPrepayment
     * @return $this
     */
    public function setVoidPrepayment($VoidPrepayment)
    {
        $this->setData(self::VOID_PREPAYMENT, $VoidPrepayment);
        return $this;
    }

    /**
     * @return string
     */
    public function getVoidPrepayment()
    {
        return $this->getData(self::VOID_PREPAYMENT);
    }

    /**
     * @param string $VoidPrepaymentLine
     * @return $this
     */
    public function setVoidPrepaymentLine($VoidPrepaymentLine)
    {
        $this->setData(self::VOID_PREPAYMENT_LINE, $VoidPrepaymentLine);
        return $this;
    }

    /**
     * @return string
     */
    public function getVoidPrepaymentLine()
    {
        return $this->getData(self::VOID_PREPAYMENT_LINE);
    }

    /**
     * @param string $ChangePrepmtAmt
     * @return $this
     */
    public function setChangePrepmtAmt($ChangePrepmtAmt)
    {
        $this->setData(self::CHANGE_PREPMT_AMT, $ChangePrepmtAmt);
        return $this;
    }

    /**
     * @return string
     */
    public function getChangePrepmtAmt()
    {
        return $this->getData(self::CHANGE_PREPMT_AMT);
    }

    /**
     * @param string $AddPrepmtAmt
     * @return $this
     */
    public function setAddPrepmtAmt($AddPrepmtAmt)
    {
        $this->setData(self::ADD_PREPMT_AMT, $AddPrepmtAmt);
        return $this;
    }

    /**
     * @return string
     */
    public function getAddPrepmtAmt()
    {
        return $this->getData(self::ADD_PREPMT_AMT);
    }

    /**
     * @param string $VoidLine
     * @return $this
     */
    public function setVoidLine($VoidLine)
    {
        $this->setData(self::VOID_LINE, $VoidLine);
        return $this;
    }

    /**
     * @return string
     */
    public function getVoidLine()
    {
        return $this->getData(self::VOID_LINE);
    }

    /**
     * @param string $AddPayment
     * @return $this
     */
    public function setAddPayment($AddPayment)
    {
        $this->setData(self::ADD_PAYMENT, $AddPayment);
        return $this;
    }

    /**
     * @return string
     */
    public function getAddPayment()
    {
        return $this->getData(self::ADD_PAYMENT);
    }

    /**
     * @param string $TransferOrders
     * @return $this
     */
    public function setTransferOrders($TransferOrders)
    {
        $this->setData(self::TRANSFER_ORDERS, $TransferOrders);
        return $this;
    }

    /**
     * @return string
     */
    public function getTransferOrders()
    {
        return $this->getData(self::TRANSFER_ORDERS);
    }

    /**
     * @param string $SplitBill
     * @return $this
     */
    public function setSplitBill($SplitBill)
    {
        $this->setData(self::SPLIT_BILL, $SplitBill);
        return $this;
    }

    /**
     * @return string
     */
    public function getSplitBill()
    {
        return $this->getData(self::SPLIT_BILL);
    }

    /**
     * @param string $SwitchDiningTableLayout
     * @return $this
     */
    public function setSwitchDiningTableLayout($SwitchDiningTableLayout)
    {
        $this->setData(self::SWITCH_DINING_TABLE_LAYOUT, $SwitchDiningTableLayout);
        return $this;
    }

    /**
     * @return string
     */
    public function getSwitchDiningTableLayout()
    {
        return $this->getData(self::SWITCH_DINING_TABLE_LAYOUT);
    }

    /**
     * @param string $AdjustDiningTables
     * @return $this
     */
    public function setAdjustDiningTables($AdjustDiningTables)
    {
        $this->setData(self::ADJUST_DINING_TABLES, $AdjustDiningTables);
        return $this;
    }

    /**
     * @return string
     */
    public function getAdjustDiningTables()
    {
        return $this->getData(self::ADJUST_DINING_TABLES);
    }

    /**
     * @param string $DesignDiningTableLayout
     * @return $this
     */
    public function setDesignDiningTableLayout($DesignDiningTableLayout)
    {
        $this->setData(self::DESIGN_DINING_TABLE_LAYOUT, $DesignDiningTableLayout);
        return $this;
    }

    /**
     * @return string
     */
    public function getDesignDiningTableLayout()
    {
        return $this->getData(self::DESIGN_DINING_TABLE_LAYOUT);
    }

    /**
     * @param boolean $ContinueonTSerrors
     * @return $this
     */
    public function setContinueOnTSErrors($ContinueonTSerrors)
    {
        $this->setData(self::CONTINUEON_T_SERRORS, $ContinueonTSerrors);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getContinueOnTSErrors()
    {
        return $this->getData(self::CONTINUEON_T_SERRORS);
    }

    /**
     * @param string $LastZReport
     * @return $this
     */
    public function setLastZReport($LastZReport)
    {
        $this->setData(self::LAST_Z_REPORT, $LastZReport);
        return $this;
    }

    /**
     * @return string
     */
    public function getLastZReport()
    {
        return $this->getData(self::LAST_Z_REPORT);
    }

    /**
     * @param string $POSInterfaceProfile
     * @return $this
     */
    public function setPOSInterfaceProfile($POSInterfaceProfile)
    {
        $this->setData(self::P_O_S_INTERFACE_PROFILE, $POSInterfaceProfile);
        return $this;
    }

    /**
     * @return string
     */
    public function getPOSInterfaceProfile()
    {
        return $this->getData(self::P_O_S_INTERFACE_PROFILE);
    }

    /**
     * @param string $POSStyleProfile
     * @return $this
     */
    public function setPOSStyleProfile($POSStyleProfile)
    {
        $this->setData(self::P_O_S_STYLE_PROFILE, $POSStyleProfile);
        return $this;
    }

    /**
     * @return string
     */
    public function getPOSStyleProfile()
    {
        return $this->getData(self::P_O_S_STYLE_PROFILE);
    }

    /**
     * @param string $POSMenuProfile
     * @return $this
     */
    public function setPOSMenuProfile($POSMenuProfile)
    {
        $this->setData(self::P_O_S_MENU_PROFILE, $POSMenuProfile);
        return $this;
    }

    /**
     * @return string
     */
    public function getPOSMenuProfile()
    {
        return $this->getData(self::P_O_S_MENU_PROFILE);
    }

    /**
     * @param string $Language
     * @return $this
     */
    public function setLanguage($Language)
    {
        $this->setData(self::LANGUAGE, $Language);
        return $this;
    }

    /**
     * @return string
     */
    public function getLanguage()
    {
        return $this->getData(self::LANGUAGE);
    }

    /**
     * @param string $CreateCustomers
     * @return $this
     */
    public function setCreateCustomers($CreateCustomers)
    {
        $this->setData(self::CREATE_CUSTOMERS, $CreateCustomers);
        return $this;
    }

    /**
     * @return string
     */
    public function getCreateCustomers()
    {
        return $this->getData(self::CREATE_CUSTOMERS);
    }

    /**
     * @param string $ViewSaleshistory
     * @return $this
     */
    public function setViewSalesHistory($ViewSaleshistory)
    {
        $this->setData(self::VIEW_SALESHISTORY, $ViewSaleshistory);
        return $this;
    }

    /**
     * @return string
     */
    public function getViewSalesHistory()
    {
        return $this->getData(self::VIEW_SALESHISTORY);
    }

    /**
     * @param string $CustomerComments
     * @return $this
     */
    public function setCustomerComments($CustomerComments)
    {
        $this->setData(self::CUSTOMER_COMMENTS, $CustomerComments);
        return $this;
    }

    /**
     * @return string
     */
    public function getCustomerComments()
    {
        return $this->getData(self::CUSTOMER_COMMENTS);
    }

    /**
     * @param float $MaxTenderDeclDifference
     * @return $this
     */
    public function setMaxTenderDeclDifference($MaxTenderDeclDifference)
    {
        $this->setData(self::MAX_TENDER_DECL_DIFFERENCE, $MaxTenderDeclDifference);
        return $this;
    }

    /**
     * @return float
     */
    public function getMaxTenderDeclDifference()
    {
        return $this->getData(self::MAX_TENDER_DECL_DIFFERENCE);
    }

    /**
     * @param int $MaxWarningCount
     * @return $this
     */
    public function setMaxWarningCount($MaxWarningCount)
    {
        $this->setData(self::MAX_WARNING_COUNT, $MaxWarningCount);
        return $this;
    }

    /**
     * @return int
     */
    public function getMaxWarningCount()
    {
        return $this->getData(self::MAX_WARNING_COUNT);
    }

    /**
     * @param string $ShowDifferenceinWarning
     * @return $this
     */
    public function setShowDifferenceInWarning($ShowDifferenceinWarning)
    {
        $this->setData(self::SHOW_DIFFERENCEIN_WARNING, $ShowDifferenceinWarning);
        return $this;
    }

    /**
     * @return string
     */
    public function getShowDifferenceInWarning()
    {
        return $this->getData(self::SHOW_DIFFERENCEIN_WARNING);
    }

    /**
     * @param string $ActionAfterDiffWarning
     * @return $this
     */
    public function setActionAfterDiffWarning($ActionAfterDiffWarning)
    {
        $this->setData(self::ACTION_AFTER_DIFF_WARNING, $ActionAfterDiffWarning);
        return $this;
    }

    /**
     * @return string
     */
    public function getActionAfterDiffWarning()
    {
        return $this->getData(self::ACTION_AFTER_DIFF_WARNING);
    }

    /**
     * @param string $CIDReportPrintingAllowed
     * @return $this
     */
    public function setCIDReportPrintingAllowed($CIDReportPrintingAllowed)
    {
        $this->setData(self::C_I_D_REPORT_PRINTING_ALLOWED, $CIDReportPrintingAllowed);
        return $this;
    }

    /**
     * @return string
     */
    public function getCIDReportPrintingAllowed()
    {
        return $this->getData(self::C_I_D_REPORT_PRINTING_ALLOWED);
    }

    /**
     * @param string $ShowTransAmount
     * @return $this
     */
    public function setShowTransAmount($ShowTransAmount)
    {
        $this->setData(self::SHOW_TRANS_AMOUNT, $ShowTransAmount);
        return $this;
    }

    /**
     * @return string
     */
    public function getShowTransAmount()
    {
        return $this->getData(self::SHOW_TRANS_AMOUNT);
    }

    /**
     * @param string $UpdateCustomers
     * @return $this
     */
    public function setUpdateCustomers($UpdateCustomers)
    {
        $this->setData(self::UPDATE_CUSTOMERS, $UpdateCustomers);
        return $this;
    }

    /**
     * @return string
     */
    public function getUpdateCustomers()
    {
        return $this->getData(self::UPDATE_CUSTOMERS);
    }

    /**
     * @param string $DiscountfromPermGroup
     * @return $this
     */
    public function setDiscountFromPermGroup($DiscountfromPermGroup)
    {
        $this->setData(self::DISCOUNTFROM_PERM_GROUP, $DiscountfromPermGroup);
        return $this;
    }

    /**
     * @return string
     */
    public function getDiscountFromPermGroup()
    {
        return $this->getData(self::DISCOUNTFROM_PERM_GROUP);
    }

    /**
     * @param string $MaxDiffWarnfromPermGr
     * @return $this
     */
    public function setMaxDiffWarnFromPermGr($MaxDiffWarnfromPermGr)
    {
        $this->setData(self::MAX_DIFF_WARNFROM_PERM_GR, $MaxDiffWarnfromPermGr);
        return $this;
    }

    /**
     * @return string
     */
    public function getMaxDiffWarnFromPermGr()
    {
        return $this->getData(self::MAX_DIFF_WARNFROM_PERM_GR);
    }
}

