<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class StaffStoreLink extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'StaffStoreLink';

    public const STAFF_I_D = 'StaffID';

    public const STAFF_FIRST_NAME = 'StaffFirstName';

    public const STAFF_LAST_NAME = 'StaffLastName';

    public const STAFF_NAME_ON_RECEIPT = 'StaffNameOnReceipt';

    public const STORE_NO = 'StoreNo';

    public const STORE_NAME = 'StoreName';

    public const PERMISSION_GROUP = 'PermissionGroup';

    public const P_O_S_INTERFACE_PROFILE = 'POSInterfaceProfile';

    public const P_O_S_STYLE_PROFILE = 'POSStyleProfile';

    public const P_O_S_MENU_PROFILE = 'POSMenuProfile';

    public const DELIVERY_DRIVER = 'DeliveryDriver';

    public const FLOAT = 'Float';

    public const CURRENT_TRIP_NO = 'CurrentTripNo';

    public const ON_CALL = 'OnCall';

    public const OPEN_TRIP_COUNTER = 'OpenTripCounter';

    public const DEFAULT_SALES_TYPE = 'DefaultSalesType';

    public const DEFAULT_SEQUENCE = 'DefaultSequence';

    public const DEFAULT_STORE = 'DefaultStore';

    /**
     * @param string $StaffID
     * @return $this
     */
    public function setStaffID($StaffID)
    {
        $this->setData(self::STAFF_I_D, $StaffID);
        return $this;
    }

    /**
     * @return string
     */
    public function getStaffID()
    {
        return $this->getData(self::STAFF_I_D);
    }

    /**
     * @param string $StaffFirstName
     * @return $this
     */
    public function setStaffFirstName($StaffFirstName)
    {
        $this->setData(self::STAFF_FIRST_NAME, $StaffFirstName);
        return $this;
    }

    /**
     * @return string
     */
    public function getStaffFirstName()
    {
        return $this->getData(self::STAFF_FIRST_NAME);
    }

    /**
     * @param string $StaffLastName
     * @return $this
     */
    public function setStaffLastName($StaffLastName)
    {
        $this->setData(self::STAFF_LAST_NAME, $StaffLastName);
        return $this;
    }

    /**
     * @return string
     */
    public function getStaffLastName()
    {
        return $this->getData(self::STAFF_LAST_NAME);
    }

    /**
     * @param string $StaffNameOnReceipt
     * @return $this
     */
    public function setStaffNameOnReceipt($StaffNameOnReceipt)
    {
        $this->setData(self::STAFF_NAME_ON_RECEIPT, $StaffNameOnReceipt);
        return $this;
    }

    /**
     * @return string
     */
    public function getStaffNameOnReceipt()
    {
        return $this->getData(self::STAFF_NAME_ON_RECEIPT);
    }

    /**
     * @param string $StoreNo
     * @return $this
     */
    public function setStoreNo($StoreNo)
    {
        $this->setData(self::STORE_NO, $StoreNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreNo()
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param string $StoreName
     * @return $this
     */
    public function setStoreName($StoreName)
    {
        $this->setData(self::STORE_NAME, $StoreName);
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreName()
    {
        return $this->getData(self::STORE_NAME);
    }

    /**
     * @param string $PermissionGroup
     * @return $this
     */
    public function setPermissionGroup($PermissionGroup)
    {
        $this->setData(self::PERMISSION_GROUP, $PermissionGroup);
        return $this;
    }

    /**
     * @return string
     */
    public function getPermissionGroup()
    {
        return $this->getData(self::PERMISSION_GROUP);
    }

    /**
     * @param string $POSInterfaceProfile
     * @return $this
     */
    public function setPOSInterfaceProfile($POSInterfaceProfile)
    {
        $this->setData(self::P_O_S_INTERFACE_PROFILE, $POSInterfaceProfile);
        return $this;
    }

    /**
     * @return string
     */
    public function getPOSInterfaceProfile()
    {
        return $this->getData(self::P_O_S_INTERFACE_PROFILE);
    }

    /**
     * @param string $POSStyleProfile
     * @return $this
     */
    public function setPOSStyleProfile($POSStyleProfile)
    {
        $this->setData(self::P_O_S_STYLE_PROFILE, $POSStyleProfile);
        return $this;
    }

    /**
     * @return string
     */
    public function getPOSStyleProfile()
    {
        return $this->getData(self::P_O_S_STYLE_PROFILE);
    }

    /**
     * @param string $POSMenuProfile
     * @return $this
     */
    public function setPOSMenuProfile($POSMenuProfile)
    {
        $this->setData(self::P_O_S_MENU_PROFILE, $POSMenuProfile);
        return $this;
    }

    /**
     * @return string
     */
    public function getPOSMenuProfile()
    {
        return $this->getData(self::P_O_S_MENU_PROFILE);
    }

    /**
     * @param boolean $DeliveryDriver
     * @return $this
     */
    public function setDeliveryDriver($DeliveryDriver)
    {
        $this->setData(self::DELIVERY_DRIVER, $DeliveryDriver);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getDeliveryDriver()
    {
        return $this->getData(self::DELIVERY_DRIVER);
    }

    /**
     * @param float $Float
     * @return $this
     */
    public function setFloat($Float)
    {
        $this->setData(self::FLOAT, $Float);
        return $this;
    }

    /**
     * @return float
     */
    public function getFloat()
    {
        return $this->getData(self::FLOAT);
    }

    /**
     * @param int $CurrentTripNo
     * @return $this
     */
    public function setCurrentTripNo($CurrentTripNo)
    {
        $this->setData(self::CURRENT_TRIP_NO, $CurrentTripNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getCurrentTripNo()
    {
        return $this->getData(self::CURRENT_TRIP_NO);
    }

    /**
     * @param boolean $OnCall
     * @return $this
     */
    public function setOnCall($OnCall)
    {
        $this->setData(self::ON_CALL, $OnCall);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getOnCall()
    {
        return $this->getData(self::ON_CALL);
    }

    /**
     * @param int $OpenTripCounter
     * @return $this
     */
    public function setOpenTripCounter($OpenTripCounter)
    {
        $this->setData(self::OPEN_TRIP_COUNTER, $OpenTripCounter);
        return $this;
    }

    /**
     * @return int
     */
    public function getOpenTripCounter()
    {
        return $this->getData(self::OPEN_TRIP_COUNTER);
    }

    /**
     * @param string $DefaultSalesType
     * @return $this
     */
    public function setDefaultSalesType($DefaultSalesType)
    {
        $this->setData(self::DEFAULT_SALES_TYPE, $DefaultSalesType);
        return $this;
    }

    /**
     * @return string
     */
    public function getDefaultSalesType()
    {
        return $this->getData(self::DEFAULT_SALES_TYPE);
    }

    /**
     * @param int $DefaultSequence
     * @return $this
     */
    public function setDefaultSequence($DefaultSequence)
    {
        $this->setData(self::DEFAULT_SEQUENCE, $DefaultSequence);
        return $this;
    }

    /**
     * @return int
     */
    public function getDefaultSequence()
    {
        return $this->getData(self::DEFAULT_SEQUENCE);
    }

    /**
     * @param boolean $DefaultStore
     * @return $this
     */
    public function setDefaultStore($DefaultStore)
    {
        $this->setData(self::DEFAULT_STORE, $DefaultStore);
        return $this;
    }

    /**
     * @return boolean
     */
    public function getDefaultStore()
    {
        return $this->getData(self::DEFAULT_STORE);
    }
}

