<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\ResponseInterface;

class TokenEntryGetResponse implements ResponseInterface
{

    /**
     * @property ClientTokenResult $TokenEntryGetResult
     */
    protected $TokenEntryGetResult = null;

    /**
     * @param ClientTokenResult $TokenEntryGetResult
     * @return $this
     */
    public function setTokenEntryGetResult($TokenEntryGetResult)
    {
        $this->TokenEntryGetResult = $TokenEntryGetResult;
        return $this;
    }

    /**
     * @return ClientTokenResult
     */
    public function getTokenEntryGetResult()
    {
        return $this->TokenEntryGetResult;
    }

    /**
     * @return ClientTokenResult
     */
    public function getResult()
    {
        return $this->TokenEntryGetResult;
    }


}

