<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class TransMixMatchEntry extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'TransMixMatchEntry';

    public const TRANSACTION_NO = 'TransactionNo';

    public const LINE_NO = 'LineNo';

    public const MIX_MATCH_GROUP = 'MixMatchGroup';

    public const STORE_NO = 'StoreNo';

    public const DATE = 'Date';

    public const TIME = 'Time';

    public const DISCOUNT_AMOUNT = 'DiscountAmount';

    public const QUANTITY = 'Quantity';

    public const P_O_S_TERMINAL_NO = 'POSTerminalNo';

    public const COUNTER = 'Counter';

    public const REPLICATED = 'Replicated';

    public const REPLICATION_COUNTER = 'ReplicationCounter';

    /**
     * @param int $TransactionNo
     * @return $this
     */
    public function setTransactionNo($TransactionNo)
    {
        $this->setData(self::TRANSACTION_NO, $TransactionNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getTransactionNo()
    {
        return $this->getData(self::TRANSACTION_NO);
    }

    /**
     * @param int $LineNo
     * @return $this
     */
    public function setLineNo($LineNo)
    {
        $this->setData(self::LINE_NO, $LineNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getLineNo()
    {
        return $this->getData(self::LINE_NO);
    }

    /**
     * @param ?string $MixMatchGroup
     * @return $this
     */
    public function setMixMatchGroup(?string $MixMatchGroup)
    {
        $this->setData(self::MIX_MATCH_GROUP, $MixMatchGroup);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getMixMatchGroup() : ?string
    {
        return $this->getData(self::MIX_MATCH_GROUP);
    }

    /**
     * @param ?string $StoreNo
     * @return $this
     */
    public function setStoreNo(?string $StoreNo)
    {
        $this->setData(self::STORE_NO, $StoreNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStoreNo() : ?string
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param ?string $Date
     * @return $this
     */
    public function setDate(?string $Date)
    {
        $this->setData(self::DATE, $Date);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getDate() : ?string
    {
        return $this->getData(self::DATE);
    }

    /**
     * @param time $Time
     * @return $this
     */
    public function setTime($Time)
    {
        $this->setData(self::TIME, $Time);
        return $this;
    }

    /**
     * @return time
     */
    public function getTime()
    {
        return $this->getData(self::TIME);
    }

    /**
     * @param ?float $DiscountAmount
     * @return $this
     */
    public function setDiscountAmount(?float $DiscountAmount)
    {
        $this->setData(self::DISCOUNT_AMOUNT, $DiscountAmount);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getDiscountAmount() : ?float
    {
        return $this->getData(self::DISCOUNT_AMOUNT);
    }

    /**
     * @param ?float $Quantity
     * @return $this
     */
    public function setQuantity(?float $Quantity)
    {
        $this->setData(self::QUANTITY, $Quantity);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getQuantity() : ?float
    {
        return $this->getData(self::QUANTITY);
    }

    /**
     * @param ?string $POSTerminalNo
     * @return $this
     */
    public function setPOSTerminalNo(?string $POSTerminalNo)
    {
        $this->setData(self::P_O_S_TERMINAL_NO, $POSTerminalNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getPOSTerminalNo() : ?string
    {
        return $this->getData(self::P_O_S_TERMINAL_NO);
    }

    /**
     * @param int $Counter
     * @return $this
     */
    public function setCounter($Counter)
    {
        $this->setData(self::COUNTER, $Counter);
        return $this;
    }

    /**
     * @return int
     */
    public function getCounter()
    {
        return $this->getData(self::COUNTER);
    }

    /**
     * @param ?bool $Replicated
     * @return $this
     */
    public function setReplicated(?bool $Replicated)
    {
        $this->setData(self::REPLICATED, $Replicated);
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getReplicated() : ?bool
    {
        return $this->getData(self::REPLICATED);
    }

    /**
     * @param int $ReplicationCounter
     * @return $this
     */
    public function setReplicationCounter($ReplicationCounter)
    {
        $this->setData(self::REPLICATION_COUNTER, $ReplicationCounter);
        return $this;
    }

    /**
     * @return int
     */
    public function getReplicationCounter()
    {
        return $this->getData(self::REPLICATION_COUNTER);
    }
}

