<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class TransPaymentEntry extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'TransPaymentEntry';

    public const TRANSACTION_NO = 'TransactionNo';

    public const LINE_NO = 'LineNo';

    public const RECEIPT_NO = 'ReceiptNo';

    public const STATEMENT_CODE = 'StatementCode';

    public const CARD_NO = 'CardNo';

    public const EXCHANGE_RATE = 'ExchangeRate';

    public const TENDER_TYPE = 'TenderType';

    public const AMOUNT_TENDERED = 'AmountTendered';

    public const CURRENCY_CODE = 'CurrencyCode';

    public const AMOUNTIN_CURRENCY = 'AmountinCurrency';

    public const CARDOR_ACCOUNT = 'CardorAccount';

    public const DATE = 'Date';

    public const TIME = 'Time';

    public const SHIFT_NO = 'ShiftNo';

    public const SHIFT_DATE = 'ShiftDate';

    public const STAFF_I_D = 'StaffID';

    public const STORE_NO = 'StoreNo';

    public const P_O_S_TERMINAL_NO = 'POSTerminalNo';

    public const TRANSACTION_STATUS = 'TransactionStatus';

    public const STATEMENT_NO = 'StatementNo';

    public const MANAGERS_KEY_LIVE = 'ManagersKeyLive';

    public const CHANGE_LINE = 'ChangeLine';

    public const COUNTER = 'Counter';

    public const TRANS_DATE = 'TransDate';

    public const TRANS_TIME = 'TransTime';

    public const MESSAGE_NO = 'MessageNo';

    public const REPLICATED = 'Replicated';

    public const QUANTITY = 'Quantity';

    public const Z_REPORT_I_D = 'Z-ReportID';

    public const TENDER_DECL_I_D = 'TenderDeclID';

    public const Y_REPORT_I_D = 'Y-ReportID';

    public const REPLICATION_COUNTER = 'ReplicationCounter';

    public const SAFETYPE = 'Safetype';

    public const CREATEDBY_STAFF_I_D = 'CreatedbyStaffID';

    public const ORDER_NO = 'OrderNo';

    /**
     * @param int $TransactionNo
     * @return $this
     */
    public function setTransactionNo($TransactionNo)
    {
        $this->setData(self::TRANSACTION_NO, $TransactionNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getTransactionNo()
    {
        return $this->getData(self::TRANSACTION_NO);
    }

    /**
     * @param int $LineNo
     * @return $this
     */
    public function setLineNo($LineNo)
    {
        $this->setData(self::LINE_NO, $LineNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getLineNo()
    {
        return $this->getData(self::LINE_NO);
    }

    /**
     * @param ?string $ReceiptNo
     * @return $this
     */
    public function setReceiptNo(?string $ReceiptNo)
    {
        $this->setData(self::RECEIPT_NO, $ReceiptNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getReceiptNo() : ?string
    {
        return $this->getData(self::RECEIPT_NO);
    }

    /**
     * @param ?string $StatementCode
     * @return $this
     */
    public function setStatementCode(?string $StatementCode)
    {
        $this->setData(self::STATEMENT_CODE, $StatementCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStatementCode() : ?string
    {
        return $this->getData(self::STATEMENT_CODE);
    }

    /**
     * @param ?string $CardNo
     * @return $this
     */
    public function setCardNo(?string $CardNo)
    {
        $this->setData(self::CARD_NO, $CardNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getCardNo() : ?string
    {
        return $this->getData(self::CARD_NO);
    }

    /**
     * @param ?float $ExchangeRate
     * @return $this
     */
    public function setExchangeRate(?float $ExchangeRate)
    {
        $this->setData(self::EXCHANGE_RATE, $ExchangeRate);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getExchangeRate() : ?float
    {
        return $this->getData(self::EXCHANGE_RATE);
    }

    /**
     * @param ?string $TenderType
     * @return $this
     */
    public function setTenderType(?string $TenderType)
    {
        $this->setData(self::TENDER_TYPE, $TenderType);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getTenderType() : ?string
    {
        return $this->getData(self::TENDER_TYPE);
    }

    /**
     * @param ?float $AmountTendered
     * @return $this
     */
    public function setAmountTendered(?float $AmountTendered)
    {
        $this->setData(self::AMOUNT_TENDERED, $AmountTendered);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getAmountTendered() : ?float
    {
        return $this->getData(self::AMOUNT_TENDERED);
    }

    /**
     * @param ?string $CurrencyCode
     * @return $this
     */
    public function setCurrencyCode(?string $CurrencyCode)
    {
        $this->setData(self::CURRENCY_CODE, $CurrencyCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getCurrencyCode() : ?string
    {
        return $this->getData(self::CURRENCY_CODE);
    }

    /**
     * @param ?float $AmountinCurrency
     * @return $this
     */
    public function setAmountinCurrency(?float $AmountinCurrency)
    {
        $this->setData(self::AMOUNTIN_CURRENCY, $AmountinCurrency);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getAmountinCurrency() : ?float
    {
        return $this->getData(self::AMOUNTIN_CURRENCY);
    }

    /**
     * @param ?string $CardorAccount
     * @return $this
     */
    public function setCardorAccount(?string $CardorAccount)
    {
        $this->setData(self::CARDOR_ACCOUNT, $CardorAccount);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getCardorAccount() : ?string
    {
        return $this->getData(self::CARDOR_ACCOUNT);
    }

    /**
     * @param ?string $Date
     * @return $this
     */
    public function setDate(?string $Date)
    {
        $this->setData(self::DATE, $Date);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getDate() : ?string
    {
        return $this->getData(self::DATE);
    }

    /**
     * @param time $Time
     * @return $this
     */
    public function setTime($Time)
    {
        $this->setData(self::TIME, $Time);
        return $this;
    }

    /**
     * @return time
     */
    public function getTime()
    {
        return $this->getData(self::TIME);
    }

    /**
     * @param ?string $ShiftNo
     * @return $this
     */
    public function setShiftNo(?string $ShiftNo)
    {
        $this->setData(self::SHIFT_NO, $ShiftNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getShiftNo() : ?string
    {
        return $this->getData(self::SHIFT_NO);
    }

    /**
     * @param ?string $ShiftDate
     * @return $this
     */
    public function setShiftDate(?string $ShiftDate)
    {
        $this->setData(self::SHIFT_DATE, $ShiftDate);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getShiftDate() : ?string
    {
        return $this->getData(self::SHIFT_DATE);
    }

    /**
     * @param ?string $StaffID
     * @return $this
     */
    public function setStaffID(?string $StaffID)
    {
        $this->setData(self::STAFF_I_D, $StaffID);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStaffID() : ?string
    {
        return $this->getData(self::STAFF_I_D);
    }

    /**
     * @param ?string $StoreNo
     * @return $this
     */
    public function setStoreNo(?string $StoreNo)
    {
        $this->setData(self::STORE_NO, $StoreNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStoreNo() : ?string
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param ?string $POSTerminalNo
     * @return $this
     */
    public function setPOSTerminalNo(?string $POSTerminalNo)
    {
        $this->setData(self::P_O_S_TERMINAL_NO, $POSTerminalNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getPOSTerminalNo() : ?string
    {
        return $this->getData(self::P_O_S_TERMINAL_NO);
    }

    /**
     * @param ?string $TransactionStatus
     * @return $this
     */
    public function setTransactionStatus(?string $TransactionStatus)
    {
        $this->setData(self::TRANSACTION_STATUS, $TransactionStatus);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getTransactionStatus() : ?string
    {
        return $this->getData(self::TRANSACTION_STATUS);
    }

    /**
     * @param ?string $StatementNo
     * @return $this
     */
    public function setStatementNo(?string $StatementNo)
    {
        $this->setData(self::STATEMENT_NO, $StatementNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStatementNo() : ?string
    {
        return $this->getData(self::STATEMENT_NO);
    }

    /**
     * @param ?bool $ManagersKeyLive
     * @return $this
     */
    public function setManagersKeyLive(?bool $ManagersKeyLive)
    {
        $this->setData(self::MANAGERS_KEY_LIVE, $ManagersKeyLive);
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getManagersKeyLive() : ?bool
    {
        return $this->getData(self::MANAGERS_KEY_LIVE);
    }

    /**
     * @param ?bool $ChangeLine
     * @return $this
     */
    public function setChangeLine(?bool $ChangeLine)
    {
        $this->setData(self::CHANGE_LINE, $ChangeLine);
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getChangeLine() : ?bool
    {
        return $this->getData(self::CHANGE_LINE);
    }

    /**
     * @param ?float $Counter
     * @return $this
     */
    public function setCounter(?float $Counter)
    {
        $this->setData(self::COUNTER, $Counter);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getCounter() : ?float
    {
        return $this->getData(self::COUNTER);
    }

    /**
     * @param ?string $TransDate
     * @return $this
     */
    public function setTransDate(?string $TransDate)
    {
        $this->setData(self::TRANS_DATE, $TransDate);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getTransDate() : ?string
    {
        return $this->getData(self::TRANS_DATE);
    }

    /**
     * @param time $TransTime
     * @return $this
     */
    public function setTransTime($TransTime)
    {
        $this->setData(self::TRANS_TIME, $TransTime);
        return $this;
    }

    /**
     * @return time
     */
    public function getTransTime()
    {
        return $this->getData(self::TRANS_TIME);
    }

    /**
     * @param int $MessageNo
     * @return $this
     */
    public function setMessageNo($MessageNo)
    {
        $this->setData(self::MESSAGE_NO, $MessageNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getMessageNo()
    {
        return $this->getData(self::MESSAGE_NO);
    }

    /**
     * @param ?bool $Replicated
     * @return $this
     */
    public function setReplicated(?bool $Replicated)
    {
        $this->setData(self::REPLICATED, $Replicated);
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getReplicated() : ?bool
    {
        return $this->getData(self::REPLICATED);
    }

    /**
     * @param ?float $Quantity
     * @return $this
     */
    public function setQuantity(?float $Quantity)
    {
        $this->setData(self::QUANTITY, $Quantity);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getQuantity() : ?float
    {
        return $this->getData(self::QUANTITY);
    }

    /**
     * @param ?string $ZReportID
     * @return $this
     */
    public function setZReportID(?string $ZReportID)
    {
        $this->setData(self::Z_REPORT_I_D, $ZReportID);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getZReportID() : ?string
    {
        return $this->getData(self::Z_REPORT_I_D);
    }

    /**
     * @param ?string $TenderDeclID
     * @return $this
     */
    public function setTenderDeclID(?string $TenderDeclID)
    {
        $this->setData(self::TENDER_DECL_I_D, $TenderDeclID);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getTenderDeclID() : ?string
    {
        return $this->getData(self::TENDER_DECL_I_D);
    }

    /**
     * @param ?string $YReportID
     * @return $this
     */
    public function setYReportID(?string $YReportID)
    {
        $this->setData(self::Y_REPORT_I_D, $YReportID);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getYReportID() : ?string
    {
        return $this->getData(self::Y_REPORT_I_D);
    }

    /**
     * @param int $ReplicationCounter
     * @return $this
     */
    public function setReplicationCounter($ReplicationCounter)
    {
        $this->setData(self::REPLICATION_COUNTER, $ReplicationCounter);
        return $this;
    }

    /**
     * @return int
     */
    public function getReplicationCounter()
    {
        return $this->getData(self::REPLICATION_COUNTER);
    }

    /**
     * @param ?string $Safetype
     * @return $this
     */
    public function setSafetype(?string $Safetype)
    {
        $this->setData(self::SAFETYPE, $Safetype);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getSafetype() : ?string
    {
        return $this->getData(self::SAFETYPE);
    }

    /**
     * @param ?string $CreatedbyStaffID
     * @return $this
     */
    public function setCreatedbyStaffID(?string $CreatedbyStaffID)
    {
        $this->setData(self::CREATEDBY_STAFF_I_D, $CreatedbyStaffID);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getCreatedbyStaffID() : ?string
    {
        return $this->getData(self::CREATEDBY_STAFF_I_D);
    }

    /**
     * @param ?string $OrderNo
     * @return $this
     */
    public function setOrderNo(?string $OrderNo)
    {
        $this->setData(self::ORDER_NO, $OrderNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getOrderNo() : ?string
    {
        return $this->getData(self::ORDER_NO);
    }
}

