<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class VariantExt
{

    /**
     * @property ArrayOfDimValue $Values
     */
    protected $Values = null;

    /**
     * @property string $Code
     */
    protected $Code = null;

    /**
     * @property string $Dimension
     */
    protected $Dimension = null;

    /**
     * @param ArrayOfDimValue $Values
     * @return $this
     */
    public function setValues($Values)
    {
        $this->Values = $Values;
        return $this;
    }

    /**
     * @return ArrayOfDimValue
     */
    public function getValues()
    {
        return $this->Values;
    }

    /**
     * @param string $Code
     * @return $this
     */
    public function setCode($Code)
    {
        $this->Code = $Code;
        return $this;
    }

    /**
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * @param string $Dimension
     * @return $this
     */
    public function setDimension($Dimension)
    {
        $this->Dimension = $Dimension;
        return $this;
    }

    /**
     * @return string
     */
    public function getDimension()
    {
        return $this->Dimension;
    }


}

