<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

class WSInventoryBuffer extends \Magento\Framework\DataObject
{
    public const CLASS_NAME = 'WSInventoryBuffer';

    public const ITEM_NO = 'ItemNo';

    public const VARIANT_CODE = 'VariantCode';

    public const LOCATION_CODE = 'LocationCode';

    public const ACTUAL_INVENTORY = 'ActualInventory';

    public const LEAD_TIME_DAYS = 'LeadTimeDays';

    public const BASE_UNIT_OF_MEASURE = 'BaseUnitOfMeasure';

    public const STORE_NO = 'StoreNo';

    public const INVENTORY = 'Inventory';

    public const QTY_SOLDNOT_POSTED = 'QtySoldnotPosted';

    public const COLOUR = 'Colour';

    public const SIZE = 'Size';

    public const STYLE = 'Style';

    public const BASE_UNITOF_MEASURE = 'BaseUnitofMeasure';

    public const EXPECTED_STOCK = 'ExpectedStock';

    public const REORDER_POINT = 'ReorderPoint';

    /**
     * @param string $ItemNo
     * @return $this
     */
    public function setItemNo($ItemNo)
    {
        $this->setData(self::ITEM_NO, $ItemNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getItemNo()
    {
        return $this->getData(self::ITEM_NO);
    }

    /**
     * @param string $VariantCode
     * @return $this
     */
    public function setVariantCode($VariantCode)
    {
        $this->setData(self::VARIANT_CODE, $VariantCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getVariantCode()
    {
        return $this->getData(self::VARIANT_CODE);
    }

    /**
     * @param string $LocationCode
     * @return $this
     */
    public function setLocationCode($LocationCode)
    {
        $this->setData(self::LOCATION_CODE, $LocationCode);
        return $this;
    }

    /**
     * @return string
     */
    public function getLocationCode()
    {
        return $this->getData(self::LOCATION_CODE);
    }

    /**
     * @param float $ActualInventory
     * @return $this
     */
    public function setActualInventory($ActualInventory)
    {
        $this->setData(self::ACTUAL_INVENTORY, $ActualInventory);
        return $this;
    }

    /**
     * @return float
     */
    public function getActualInventory()
    {
        return $this->getData(self::ACTUAL_INVENTORY);
    }

    /**
     * @param int $LeadTimeDays
     * @return $this
     */
    public function setLeadTimeDays($LeadTimeDays)
    {
        $this->setData(self::LEAD_TIME_DAYS, $LeadTimeDays);
        return $this;
    }

    /**
     * @return int
     */
    public function getLeadTimeDays()
    {
        return $this->getData(self::LEAD_TIME_DAYS);
    }

    /**
     * @param string $BaseUnitOfMeasure
     * @return $this
     */
    public function setBaseUnitOfMeasure($BaseUnitOfMeasure)
    {
        $this->setData(self::BASE_UNIT_OF_MEASURE, $BaseUnitOfMeasure);
        return $this;
    }

    /**
     * @return string
     */
    public function getBaseUnitOfMeasure()
    {
        return $this->getData(self::BASE_UNIT_OF_MEASURE);
    }

    /**
     * @param string $StoreNo
     * @return $this
     */
    public function setStoreNo($StoreNo)
    {
        $this->setData(self::STORE_NO, $StoreNo);
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreNo()
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param float $Inventory
     * @return $this
     */
    public function setInventory($Inventory)
    {
        $this->setData(self::INVENTORY, $Inventory);
        return $this;
    }

    /**
     * @return float
     */
    public function getInventory()
    {
        return $this->getData(self::INVENTORY);
    }

    /**
     * @param float $QtySoldnotPosted
     * @return $this
     */
    public function setQtySoldnotPosted($QtySoldnotPosted)
    {
        $this->setData(self::QTY_SOLDNOT_POSTED, $QtySoldnotPosted);
        return $this;
    }

    /**
     * @return float
     */
    public function getQtySoldnotPosted()
    {
        return $this->getData(self::QTY_SOLDNOT_POSTED);
    }

    /**
     * @param string $Colour
     * @return $this
     */
    public function setColour($Colour)
    {
        $this->setData(self::COLOUR, $Colour);
        return $this;
    }

    /**
     * @return string
     */
    public function getColour()
    {
        return $this->getData(self::COLOUR);
    }

    /**
     * @param string $Size
     * @return $this
     */
    public function setSize($Size)
    {
        $this->setData(self::SIZE, $Size);
        return $this;
    }

    /**
     * @return string
     */
    public function getSize()
    {
        return $this->getData(self::SIZE);
    }

    /**
     * @param string $Style
     * @return $this
     */
    public function setStyle($Style)
    {
        $this->setData(self::STYLE, $Style);
        return $this;
    }

    /**
     * @return string
     */
    public function getStyle()
    {
        return $this->getData(self::STYLE);
    }

    /**
     * @param float $ExpectedStock
     * @return $this
     */
    public function setExpectedStock($ExpectedStock)
    {
        $this->setData(self::EXPECTED_STOCK, $ExpectedStock);
        return $this;
    }

    /**
     * @return float
     */
    public function getExpectedStock()
    {
        return $this->getData(self::EXPECTED_STOCK);
    }

    /**
     * @param float $ReorderPoint
     * @return $this
     */
    public function setReorderPoint($ReorderPoint)
    {
        $this->setData(self::REORDER_POINT, $ReorderPoint);
        return $this;
    }

    /**
     * @return float
     */
    public function getReorderPoint()
    {
        return $this->getData(self::REORDER_POINT);
    }
}

