<?php

/**
 * @var Stores $block
 */

use \Ls\Omni\Block\Stores\Stores;

$show = true;
if (array_key_exists("data", $block->getData())) {
    $collection = $block->getData()['data'];
    $show       = false;
} else {
    $collection = $block->getStores();
}
$counter = 0;
$apiKey  = $block->getStoreMapKey();

if ($collection && $collection->getSize()) : ?>
    <?php if ($show) : ?>
        <div id="map" style="height: 300px; width: 100%;"></div>
    <?php endif; ?>
    <div class="row mt-5 stores-maps-container">
        <?php foreach ($collection as $stores) :
            $store = $stores->getData();
            $storeId = $store['no'];
            $hours = $block->hasData('storeHours') && !$block->getData('storeHours') ? [] : $block->getStoreHours($storeId);
            ?>
            <div class="col-md-4 mb-5 store-map-plus-info-container" id="store-<?= $storeId; ?>">
                <?php if ($show) : ?>
                    <div id="map<?= $counter ?>" style="height:200px;" class="store-map"></div>
                <?php endif; ?>
                <?php if (!empty($store['name'])) : ?>
                    <div class="store-name">
                        <i class="fas fa-store"></i><label><strong><?= __('Store'); ?>:</strong></label>
                        <span><?= $store['name']; ?></span>

                    </div>
                <?php endif; ?>
                <?php if (!empty($store['address']) && !empty($store['city']) && !empty($store['country_code'])) :
                    if ($store['county'] == null) :
                        $store['county'] = "";
                    endif;
                    ?>
                    <div class="store-address">
                        <i class="fas fa-map-marked-alt"></i><strong><?= __('Address'); ?>:</strong>
                        <span><a target="_blank"
                                 href="http://maps.google.com/maps?q=<?= $store['address'] . "+" . $store['city'] . "+" . $store['county'] . "+" . $store['post_code'] . "+" . $store['country_code']; ?>">
                    <?= $store['address'] . ", " . $store['city'] . " " . $store['county'] . " " . $store['post_code'] . " " . $store['country_code'] . " " . "</a><br/>"; ?></span>
                    </div>
                <?php endif; ?>
                <?php if (!empty($store['phone_no'])) : ?>
                    <div class="store-phone">
                        <i class="fas fa-phone-square-alt"></i><label><strong><?= __('Phone'); ?>:</strong></label>
                        <a href="tel:<?= $store['phone_no']; ?>"><span><?= $store['phone_no']; ?></span></a>
                    </div>
                <?php endif; ?>
                <?= $block->getLayout()->createBlock(Stores::class)
                    ->setTemplate('Ls_Omni::stores/hours.phtml')
                    ->setData(['hours' => $hours])
                    ->toHtml(); ?>
            </div>
            <?php
            $counter++;
        endforeach; ?>
        <?php if ($show) : ?>
            <script type="text/javascript">
                var apiKey = '<?= $apiKey;?>';
                var locations = [
                    <?php foreach($collection->getData() as $store) :
                    if ($store['county'] == null) :
                        $store['county'] = "";
                    endif;
                    ?>
                    ['<?= $store['name']?><br/><?= $store['address'] . ", " . $store['city'] . "  " . " " . $store['county'] . " " . $store['post_code'] . " " . $store['country_code']; ?> ', <?= $store['latitude']?>,<?= $store['longitude'];?>, 14],
                    <?php endforeach; ?>
                ];
                requirejs([
                        'Ls_Omni/js/view/stores/googlemaps'
                    ], function (map) {
                        map.allStoresMap(locations);
                        map.singleStoreMap(locations);
                    }
                );
            </script>
        <?php endif; ?>
    </div>
<?php endif; ?>
