<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Customer $customer */
$customer = $viewModels->require(Customer::class);
/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
?>
<div class="md:w-1/4 w-full flex flex-wrap pr-4">
    <div class="w-full grid grid-cols-1 sm:grid-cols-2 gap-8 xl:col-span-2">
        <nav aria-label="<?= $escaper->escapeHtmlAttr(__('Quick Links')) ?>"
             class="md:w-auto w-full flex flex-wrap pr-4">
            <div class="w-full">
                <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">
                    <?= $escaper->escapeHtml(__('Quick Links')) ?>
                </h2>
                <ul class="mt-4">
                    <li>
                        <a href="<?= $escaper->escapeUrl($block->getUrl('omni/stores')) ?>"
                           class="ls-footer-stores text-base leading-6">
                            <?= $escaper->escapeHtml(__('Stores')) ?>
                        </a>
                    </li>
                    <li class="mt-4">
                        <a href="<?= $escaper->escapeUrl($block->getUrl('omni/giftcardbalance')) ?>"
                           class="ls-footer-gift-card text-base leading-6">
                            <?= $escaper->escapeHtml(__('Check Gift Card Balance')) ?>
                        </a>
                    </li>
                    <?php // Slot for additional LS footer quick links contributed by other modules (e.g. Hospitality). ?>
                    <?= /* @noEscape */ $block->getChildHtml() ?>
                </ul>
            </div>
        </nav>
    </div>
</div>

