<?php

// @codingStandardsIgnoreFile

/** @var  $block Renderer */
/**
 * @var \Magento\Framework\Escaper $escaper
 */
$_item           = $block->getItem();
$checkIsShipment = $block->checkIsShipment();
$discountInfo    = $block->getItemDiscountLines();
$sku             = $block->getSku();
if (!empty($_item->getVariantId())) {
    $sku .= '-' . $_item->getVariantId();
}

if (!empty($_item->getUomId())) {
    $sku .= '-' . $_item->getUomId();
}

use \Ls\Customer\Block\Order\Item\Custom\Renderer; ?>
<tr id="order-item-row-<?= /* @noEscape */
$_item->getItemId() ?>">
    <td class="col name" data-th="<?= /* @noEscape */
    __('Product Name') ?>">
        <strong class="product name product-item-name"><?= /* @noEscape */
            $_item->getItemDescription() ?></strong>
        <?php if (!empty($_item->getVariantDescription())): ?>
            <p><?= /* @noEscape */
                $_item->getVariantDescription() ?></p>
        <?php endif; ?>
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option): ?>
                    <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                            <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                                        <dd><?= $escaper->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <?php $optionValue = isset($_option['print_value']) ? $_option['print_value'] : $_option['value'] ?>
                        <dd><?= $escaper->escapeHtml($optionValue) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php if (!empty($discountInfo)): ?>
            <p><strong><?= /* @noEscape */
                    $discountInfo[0]; ?></strong></p>
        <?php endif; ?>
    </td>
    <td class="col sku" data-th="<?= /* @noEscape */
    __('SKU') ?>"><?= /* @noEscape */
        $sku ?></td>
    <?php if (!$checkIsShipment): ?>
        <td class="col price" data-th="<?= /* @noEscape */
        __('Price') ?>">
            <?php if (!empty($_item->getDiscountAmount()) && $_item->getDiscountAmount() > 0): ?>
                <?php if ($block->isDisplaySalesPricesInclTax() || $block->isDisplaySalesPricesBoth()): ?>
                    <span class="price-including-tax" data-label="<?= /* @noEscape */
                    __('Incl. Tax') ?>">
                        <?= /* @noEscape */
                        $block->getFormattedPrice($_item->getAmount()); ?>
                        <div class="lsdiscountprice2">
                            <strike>
                                <?= /* @noEscape */
                                $block->getFormattedPrice($_item->getPrice() * $_item->getQuantity()); ?>
                            </strike></div>
                    </span>
                <?php endif; ?>
                <?php if ($block->isDisplaySalesPricesExclTax() || $block->isDisplaySalesPricesBoth()): ?>
                    <span class="price-excluding-tax" data-label="<?= /* @noEscape */
                    __('Excl. Tax') ?>">
                        <?= /* @noEscape */
                        $block->getFormattedPrice($_item->getNetAmount()); ?>
                        <div class="lsdiscountprice2">
                            <strike>
                                <?= /* @noEscape */
                                $block->getFormattedPrice($_item->getNetPrice() * $_item->getQuantity()); ?>
                            </strike></div>
                    </span>
                <?php endif; ?>
                <div class="lsdiscountamount">
                    <?= /* @noEscape */
                    '(' . __($block->getDiscountLabel()) . ' ' . $block->getFormattedPrice($_item->getDiscountAmount()) . ')'; ?>
                </div>
            <?php else: ?>
                <?php if ($block->isDisplaySalesPricesInclTax() || $block->isDisplaySalesPricesBoth()): ?>
                    <span class="price-including-tax" data-label="<?= /* @noEscape */
                    __('Incl. Tax') ?>">
                        <?= /* @noEscape */
                        $block->getFormattedPrice($_item->getAmount()); ?>
                    </span>
                <?php endif; ?>
                <?php if ($block->isDisplaySalesPricesExclTax() || $block->isDisplaySalesPricesBoth()): ?>
                    <span class="price-excluding-tax" data-label="<?= /* @noEscape */
                    __('Excl. Tax') ?>">
                        <?= /* @noEscape */
                        $block->getFormattedPrice($_item->getNetAmount()); ?>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= /* @noEscape */
    __('Qty') ?>">
        <?= /* @noEscape */
        $block->getFormattedQty($_item->getQuantity()); ?>
    </td>
    <?php if (!$checkIsShipment): ?>
        <td class="col subtotal" data-th="<?= /* @noEscape */
        __('Subtotal') ?>">
            <?php if ($block->isDisplaySalesSubtotalInclTax() || $block->isDisplaySalesSubtotalBoth()): ?>
                <span class="price-including-tax" data-label="<?= /* @noEscape */
                __('Incl. Tax') ?>">
                    <?= /* @noEscape */
                     $block->getFormattedPrice($_item->getAmount()); ?>
                </span>
            <?php endif; ?>
            <?php if ($block->isDisplaySalesSubtotalExclTax() || $block->isDisplaySalesSubtotalBoth()): ?>
                <span class="price-excluding-tax" data-label="<?= /* @noEscape */
                __('Excl. Tax') ?>">
                    <?= /* @noEscape */
                     $block->getFormattedPrice($_item->getNetAmount()); ?>
                </span>
            <?php endif; ?>
        </td>
    <?php endif; ?>
</tr>
