<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Cron;

use Ls\Core\Model\Data as LsHelper;
use Ls\Replication\Api\ReplLscWiDiscountsRepositoryInterface as ReplLscWiDiscountsRepository;
use Ls\Replication\Model\ReplLscWiDiscountsFactory;
use Ls\Replication\Api\Data\ReplLscWiDiscountsInterface;

class ReplLscWiDiscountsTask extends AbstractReplicationTask
{
    public const JOB_CODE = 'replication_repl_lsc_wi_discounts';

    public const CONFIG_PATH = 'ls_mag/replication/repl_lsc_wi_discounts';

    public const CONFIG_PATH_STATUS = 'ls_mag/replication/status_repl_lsc_wi_discounts';

    public const CONFIG_PATH_LAST_EXECUTE = 'ls_mag/replication/last_execute_repl_lsc_wi_discounts';

    public const CONFIG_PATH_LAST_ENTRY_NO = 'ls_mag/replication/last_entry_no_repl_lsc_wi_discounts';

    /**
     * @property ReplLscWiDiscountsRepository $repository
     */
    protected $repository = null;

    /**
     * @property ReplLscWiDiscountsFactory $factory
     */
    protected $factory = null;

    /**
     * @property ReplLscWiDiscountsInterface $dataInterface
     */
    protected $dataInterface = null;

    public function setRepository(ReplLscWiDiscountsRepository $repository)
    {
        $this->repository = $repository;
        return $this;
    }

    public function getRepository() : ReplLscWiDiscountsRepository
    {
        return $this->repository;
    }

    public function setFactory(ReplLscWiDiscountsFactory $factory)
    {
        $this->factory = $factory;
        return $this;
    }

    public function getFactory() : ReplLscWiDiscountsFactory
    {
        return $this->factory;
    }

    public function setDataInterface(ReplLscWiDiscountsInterface $dataInterface)
    {
        $this->dataInterface = $dataInterface;
        return $this;
    }

    public function getDataInterface() : ReplLscWiDiscountsInterface
    {
        return $this->dataInterface;
    }

    public function __construct(\Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig, \Magento\Config\Model\ResourceModel\Config $resourceConfig, \Ls\Replication\Logger\Logger $logger, LsHelper $helper, \Ls\Replication\Helper\ReplicationHelper $repHelper, ReplLscWiDiscountsFactory $factory, ReplLscWiDiscountsRepository $repository, ReplLscWiDiscountsInterface $dataInterface)
    {
        parent::__construct($scopeConfig, $resourceConfig, $logger, $helper, $repHelper);
        $this->repository = $repository;
        $this->factory = $factory;
        $this->dataInterface = $dataInterface;
    }

    public function makeRequest(string $baseUrl = '', array $connectionParams = [], string $companyName = '', bool $fullRepl = false, int $batchSize = 100, string $storeNo = '', int $lastEntryNo = 0, string $lastKey = '')
    {
        $request = new \Ls\Omni\Client\Ecommerce\Operation\LSCWIDiscounts($baseUrl, $connectionParams, $companyName);
        $request->setOperationInput([
        'storeNo' => $storeNo,
        'batchSize' => $batchSize,
        'fullRepl' => $fullRepl,
        'lastEntryNo' => $lastEntryNo,
        'lastKey' => $lastKey
        ]);
        return $request;
    }

    public function getConfigPath() : string
    {
        return self::CONFIG_PATH;
    }

    public function getConfigPathStatus() : string
    {
        return self::CONFIG_PATH_STATUS;
    }

    public function getConfigPathLastExecute() : string
    {
        return self::CONFIG_PATH_LAST_EXECUTE;
    }

    public function getConfigPathLastEntryNo() : string
    {
        return self::CONFIG_PATH_LAST_ENTRY_NO;
    }

    public function getMainEntity() : ReplLscWiDiscountsInterface
    {
        return $this->dataInterface;
    }
}

