<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Replication\Cron;

use Psr\Log\LoggerInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Config\Model\ResourceModel\Config;
use Ls\Core\Helper\Data as LsHelper;
use Ls\Omni\Client\Ecommerce\Entity\ReplRequest;
use Ls\Omni\Client\Ecommerce\Operation\ReplEcommCountryCode;
use Ls\Replication\Model\ReplCountryCodeRepository;
use Ls\Replication\Model\ReplCountryCodeFactory;
use Ls\Replication\Model\ReplCountryCode;

class ReplEcommCountryCodeTask extends AbstractReplicationTask
{

    const JOB_CODE = 'replication_repl_country_code';

    const CONFIG_PATH = 'ls_mag/replication/repl_country_code';

    const CONFIG_PATH_STATUS = 'ls_mag/replication/status_repl_country_code';

    /**
     * @property ReplCountryCodeRepository $repository
     */
    protected $repository = null;

    /**
     * @property ReplCountryCodeFactory $factory
     */
    protected $factory = null;

    /**
     * @param ReplCountryCodeRepository $repository
     * @return $this
     */
    public function setRepository($repository)
    {
        $this->repository = $repository;
        return $this;
    }

    /**
     * @return ReplCountryCodeRepository
     */
    public function getRepository()
    {
        return $this->repository;
    }

    /**
     * @param ReplCountryCodeFactory $factory
     * @return $this
     */
    public function setFactory($factory)
    {
        $this->factory = $factory;
        return $this;
    }

    /**
     * @return ReplCountryCodeFactory
     */
    public function getFactory()
    {
        return $this->factory;
    }

    public function __construct(ScopeConfigInterface $scope_config, Config $resource_config, LoggerInterface $logger, LsHelper $helper, ReplCountryCodeFactory $factory, ReplCountryCodeRepository $repository)
    {
        parent::__construct($scope_config, $resource_config, $logger, $helper);
        $this->repository = $repository;
        $this->factory = $factory;
    }

    public function makeRequest($last_key, $full_replication = false, $batchsize = 100, $storeId = '')
    {
        $request = new ReplEcommCountryCode();
        $request->getOperationInput()
                 ->setReplRequest( ( new ReplRequest() )->setBatchSize($batchsize)
                                                        ->setFullReplication($full_replication)
                                                        ->setLastKey($last_key)
                                                        ->setStoreId($storeId));
        return $request;
    }

    public function getConfigPath()
    {
        return self::CONFIG_PATH;
    }

    public function getConfigPathStatus()
    {
        return self::CONFIG_PATH_STATUS;
    }

    public function getMainEntity()
    {
        return ReplCountryCode::class;
    }


}

