<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Cron;

use Ls\Core\Model\Data as LsHelper;
use Ls\Replication\Api\ReplLscPosTerminalRepositoryInterface as ReplLscPosTerminalRepository;
use Ls\Replication\Model\ReplLscPosTerminalFactory;
use Ls\Replication\Api\Data\ReplLscPosTerminalInterface;

class ReplLscPosTerminalTask extends AbstractReplicationTask
{
    public const JOB_CODE = 'replication_repl_lsc_pos_terminal';

    public const CONFIG_PATH = 'ls_mag/replication/repl_lsc_pos_terminal';

    public const CONFIG_PATH_STATUS = 'ls_mag/replication/status_repl_lsc_pos_terminal';

    public const CONFIG_PATH_LAST_EXECUTE = 'ls_mag/replication/last_execute_repl_lsc_pos_terminal';

    public const CONFIG_PATH_LAST_ENTRY_NO = 'ls_mag/replication/last_entry_no_repl_lsc_pos_terminal';

    /**
     * @property ReplLscPosTerminalRepository $repository
     */
    protected $repository = null;

    /**
     * @property ReplLscPosTerminalFactory $factory
     */
    protected $factory = null;

    /**
     * @property ReplLscPosTerminalInterface $dataInterface
     */
    protected $dataInterface = null;

    public function setRepository(ReplLscPosTerminalRepository $repository)
    {
        $this->repository =  $repository;
        return $this;
    }

    public function getRepository() : ReplLscPosTerminalRepository
    {
        return $this->repository;
    }

    public function setFactory(ReplLscPosTerminalFactory $factory)
    {
        $this->factory =  $factory;
        return $this;
    }

    public function getFactory() : ReplLscPosTerminalFactory
    {
        return $this->factory;
    }

    public function setDataInterface(ReplLscPosTerminalInterface $dataInterface)
    {
        $this->dataInterface =  $dataInterface;
        return $this;
    }

    public function getDataInterface() : ReplLscPosTerminalInterface
    {
        return $this->dataInterface;
    }

    public function __construct(\Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig, \Magento\Config\Model\ResourceModel\Config $resourceConfig, \Ls\Replication\Logger\Logger $logger, LsHelper $helper, \Ls\Replication\Helper\ReplicationHelper $repHelper, ReplLscPosTerminalFactory $factory, ReplLscPosTerminalRepository $repository, ReplLscPosTerminalInterface $dataInterface)
    {
        parent::__construct($scopeConfig, $resourceConfig, $logger, $helper, $repHelper);
        $this->repository = $repository;
        $this->factory = $factory;
        $this->dataInterface = $dataInterface;
    }

    public function makeRequest(string $baseUrl = '', array $connectionParams = [], string $companyName = '', bool $fullRepl = false, int $batchSize = 100, string $storeNo = '', int $lastEntryNo = 0, string $lastKey = '')
    {
        $request = new \Ls\Omni\Client\Ecommerce\Operation\LSCPOSTerminal($baseUrl, $connectionParams, $companyName);
        $request->setOperationInput([
        'storeNo' => $storeNo,
        'batchSize' => $batchSize,
        'fullRepl' => $fullRepl,
        'lastEntryNo' => $lastEntryNo,
        'lastKey' => $lastKey
        ]);
        return $request;
    }

    public function getConfigPath() : string
    {
        return self::CONFIG_PATH;
    }

    public function getConfigPathStatus() : string
    {
        return self::CONFIG_PATH_STATUS;
    }

    public function getConfigPathLastExecute() : string
    {
        return self::CONFIG_PATH_LAST_EXECUTE;
    }

    public function getConfigPathLastEntryNo() : string
    {
        return self::CONFIG_PATH_LAST_ENTRY_NO;
    }

    public function getMainEntity() : ReplLscPosTerminalInterface
    {
        return $this->dataInterface;
    }
}

