<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Replication\Cron;

use Psr\Log\LoggerInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Config\Model\ResourceModel\Config;
use Ls\Core\Helper\Data as LsHelper;
use Ls\Omni\Client\Ecommerce\Entity\ReplRequest;
use Ls\Omni\Client\Ecommerce\Operation\ReplEcommHierarchy;
use Ls\Replication\Model\ReplHierarchyRepository;
use Ls\Replication\Model\ReplHierarchyFactory;
use Ls\Replication\Model\ReplHierarchy;

class ReplEcommHierarchyTask extends AbstractReplicationTask
{

    const JOB_CODE = 'replication_repl_hierarchy';

    const CONFIG_PATH = 'ls_mag/replication/repl_hierarchy';

    const CONFIG_PATH_STATUS = 'ls_mag/replication/status_repl_hierarchy';

    /**
     * @property ReplHierarchyRepository $repository
     */
    protected $repository = null;

    /**
     * @property ReplHierarchyFactory $factory
     */
    protected $factory = null;

    /**
     * @param ReplHierarchyRepository $repository
     * @return $this
     */
    public function setRepository($repository)
    {
        $this->repository = $repository;
        return $this;
    }

    /**
     * @return ReplHierarchyRepository
     */
    public function getRepository()
    {
        return $this->repository;
    }

    /**
     * @param ReplHierarchyFactory $factory
     * @return $this
     */
    public function setFactory($factory)
    {
        $this->factory = $factory;
        return $this;
    }

    /**
     * @return ReplHierarchyFactory
     */
    public function getFactory()
    {
        return $this->factory;
    }

    public function __construct(
        ScopeConfigInterface $scope_config,
        Config $resource_config,
        LoggerInterface $logger,
        LsHelper $helper,
        ReplHierarchyFactory $factory,
        ReplHierarchyRepository $repository)
    {
        parent::__construct($scope_config, $resource_config, $logger, $helper);
        $this->repository = $repository;
        $this->factory = $factory;
    }

    public function makeRequest($last_key, $full_replication = false, $batchsize = 100, $storeId = '')
    {
        $request = new ReplEcommHierarchy();
        $request->getOperationInput()
                 ->setReplRequest( ( new ReplRequest() )->setBatchSize($batchsize)
                                                        ->setFullReplication($full_replication)
                                                        ->setLastKey($last_key)
                                                        ->setStoreId($storeId));
        return $request;
    }

    public function getConfigPath()
    {
        return self::CONFIG_PATH;
    }

    public function getConfigPathStatus()
    {
        return self::CONFIG_PATH_STATUS;
    }

    public function getMainEntity()
    {
        return ReplHierarchy::class;
    }


}

