<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Cron;

class ReplLscRetailImageLinkTask extends ReplEcommImageLinksTask
{
    public const CONFIG_PATH_LAST_ENTRY_NO = 'ls_mag/replication/last_entry_no_repl_image_link';

    public const MODEL_CLASS = 'Ls\\Replication\\Model\\Central\\ReplLscRetailImageLink';

    public function getModelName(): string
    {
        return self::MODEL_CLASS;
    }

    public function makeRequest(string $baseUrl = '', array $connectionParams = [], string $companyName = '', bool $fullRepl = false, int $batchSize = 100, string $storeNo = '', int $lastEntryNo = 0, string $lastKey = '')
    {
        $request = new \Ls\Omni\Client\CentralEcommerce\Operation\LSCRetailImageLink($baseUrl, $connectionParams, $companyName);
        $request->setOperationInput([
        'storeNo' => $storeNo,
        'batchSize' => $batchSize,
        'fullRepl' => $fullRepl,
        'lastEntryNo' => $lastEntryNo,
        'lastKey' => $lastKey
        ]);
        return $request;
    }

    public function getConfigPathLastEntryNo(): string
    {
        return self::CONFIG_PATH_LAST_ENTRY_NO;
    }
}

