<?php
/**
 * Items list template for email
 *
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $items = $block->getItems() ?>
<?php if ($items) : ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= /* @escapeNotVerified */
                __('Items'); ?>
            </th>
            <th class="item-info">
                <?= /* @escapeNotVerified */
                __('Sku'); ?>
            </th>
            <th class="item-info">
                <?= /* @escapeNotVerified */
                __('Qty'); ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($items as $item): ?>
            <tr>
                <td class="item-info">
                    <?= /* @escapeNotVerified */
                    $item->getName() ?>
                    <table class="item-info">
                        <?php if ($options = $item->getProductOptions()): ?>
                            <?php if (isset($options['attributes_info'])): ?>
                                <?php foreach ($options['attributes_info'] as $option): ?>
                                    <br/>
                                    <strong><em><small><?= $escaper->escapeHtml($option['label']) ?></small></em></strong>
                                    <br/><?= (isset($option['print_value']) ? $escaper->escapeHtml($option['print_value']) : nl2br($escaper->escapeHtml($option['value']))) ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </table>
                </td>
                <td class="item-info"><?= $escaper->escapeHtml($item->getSku()) ?></td>
                <td class="item-info"><?= (float)$escaper->escapeHtml($item->getQtyOrdered()) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
