<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Sales\OrderCancellation;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Sales\Model\Order;
use Magento\OrderCancellationUi\ViewModel\Config as OrderCancellationUiConfig;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var OrderCancellation $orderCancellation */
$orderCancellation = $viewModels->require(OrderCancellation::class);

/** @var Order $order */
$orderHelper   = $this->helper(Ls\Omni\Helper\OrderHelper::class);
$centralOrder = $orderHelper->getLscMemberSalesBuffer($block->getParentBlock()->getOrder());
$order     = $block->getParentBlock()->getMagOrder();

$orderCancellationUiConfig = $viewModels->require(OrderCancellationUiConfig::class);
$reasons = $orderCancellationUiConfig->getCancellationReasons((int) $order->getId());

$cancelOrderId = $centralOrder && $centralOrder->getDocumentId() ? $centralOrder->getDocumentId() : $order->getRealOrderId();

$idType        = $orderHelper->getOrderType($centralOrder->getDocumentSourceType());

$recentBlock = $block->getLayout()->createBlock(
    \Ls\Customer\Block\Order\Recent::class
);
?>

<?php if ($order && $orderCancellation->canCancel($order->getEntityId()) && $recentBlock->orderCancellationOnFrontendIsEnabled()): ?>

<?php $hyvaCsp->registerInlineScript(); ?>
<button
    x-data=""
    type="button"
    class="btn btn-secondary"
    data-order-id="<?= (int) $order->getId() ?>"
    data-increment-id="<?= $escaper->escapeHtmlAttr($order->getRealOrderId()) ?>"
    data-reasons="<?= $escaper->escapeHtmlAttr(json_encode(array_values($reasons))) ?>"
    @click="$dispatch('confirm-cancel-order', {
            increment_id: '<?= $escaper->escapeJs($cancelOrderId) ?>',
            magento_order_id: '<?= $order->getId() ?>',
            central_order_id: '<?= $centralOrder->getDocumentId() ?>',
            id_type: '<?= $idType ?>',
            reasons: <?= $escaper->escapeHtmlAttr(json_encode(array_values($reasons))) ?>,
        })"
>
    <?= $heroicons->xCircleHtml('mr-1 inline-block', 24, 24, ['aria-hidden' => 'true']); ?>
    <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
</button>
<?php endif ?>
