<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Omni\Client\Loyalty\Entity;

use \Ls\Omni\Client\ResponseInterface;

class AdvertisementsGetByIdResponse implements ResponseInterface
{

    /**
     * @property ArrayOfAdvertisement $AdvertisementsGetByIdResult
     */
    protected $AdvertisementsGetByIdResult = null;

    /**
     * @param ArrayOfAdvertisement $AdvertisementsGetByIdResult
     * @return $this
     */
    public function setAdvertisementsGetByIdResult($AdvertisementsGetByIdResult)
    {
        $this->AdvertisementsGetByIdResult = $AdvertisementsGetByIdResult;
        return $this;
    }

    /**
     * @return ArrayOfAdvertisement
     */
    public function getAdvertisementsGetByIdResult()
    {
        return $this->AdvertisementsGetByIdResult;
    }

    /**
     * @return ArrayOfAdvertisement
     */
    public function getResult()
    {
        return $this->AdvertisementsGetByIdResult;
    }


}

