<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Omni\Client\Loyalty\Entity;

use IteratorAggregate;
use ArrayIterator;

class ArrayOfDealModifierGroup implements IteratorAggregate
{

    /**
     * @property DealModifierGroup[] $DealModifierGroup
     */
    protected $DealModifierGroup = array(
        
    );

    /**
     * @param DealModifierGroup[] $DealModifierGroup
     * @return $this
     */
    public function setDealModifierGroup($DealModifierGroup)
    {
        $this->DealModifierGroup = $DealModifierGroup;
        return $this;
    }

    /**
     * @return DealModifierGroup[]
     */
    public function getIterator()
    {
        return new ArrayIterator( $this->DealModifierGroup );
    }

    /**
     * @return DealModifierGroup[]
     */
    public function getDealModifierGroup()
    {
        return $this->DealModifierGroup;
    }


}

