<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Omni\Client\Loyalty\Entity;

class ProductModifier
{

    /**
     * @property string $Desc
     */
    protected $Desc = null;

    /**
     * @property string $Group
     */
    protected $Group = null;

    /**
     * @property string $Id
     */
    protected $Id = null;

    /**
     * @property string $It
     */
    protected $It = null;

    /**
     * @property float $MaxS
     */
    protected $MaxS = null;

    /**
     * @property float $MinS
     */
    protected $MinS = null;

    /**
     * @property int $Ord
     */
    protected $Ord = null;

    /**
     * @property float $Pri
     */
    protected $Pri = null;

    /**
     * @property float $Qty
     */
    protected $Qty = null;

    /**
     * @property boolean $RqS
     */
    protected $RqS = null;

    /**
     * @property string $Sub
     */
    protected $Sub = null;

    /**
     * @property string $UOM
     */
    protected $UOM = null;

    /**
     * @param string $Desc
     * @return $this
     */
    public function setDesc($Desc)
    {
        $this->Desc = $Desc;
        return $this;
    }

    /**
     * @return string
     */
    public function getDesc()
    {
        return $this->Desc;
    }

    /**
     * @param string $Group
     * @return $this
     */
    public function setGroup($Group)
    {
        $this->Group = $Group;
        return $this;
    }

    /**
     * @return string
     */
    public function getGroup()
    {
        return $this->Group;
    }

    /**
     * @param string $Id
     * @return $this
     */
    public function setId($Id)
    {
        $this->Id = $Id;
        return $this;
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * @param string $It
     * @return $this
     */
    public function setIt($It)
    {
        $this->It = $It;
        return $this;
    }

    /**
     * @return string
     */
    public function getIt()
    {
        return $this->It;
    }

    /**
     * @param float $MaxS
     * @return $this
     */
    public function setMaxS($MaxS)
    {
        $this->MaxS = $MaxS;
        return $this;
    }

    /**
     * @return float
     */
    public function getMaxS()
    {
        return $this->MaxS;
    }

    /**
     * @param float $MinS
     * @return $this
     */
    public function setMinS($MinS)
    {
        $this->MinS = $MinS;
        return $this;
    }

    /**
     * @return float
     */
    public function getMinS()
    {
        return $this->MinS;
    }

    /**
     * @param int $Ord
     * @return $this
     */
    public function setOrd($Ord)
    {
        $this->Ord = $Ord;
        return $this;
    }

    /**
     * @return int
     */
    public function getOrd()
    {
        return $this->Ord;
    }

    /**
     * @param float $Pri
     * @return $this
     */
    public function setPri($Pri)
    {
        $this->Pri = $Pri;
        return $this;
    }

    /**
     * @return float
     */
    public function getPri()
    {
        return $this->Pri;
    }

    /**
     * @param float $Qty
     * @return $this
     */
    public function setQty($Qty)
    {
        $this->Qty = $Qty;
        return $this;
    }

    /**
     * @return float
     */
    public function getQty()
    {
        return $this->Qty;
    }

    /**
     * @param boolean $RqS
     * @return $this
     */
    public function setRqS($RqS)
    {
        $this->RqS = $RqS;
        return $this;
    }

    /**
     * @return boolean
     */
    public function getRqS()
    {
        return $this->RqS;
    }

    /**
     * @param string $Sub
     * @return $this
     */
    public function setSub($Sub)
    {
        $this->Sub = $Sub;
        return $this;
    }

    /**
     * @return string
     */
    public function getSub()
    {
        return $this->Sub;
    }

    /**
     * @param string $UOM
     * @return $this
     */
    public function setUOM($UOM)
    {
        $this->UOM = $UOM;
        return $this;
    }

    /**
     * @return string
     */
    public function getUOM()
    {
        return $this->UOM;
    }


}

