<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\CentralEcommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class GetTransactionV2 extends \Magento\Catalog\Model\AbstractModel implements RequestInterface
{
    public const CLASS_NAME = 'GetTransactionV2';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    public const RECEIPT_NO = 'receiptNo';

    public const STORE_NO = 'storeNo';

    public const POS_TERMINAL_NO = 'posTerminalNo';

    public const TRANSACTION_NO = 'transactionNo';

    public const GET_TRANSACTION_V2_XML = 'getTransactionV2XML';

    /**
     * @param ?string $responseCode
     * @return $this
     */
    public function setResponsecode(?string $responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResponsecode() : ?string
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param ?string $errorText
     * @return $this
     */
    public function setErrortext(?string $errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getErrortext() : ?string
    {
        return $this->getData(self::ERROR_TEXT);
    }

    /**
     * @param ?string $receiptNo
     * @return $this
     */
    public function setReceiptno(?string $receiptNo)
    {
        $this->setData(self::RECEIPT_NO, $receiptNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getReceiptno() : ?string
    {
        return $this->getData(self::RECEIPT_NO);
    }

    /**
     * @param ?string $storeNo
     * @return $this
     */
    public function setStoreno(?string $storeNo)
    {
        $this->setData(self::STORE_NO, $storeNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStoreno() : ?string
    {
        return $this->getData(self::STORE_NO);
    }

    /**
     * @param ?string $posTerminalNo
     * @return $this
     */
    public function setPosterminalno(?string $posTerminalNo)
    {
        $this->setData(self::POS_TERMINAL_NO, $posTerminalNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getPosterminalno() : ?string
    {
        return $this->getData(self::POS_TERMINAL_NO);
    }

    /**
     * @param int $transactionNo
     * @return $this
     */
    public function setTransactionno($transactionNo)
    {
        $this->setData(self::TRANSACTION_NO, $transactionNo);
        return $this;
    }

    /**
     * @return int
     */
    public function getTransactionno()
    {
        return $this->getData(self::TRANSACTION_NO);
    }

    /**
     * @param RootGetTransaction $getTransactionV2XML
     * @return $this
     */
    public function setGettransactionv2xml($getTransactionV2XML)
    {
        $this->setData(self::GET_TRANSACTION_V2_XML, $getTransactionV2XML);
        return $this;
    }

    /**
     * @return RootGetTransaction
     */
    public function getGettransactionv2xml()
    {
        return $this->getData(self::GET_TRANSACTION_V2_XML);
    }
}

