<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\CentralEcommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class GetTokenEntry extends \Magento\Catalog\Model\AbstractModel implements RequestInterface
{
    public const CLASS_NAME = 'GetTokenEntry';

    public const RECORD_ID_P = 'recordId_p';

    public const MEMBER_CARD_NO = 'memberCardNo';

    public const TOKEN_ID = 'tokenId';

    public const EXPIRY_DATE = 'expiryDate';

    public const RESULT = 'result';

    public const RESPONSE_CODE = 'responseCode';

    public const ERROR_TEXT = 'errorText';

    /**
     * @param ?string $recordIdp
     * @return $this
     */
    public function setRecordidP(?string $recordIdp)
    {
        $this->setData(self::RECORD_ID_P, $recordIdp);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getRecordidP() : ?string
    {
        return $this->getData(self::RECORD_ID_P);
    }

    /**
     * @param ?string $memberCardNo
     * @return $this
     */
    public function setMembercardno(?string $memberCardNo)
    {
        $this->setData(self::MEMBER_CARD_NO, $memberCardNo);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getMembercardno() : ?string
    {
        return $this->getData(self::MEMBER_CARD_NO);
    }

    /**
     * @param ?string $tokenId
     * @return $this
     */
    public function setTokenid(?string $tokenId)
    {
        $this->setData(self::TOKEN_ID, $tokenId);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getTokenid() : ?string
    {
        return $this->getData(self::TOKEN_ID);
    }

    /**
     * @param ?string $expiryDate
     * @return $this
     */
    public function setExpirydate(?string $expiryDate)
    {
        $this->setData(self::EXPIRY_DATE, $expiryDate);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getExpirydate() : ?string
    {
        return $this->getData(self::EXPIRY_DATE);
    }

    /**
     * @param ?string $result
     * @return $this
     */
    public function setResult(?string $result)
    {
        $this->setData(self::RESULT, $result);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResult() : ?string
    {
        return $this->getData(self::RESULT);
    }

    /**
     * @param ?string $responseCode
     * @return $this
     */
    public function setResponsecode(?string $responseCode)
    {
        $this->setData(self::RESPONSE_CODE, $responseCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getResponsecode() : ?string
    {
        return $this->getData(self::RESPONSE_CODE);
    }

    /**
     * @param ?string $errorText
     * @return $this
     */
    public function setErrortext(?string $errorText)
    {
        $this->setData(self::ERROR_TEXT, $errorText);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getErrortext() : ?string
    {
        return $this->getData(self::ERROR_TEXT);
    }
}

