<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\CentralEcommerce\Entity;

class HierarchyDateValSched extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'HierarchyDateVal.Sched';

    public const HIERARCHY_CODE = 'HierarchyCode';

    public const VALIDATION_SCHEDULE_ID = 'ValidationScheduleID';

    public const SALES_TYPE_FILTER = 'SalesTypeFilter';

    public const PRIORITY = 'Priority';

    /**
     * @param ?string $HierarchyCode
     * @return $this
     */
    public function setHierarchycode(?string $HierarchyCode)
    {
        $this->setData(self::HIERARCHY_CODE, $HierarchyCode);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getHierarchycode() : ?string
    {
        return $this->getData(self::HIERARCHY_CODE);
    }

    /**
     * @param ?string $ValidationScheduleID
     * @return $this
     */
    public function setValidationscheduleid(?string $ValidationScheduleID)
    {
        $this->setData(self::VALIDATION_SCHEDULE_ID, $ValidationScheduleID);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getValidationscheduleid() : ?string
    {
        return $this->getData(self::VALIDATION_SCHEDULE_ID);
    }

    /**
     * @param ?string $SalesTypeFilter
     * @return $this
     */
    public function setSalestypefilter(?string $SalesTypeFilter)
    {
        $this->setData(self::SALES_TYPE_FILTER, $SalesTypeFilter);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getSalestypefilter() : ?string
    {
        return $this->getData(self::SALES_TYPE_FILTER);
    }

    /**
     * @param int $Priority
     * @return $this
     */
    public function setPriority($Priority)
    {
        $this->setData(self::PRIORITY, $Priority);
        return $this;
    }

    /**
     * @return int
     */
    public function getPriority()
    {
        return $this->getData(self::PRIORITY);
    }
}

