<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\CentralEcommerce\Entity;

class InventoryBufferOut extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'InventoryBufferOut';

    public const NUMBER = 'Number';

    public const VARIANT = 'Variant';

    public const STORE = 'Store';

    public const LOCATION = 'Location';

    public const INVENTORY = 'Inventory';

    /**
     * @param ?string $Number
     * @return $this
     */
    public function setNumber(?string $Number)
    {
        $this->setData(self::NUMBER, $Number);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getNumber() : ?string
    {
        return $this->getData(self::NUMBER);
    }

    /**
     * @param ?string $Variant
     * @return $this
     */
    public function setVariant(?string $Variant)
    {
        $this->setData(self::VARIANT, $Variant);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getVariant() : ?string
    {
        return $this->getData(self::VARIANT);
    }

    /**
     * @param ?string $Store
     * @return $this
     */
    public function setStore(?string $Store)
    {
        $this->setData(self::STORE, $Store);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getStore() : ?string
    {
        return $this->getData(self::STORE);
    }

    /**
     * @param ?string $Location
     * @return $this
     */
    public function setLocation(?string $Location)
    {
        $this->setData(self::LOCATION, $Location);
        return $this;
    }

    /**
     * @return ?string
     */
    public function getLocation() : ?string
    {
        return $this->getData(self::LOCATION);
    }

    /**
     * @param ?float $Inventory
     * @return $this
     */
    public function setInventory(?float $Inventory)
    {
        $this->setData(self::INVENTORY, $Inventory);
        return $this;
    }

    /**
     * @return ?float
     */
    public function getInventory() : ?float
    {
        return $this->getData(self::INVENTORY);
    }
}

