<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */

namespace Ls\Omni\Client\CentralEcommerce\Entity;

use Magento\Catalog\Model\AbstractModel;

class LSCHospitalityType extends AbstractModel
{
    public const RESTAURANT_NO = 'Restaurant No.';
    public const SEQUENCE = 'Sequence';
    public const SALES_TYPE = 'Sales Type';
    public const TIPS_CALCULATION = 'Tips Calculation';
    public const TIPS_INCOME_ACC_1 = 'Tips Income Acc. 1';
    public const TIPS_INCOME_ACC_2 = 'Tips Income Acc. 2';
    public const SUGGESTED_TIPS_1_PERCENTAGE = 'Suggested Tips 1 Percentage';
    public const SUGGESTED_TIPS_2_PERCENTAGE = 'Suggested Tips 2 Percentage';
    public const SUGGESTED_TIPS_3_PERCENTAGE = 'Suggested Tips 3 Percentage';

    public static array $dbColumnsMapping = [
	self::RESTAURANT_NO => 'restaurant_no',
	self::SEQUENCE => 'sequence',
	self::SALES_TYPE => 'sales_type',
	self::TIPS_CALCULATION => 'tips_calculation',
	self::TIPS_INCOME_ACC_1 => 'tips_income_acc_1',
	self::TIPS_INCOME_ACC_2 => 'tips_income_acc_2',
	self::SUGGESTED_TIPS_1_PERCENTAGE => 'suggested_tips_1_percentage',
	self::SUGGESTED_TIPS_2_PERCENTAGE => 'suggested_tips_2_percentage',
	self::SUGGESTED_TIPS_3_PERCENTAGE => 'suggested_tips_3_percentage',
    ];

    public static function getDbColumnsMapping(): array
    {
        return self::$dbColumnsMapping;
    }


    public function getRestaurantNo(): ?string
    {
        return $this->getData(self::RESTAURANT_NO);
    }

    public function setRestaurantNo(?string $value)
    {
        return $this->setData(self::RESTAURANT_NO, $value);
    }

    public function getSequence(): ?int
    {
        return $this->getData(self::SEQUENCE);
    }

    public function setSequence(?int $value)
    {
        return $this->setData(self::SEQUENCE, $value);
    }

    public function getSalesType(): ?string
    {
        return $this->getData(self::SALES_TYPE);
    }

    public function setSalesType(?string $value)
    {
        return $this->setData(self::SALES_TYPE, $value);
    }

    public function getTipsCalculation(): ?int
    {
        return $this->getData(self::TIPS_CALCULATION);
    }

    public function setTipsCalculation(?int $value)
    {
        return $this->setData(self::TIPS_CALCULATION, $value);
    }

    public function getTipsIncomeAcc1(): ?string
    {
        return $this->getData(self::TIPS_INCOME_ACC_1);
    }

    public function setTipsIncomeAcc1(?string $value)
    {
        return $this->setData(self::TIPS_INCOME_ACC_1, $value);
    }

    public function getTipsIncomeAcc2(): ?string
    {
        return $this->getData(self::TIPS_INCOME_ACC_2);
    }

    public function setTipsIncomeAcc2(?string $value)
    {
        return $this->setData(self::TIPS_INCOME_ACC_2, $value);
    }

    public function getSuggestedTips1Percentage(): ?float
    {
        return $this->getData(self::SUGGESTED_TIPS_1_PERCENTAGE);
    }

    public function setSuggestedTips1Percentage(?float $value)
    {
        return $this->setData(self::SUGGESTED_TIPS_1_PERCENTAGE, $value);
    }

    public function getSuggestedTips2Percentage(): ?float
    {
        return $this->getData(self::SUGGESTED_TIPS_2_PERCENTAGE);
    }

    public function setSuggestedTips2Percentage(?float $value)
    {
        return $this->setData(self::SUGGESTED_TIPS_2_PERCENTAGE, $value);
    }

    public function getSuggestedTips3Percentage(): ?float
    {
        return $this->getData(self::SUGGESTED_TIPS_3_PERCENTAGE);
    }

    public function setSuggestedTips3Percentage(?float $value)
    {
        return $this->setData(self::SUGGESTED_TIPS_3_PERCENTAGE, $value);
    }
}