<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\CentralEcommerce\Entity;

class RootSetTokenEntry extends \Magento\Catalog\Model\AbstractModel
{
    public const CLASS_NAME = 'RootSetTokenEntry';

    public const TOKEN = 'Token';

    /**
     * @param Token $Token
     * @return $this
     */
    public function setToken($Token)
    {
        $this->setData(self::TOKEN, $Token);
        return $this;
    }

    /**
     * @return Token
     */
    public function getToken()
    {
        return $this->getData(self::TOKEN);
    }
}

