<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api;

use Ls\Replication\Api\Data\ReplStoreviewInterface;
use Magento\Framework\Api\SearchCriteriaInterface;

/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */
interface ReplStoreviewRepositoryInterface
{
    public function getList(SearchCriteriaInterface $criteria);

    public function save(ReplStoreviewInterface $page);

    public function delete(ReplStoreviewInterface $page);

    public function getById($id);

    public function deleteById($id);
}

