<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api;

use Ls\Replication\Api\Data\ReplHierarchyviewInterface;
use Magento\Framework\Api\SearchCriteriaInterface;

/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */
interface ReplHierarchyviewRepositoryInterface
{
    public function getList(SearchCriteriaInterface $criteria);

    public function save(ReplHierarchyviewInterface $page);

    public function delete(ReplHierarchyviewInterface $page);

    public function getById($id);

    public function deleteById($id);
}

