<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity;

use Ls\Omni\Client\RequestInterface;

class ItemCustomerPricesGet implements RequestInterface
{
    /**
     * @property ArrayOfItemCustomerPrice $items
     */
    protected $items = null;

    /**
     * @property string $storeId
     */
    protected $storeId = null;

    /**
     * @property string $cardId
     */
    protected $cardId = null;

    /**
     * @param ArrayOfItemCustomerPrice $items
     * @return $this
     */
    public function setItems($items)
    {
        $this->items = $items;
        return $this;
    }

    /**
     * @return ArrayOfItemCustomerPrice
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * @param string $storeId
     * @return $this
     */
    public function setStoreId($storeId)
    {
        $this->storeId = $storeId;
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreId()
    {
        return $this->storeId;
    }

    /**
     * @param string $cardId
     * @return $this
     */
    public function setCardId($cardId)
    {
        $this->cardId = $cardId;
        return $this;
    }

    /**
     * @return string
     */
    public function getCardId()
    {
        return $this->cardId;
    }
}

