<?php

// @codingStandardsIgnoreFile

/** @var Telephone $block */

use Magento\Customer\Block\Widget\Telephone; ?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <?php
        $_validationClass = $block->escapeHtmlAttr(
            $this->helper('Magento\Customer\Helper\Address')
                ->getAttributeValidationClass('telephone')
        );
        ?>
        <input type="text" maxlength="30" data-validate='{"required":true,"maxlength":30}'
               name="telephone"
               id="telephone"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>
