<?php
/** @var Proactive $block */

use \Ls\Omni\Block\Product\View\Discount\Proactive;

$currentProductSku = $block->getProductSku();
$ajaxUrl           = $block->getAjaxUrl();
$isEnabled         = $block->isDiscountEnable();

if ($isEnabled) {
    ?>

    <div id="ls-discounts">
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */
            $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */
                 __('Loading...') ?>">
            <br/>
            <div><?php echo __('Loading Product Discounts...'); ?></div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Ls_Omni/js/view/product/proactive": {
                    "ajaxUrl": "<?php echo $ajaxUrl; ?>",
                    "currentProduct": "<?php echo $currentProductSku; ?>"
                }
            }
        }

    </script>
<?php }