<?php
/** @var Recommend $block */

use \Ls\Omni\Block\Product\View\Recommend;

if ($block->isEnabled() && $block->isValid()) :
    $currentProductSku = $block->getProductBySku();
    $ajaxUrl           = $block->getAjaxUrl();
    ?>
    <div id="lsRecommendation">
        <div class="ls-loader">
            <img src="<?= /* @escapeNotVerified */
            $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */
                 __('Loading...') ?>">
            <br/>
            <div><?php echo __('Loading recommended products for you...'); ?></div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Ls_Omni/js/view/product/recommendation": {
                    "ajaxUrl": "<?php echo $ajaxUrl; ?>",
                    "currentProduct": "<?php echo $currentProductSku; ?>"
                }
            }
        }
    </script>
<?php endif; ?>
