<?php
/** @var \Ls\Omni\Block\Product\View\Recommend $block */
if ($block->isEnabled()) {
    $currentProductSku = $block->getProductBySku();
    $ajaxUrl = $block->getAjaxUrl();
    ?>
    <div id="lsRecommendation">
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */
            $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */
                 __('Loading...') ?>">
            <br/>
            <div><?php echo __('Loading LS Recommendation...'); ?></div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Ls_Omni/js/view/product/recommendation": {
                    "ajaxUrl": "<?php echo $ajaxUrl; ?>",
                    "currentProduct": "<?php echo $currentProductSku; ?>"
                }
            }
        }
    </script>
<?php } ?>