<?php
// @codingStandardsIgnoreFile
/** @var $block Info */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Ls\Core\Model\LSR;
use Ls\Customer\Block\Order\Info;
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$centralOrder = $block->getOrder();
$magOrder     = $block->getMagOrder();
?>
<div class="flex items-center justify-center md:justify-start flex-wrap gap-4 md:gap-x-6 my-4 md:my-0">
    <?php if (!empty($magOrder)): ?>

        <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($magOrder->getId())): ?>
            <?php $formData = json_decode(
                $this->helper(PostHelper::class)->getPostData(
                    $block->getReorderUrl($magOrder)
                ),
                true
            ) ?>
            <form id="reorder-form"
                  action="<?= $escaper->escapeUrl($formData['action']) ?>"
                  method="post"
                  class="inline-flex items-center">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="data" value='<?= /** @noEscape */ json_encode($formData['data']) ?>'>
                <button type="submit" class="btn btn-secondary">
                    <?= $heroicons->refreshHtml('mr-1 inline-block', 24, 24, ['aria-hidden' => 'true']) ?>
                    <span><?= $escaper->escapeHtml(__('Reorder')) ?></span>
                </button>
            </form>
        <?php endif ?>

        <?php if ($magOrder->canCancel() &&
            $block->orderCancellationOnFrontendIsEnabled() &&
            strtolower($block->getOrderStatus()) !== strtolower(LSR::LS_STATE_CANCELED)): ?>
            <?php $cancelFormData = json_decode(
                $this->helper(PostHelper::class)->getPostData(
                    $block->getCancelUrl($magOrder, $centralOrder),
                    [
                        'confirmation'        => 1,
                        'confirmationMessage' => __('Do you wish to cancel this order?')
                    ]
                ),
                true
            ) ?>
            <form id="cancel-form"
                  action="<?= $escaper->escapeUrl($cancelFormData['action']) ?>"
                  method="post"
                  class="inline-flex items-center">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden" name="data" value='<?= /** @noEscape */ json_encode($cancelFormData['data']) ?>'>
                <button type="submit" class="btn btn-secondary">
                    <?= $heroicons->xCircleHtml('mr-1 inline-block', 24, 24, ['aria-hidden' => 'true']) ?>
                    <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
                </button>
            </form>
        <?php endif ?>

        <a href="<?= $escaper->escapeUrl($block->getPrintUrl($centralOrder)) ?>"
           class="btn btn-secondary"
           target="_blank"
           rel="noopener">
            <?= $heroicons->printerHtml('mr-1 inline-block', 24, 24, ['aria-hidden' => 'true']) ?>
            <span><?= $escaper->escapeHtml(__('Print Order')) ?></span>
        </a>

        <?= $block->getChildHtml() ?>

    <?php endif ?>
</div>
