<?php
// @codingStandardsIgnoreFile
/** @var  $block Info */

use Ls\Customer\Block\Order\Info;
use Magento\Framework\Data\Helper\PostHelper;

?>
<?php
$centralOrder   = $block->getOrder();
$magOrder = $block->getMagOrder();
?>
<div class="actions">
    <?php if (!empty($magOrder)) : ?>
        <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($magOrder->getId())) : ?>
            <a href="#"
               class="action order reorder"
               data-post='<?= /* @escapeNotVerified */
               $this->helper(PostHelper::class)->getPostData($block->getReorderUrl($magOrder))
            ?>'>
                <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
            </a>
        <?php endif ?>
        <?php if ($magOrder->canCancel() && $block->orderCancellationOnFrontendIsEnabled()): ?>
            <a href="#"
               class="action order cancel"
               data-post='<?= /* @escapeNotVerified */
               $this->helper(PostHelper::class)->getPostData(
                   $block->getCancelUrl($magOrder, $centralOrder),
                   [
                       'confirmation' => 1,
                       'confirmationMessage' => __('Do you wish to cancel this order?')
                   ]
               )
               ?>'>
                <span><?= /* @escapeNotVerified */ __('Cancel') ?></span>
            </a>
        <?php endif; ?>
        <a class="action order print"
           href="<?= /* @escapeNotVerified */ $block->getPrintUrl($centralOrder) ?>"
           onclick="this.target='_blank';">
            <span><?= /* @escapeNotVerified */ __('Print Order') ?></span>
        </a>
        <?= $block->getChildHtml() ?>
    <?php endif; ?>
</div>
