<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity\Enum;

use MyCLabs\Enum\Enum;

/**
 * @$method static DiscountType PERIODIC_DISC()
 * @$method static DiscountType CUSTOMER()
 * @$method static DiscountType INFO_CODE()
 * @$method static DiscountType TOTAL()
 * @$method static DiscountType LINE()
 * @$method static DiscountType PROMOTION()
 * @$method static DiscountType DEAL()
 * @$method static DiscountType TOTAL_DISCOUNT()
 * @$method static DiscountType TENDER_TYPE()
 * @$method static DiscountType ITEM_POINT()
 * @$method static DiscountType LINE_DISCOUNT()
 * @$method static DiscountType MEMBER_POINT()
 * @$method static DiscountType COUPON()
 * @$method static DiscountType UNKNOWN()
 */
class DiscountType extends Enum
{

    const PERIODIC_DISC = 'PeriodicDisc';

    const CUSTOMER = 'Customer';

    const INFO_CODE = 'InfoCode';

    const TOTAL = 'Total';

    const LINE = 'Line';

    const PROMOTION = 'Promotion';

    const DEAL = 'Deal';

    const TOTAL_DISCOUNT = 'TotalDiscount';

    const TENDER_TYPE = 'TenderType';

    const ITEM_POINT = 'ItemPoint';

    const LINE_DISCOUNT = 'LineDiscount';

    const MEMBER_POINT = 'MemberPoint';

    const COUPON = 'Coupon';

    const UNKNOWN = 'Unknown';


}

