<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Omni\Client\Ecommerce\Entity\Enum;

use MyCLabs\Enum\Enum;

/**
 * @$method static DocumentIdType ORDER()
 * @$method static DocumentIdType EXTERNAL()
 * @$method static DocumentIdType RECEIPT()
 */
class DocumentIdType extends Enum
{

    public const ORDER = 'Order';

    public const EXTERNAL = 'External';

    public const RECEIPT = 'Receipt';


}

