<?php
// @codingStandardsIgnoreFile

/**
 * Recent order template
 *
 * @var Renderer $block
 * @var Escaper $escaper
 * @var Data $helper
 */

use Ls\Omni\Block\Cart\Item\Renderer;
use Magento\Msrp\Helper\Data;
use Magento\Framework\Escaper;

$_item            = $block->getItem();
$product          = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$basketData       = $block->getOneListCalculateData($_item);

$helper              = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp        = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$this->priceCurrency = $block->getPriceCurrency();
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()): ?>
            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
               title="<?= $escaper->escapeHtml($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo">
        <?php else: ?>
            <span class="product-item-photo">
        <?php endif; ?>
        <?= $block->getImage(
            $block->getProductForThumbnail(),
            'cart_page_product_thumbnail'
        )->toHtml() ?>
        <?php if ($block->hasProductUrl()): ?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>">
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    </a>
                <?php else: ?>
                    <?= $escaper->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($_options = $block->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $_option['label'] ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?= $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if (!empty($basketData)): ?>
                <p><strong><?= $basketData[0] ?></strong></p>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= $escaper->escapeHtml($message['type']) ?>">
                        <div><?= $escaper->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
        </div>
    </td>

    <?php if ($canApplyMsrp): ?>
        <td class="col msrp" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice">
                        <?= $escaper->escapeHtml(__('See price before order confirmation.')) ?>
                    </span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= $escaper->escapeHtml($helpLinkId) ?>"
                       data-mage-init='{"addToCart":{"helpLinkId": "#<?= $escaper->escapeHtml(
                        $helpLinkId) ?>","productName": "<?=$escaper->escapeHtml(
                        $product->getName()) ?>","showAddToCart": false}}'>
                        <span><?= $escaper->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
        </td>
    <?php else: ?>
        <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
            <?php if (!empty($basketData)): ?>
                <span class="price-excluding-tax" data-label="Excl. Tax">
                    <span class="cart-price">
                        <?= $this->priceCurrency->format($block->getItemRowTotal($_item), true); ?><br/>
                        <?php if ($_item->getDiscountAmount() > 0): ?>
                            <div class="lsdiscountprice2">
                            <strike>
                                <?= $this->priceCurrency->format($_item->getProduct()->getPrice() * (int)$block->getQty(), true); ?>
                            </strike>
                            </div>
                        <?php endif; ?>
                    </span>
                </span>
                <?php if ($_item->getDiscountAmount() > 0): ?>
                    <div class="lsdiscountamount">
                        <?= '(' . __($basketData[1]) . ' ' . $this->priceCurrency->format($_item->getDiscountAmount()) . ')';
                        ?>
                    </div>
                <?php endif; ?>
            <?php else: ?>
                <?= $block->getUnitPriceHtml($_item); ?>
            <?php endif; ?>

        </td>
    <?php endif; ?>
    <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <label class="label" for="cart-<?= $escaper->escapeHtml($_item->getId()) ?>-qty">
                <span><?= $escaper->escapeHtml(__('Qty')) ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?= $escaper->escapeHtml($_item->getId()) ?>-qty"
                       name="cart[<?= $escaper->escapeHtml($_item->getId()) ?>][qty]"
                       data-cart-item-id="<?= $escaper->escapeHtml($_item->getSku()) ?>"
                       value="<?= $escaper->escapeHtml($block->getQty()) ?>"
                       type="number"
                       size="4"
                       title="<?= $escaper->escapeHtml(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
            </div>
        </div>
    </td>

    <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?php if (!empty($basketData)): ?>
                <span class="price-excluding-tax" data-label="Excl. Tax">
                    <span class="cart-price">
                        <?= $this->priceCurrency->format($block->getItemRowTotal($_item), true); ?>
                    </span>
        </span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        <?php endif; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="100">
        <div class="actions-toolbar">
            <?= $block->getActions($_item) ?>
        </div>
    </td>
</tr>
</tbody>
