<?php
// @codingStandardsIgnoreFile

/**
 * @var $block DefaultRenderer
 * @var $viewModel ItemRenderer
 * @var \Magento\Framework\Escaper $escaper
 */

use Ls\Customer\ViewModel\ItemRenderer;
use Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer;

$_item     = $block->getItem();
$viewModel = $block->getViewModel();
list($discountInfo, $line) = $viewModel->getDiscountInfoGivenOrderItem($_item);

if (!empty($discountInfo)) {
    $discountDescription = $discountInfo[0] ?? '';
}
?>
<tr id="order-item-row-<?= (int)$_item->getId() ?>">
    <td class="col name" data-th="<?= $escaper->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $escaper->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option): ?>
                    <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dd<?= (isset($_formatedOptionValue['full_view']) ? ' class="tooltip wrapper"' : '') ?>>
                            <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt><?= $escaper->escapeHtml($_option['label']) ?></dt>
                                        <dd><?= $escaper->escapeHtml($_formatedOptionValue['full_view']) ?></dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <?php $optionValue = isset($_option['print_value']) ? $_option['print_value'] : $_option['value'] ?>
                        <dd><?= $escaper->escapeHtml($optionValue) ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock): ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $escaper->escapeHtml($_item->getDescription()) ?>
        <?php if (!empty($discountDescription)): ?>
            <p><strong><?= $discountDescription; ?></strong></p>
        <?php endif; ?>
    </td>
    <td class="col sku" data-th="<?= $escaper->escapeHtml(__('SKU')) ?>">
        <?= /* @noEscape */
        $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
        <?php if ($line && !empty($line->getDiscountAmount()) && $line->getDiscountAmount() > 0) : ?>
            <?= $viewModel->getFormattedPrice(($line->getAmount() / $line->getQuantity()) * $_item->getQtyOrdered()); ?>
            <div class="lsdiscountprice2">
                <span><?= $viewModel->getFormattedPrice($line->getPrice() * $_item->getQtyOrdered()); ?></span></div>
            <div class="lsdiscountamount">
                <?= '(' . __('Save') . ' ' . $viewModel->getFormattedPrice(($line->getDiscountAmount() / $line->getQuantity()) * $_item->getQtyOrdered()) . ')'; ?>
            </div>
        <?php else: ?>
            <?= $viewModel->getFormattedPrice($block->getItem()->getPrice()) ?>
        <?php endif; ?>
    </td>
    <td class="col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="title"><?= $escaper->escapeHtml(__('Ordered')) ?></span>
                    <span class="content"><?= (float)$block->getItem()->getQtyOrdered() ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
        <?= $viewModel->getFormattedPrice($block->getItem()->getRowTotal()) ?>
    </td>
</tr>
