<?php
// @codingStandardsIgnoreFile
use Magento\Customer\Block\Account\Forgotpassword;
use Magento\Customer\ViewModel\ForgotPasswordButton;

/**
 *
 * @var Forgotpassword $block
 * @var ForgotPasswordButton $forgotPasswordButtonViewModel
 */
$forgotPasswordButtonViewModel = $block->getData('forgot_password_button_view_model');
if ($forgotPasswordButtonViewModel == null) {
    $forgotPasswordButtonViewModel = $block;
}
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note">
            <?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?>
        </div>
        <div class="field email required">
            <label for="email_address"
                   class="label">
                <span><?= $block->escapeHtml(__('Username/Email')) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="email"
                       alt="email"
                       id="email_address"
                       class="input-text"
                       value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>"
                       data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action submit primary"
                    id="send2"
                <?php if ($forgotPasswordButtonViewModel && $forgotPasswordButtonViewModel->getButtonLockManager()->isDisabled('customer_forgot_password_form_submit')): ?> disabled="disabled" <?php endif; ?>>
                <span><?= $block->escapeHtml(__('Reset My Password')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?= $block->escapeUrl($block->getLoginUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
