<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Data;

interface ReplLscWiItemModifierInterface
{
    public function getDbColumnsMapping() : array;

    public function getParentItemNo() : ?string;

    public function setParentItemNo(?string $value);

    public function getInfocodeCode() : ?string;

    public function setInfocodeCode(?string $value);

    public function getSubcode() : ?string;

    public function setSubcode(?string $value);

    public function getExplanatoryHeaderText() : ?string;

    public function setExplanatoryHeaderText(?string $value);

    public function getPrompt() : ?string;

    public function setPrompt(?string $value);

    public function getGroupMinSelection() : ?int;

    public function setGroupMinSelection(?int $value);

    public function getGroupMaxSelection() : ?int;

    public function setGroupMaxSelection(?int $value);

    public function getItemNo() : ?string;

    public function setItemNo(?string $value);

    public function getVariantCode() : ?string;

    public function setVariantCode(?string $value);

    public function getDescription() : ?string;

    public function setDescription(?string $value);

    public function getMinSelection() : ?int;

    public function setMinSelection(?int $value);

    public function getMaxSelection() : ?int;

    public function setMaxSelection(?int $value);

    public function getPriceHandling() : ?string;

    public function setPriceHandling(?string $value);

    public function getPriceType() : ?string;

    public function setPriceType(?string $value);

    public function getAmountPercent() : ?string;

    public function setAmountPercent(?string $value);

    public function getUnitOfMeasure() : ?string;

    public function setUnitOfMeasure(?string $value);

    public function getQtyPerUnitOfMeasure() : ?string;

    public function setQtyPerUnitOfMeasure(?string $value);

    public function getTimeModifierMinutes() : ?string;

    public function setTimeModifierMinutes(?string $value);

    public function getSystemid() : ?string;

    public function setSystemid(?string $value);

    public function getSystemcreatedat() : ?\DateTime;

    public function setSystemcreatedat(?\DateTime $value);

    public function getSystemcreatedby() : ?string;

    public function setSystemcreatedby(?string $value);

    public function getSystemmodifiedat() : ?\DateTime;

    public function setSystemmodifiedat(?\DateTime $value);

    public function getSystemmodifiedby() : ?string;

    public function setSystemmodifiedby(?string $value);

    public function setProcessed(bool $processed);

    public function getProcessed() : bool;

    public function setIsUpdated(bool $is_updated);

    public function getIsUpdated() : bool;

    public function setIsFailed(bool $is_failed);

    public function getIsFailed() : bool;

    public function setCreatedAt(string $created_at);

    public function getCreatedAt() : string;

    public function setUpdatedAt(string $updated_at);

    public function getUpdatedAt() : string;

    public function setIdentityValue(string $identity_value);

    public function getIdentityValue() : string;

    public function setChecksum(string $checksum);

    public function getChecksum() : string;

    public function setProcessedAt(string $processed_at);

    public function getProcessedAt() : string;
}

