<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Data;

interface ReplItemUnitOfMeasureInterface
{

    /**
     * @param string $Code
     * @return $this
     */
    public function setCode($Code);

    /**
     * @return string
     */
    public function getCode();

    /**
     * @param boolean $CountAsOne
     * @return $this
     */
    public function setCountAsOne($CountAsOne);

    /**
     * @return boolean
     */
    public function getCountAsOne();

    /**
     * @param boolean $IsDeleted
     * @return $this
     */
    public function setIsDeleted($IsDeleted);

    /**
     * @return boolean
     */
    public function getIsDeleted();

    /**
     * @param string $ItemId
     * @return $this
     */
    public function setItemId($ItemId);

    /**
     * @return string
     */
    public function getItemId();

    /**
     * @param int $Order
     * @return $this
     */
    public function setOrder($Order);

    /**
     * @return int
     */
    public function getOrder();

    /**
     * @param float $QtyPrUOM
     * @return $this
     */
    public function setQtyPrUOM($QtyPrUOM);

    /**
     * @return float
     */
    public function getQtyPrUOM();

    /**
     * @param int $Selection
     * @return $this
     */
    public function setSelection($Selection);

    /**
     * @return int
     */
    public function getSelection();

    /**
     * @param string $StoreId
     * @return $this
     */
    public function setStoreId($StoreId);

    /**
     * @return string
     */
    public function getStoreId();

    /**
     * @param string $UnitOfMeasure
     * @return $this
     */
    public function setUnitOfMeasure($UnitOfMeasure);

    /**
     * @return string
     */
    public function getUnitOfMeasure();

    /**
     * @param string $scope
     * @return $this
     */
    public function setScope($scope);

    /**
     * @return string
     */
    public function getScope();

    /**
     * @param int $scope_id
     * @return $this
     */
    public function setScopeId($scope_id);

    /**
     * @return int
     */
    public function getScopeId();

    /**
     * @param string $processed
     * @return $this
     */
    public function setProcessed($processed);

    /**
     * @return string
     */
    public function getProcessed();


}

