<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Data;

interface ReplItemuomupdviewInterface
{
    public function getDbColumnsMapping() : array;

    public function getItemNo() : ?string;

    public function setItemNo(?string $value);

    public function getCode() : ?string;

    public function setCode(?string $value);

    public function getQtyPerUnitOfMeasure() : ?string;

    public function setQtyPerUnitOfMeasure(?string $value);

    public function getQtyRoundingPrecision() : ?string;

    public function setQtyRoundingPrecision(?string $value);

    public function getLength() : ?string;

    public function setLength(?string $value);

    public function getWidth() : ?string;

    public function setWidth(?string $value);

    public function getHeight() : ?string;

    public function setHeight(?string $value);

    public function getCubage() : ?string;

    public function setCubage(?string $value);

    public function getWeight() : ?string;

    public function setWeight(?string $value);

    public function getLscNoInBarcode() : ?string;

    public function setLscNoInBarcode(?string $value);

    public function getLscPrintShelfLabel() : ?bool;

    public function setLscPrintShelfLabel(?bool $value);

    public function getLscTextOnShelfLabel() : ?string;

    public function setLscTextOnShelfLabel(?string $value);

    public function getLscCountAs1OnReceipt() : ?bool;

    public function setLscCountAs1OnReceipt(?bool $value);

    public function getLscPosSelection() : ?string;

    public function setLscPosSelection(?string $value);

    public function getLscOrder() : ?int;

    public function setLscOrder(?int $value);

    public function getLscEcomSelection() : ?string;

    public function setLscEcomSelection(?string $value);

    public function getSystemid() : ?string;

    public function setSystemid(?string $value);

    public function getSystemcreatedat() : ?\DateTime;

    public function setSystemcreatedat(?\DateTime $value);

    public function getSystemcreatedby() : ?string;

    public function setSystemcreatedby(?string $value);

    public function getSystemmodifiedat() : ?\DateTime;

    public function setSystemmodifiedat(?\DateTime $value);

    public function getSystemmodifiedby() : ?string;

    public function setSystemmodifiedby(?string $value);

    public function getDescription() : ?string;

    public function setDescription(?string $value);

    public function setProcessed(bool $processed);

    public function getProcessed() : bool;

    public function setIsUpdated(bool $is_updated);

    public function getIsUpdated() : bool;

    public function setIsFailed(bool $is_failed);

    public function getIsFailed() : bool;

    public function setCreatedAt(string $created_at);

    public function getCreatedAt() : string;

    public function setUpdatedAt(string $updated_at);

    public function getUpdatedAt() : string;

    public function setIdentityValue(string $identity_value);

    public function getIdentityValue() : string;

    public function setChecksum(string $checksum);

    public function getChecksum() : string;

    public function setProcessedAt(string $processed_at);

    public function getProcessedAt() : string;
}

