<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Data;

interface ReplLscTenderTypeCurrencySetupInterface
{
    public static function getDbColumnsMapping() : array;

    public function getCurrencyCode() : ?string;

    public function setCurrencyCode(?string $value);

    public function getDescription() : ?string;

    public function setDescription(?string $value);

    public function getStoreNo() : ?string;

    public function setStoreNo(?string $value);

    public function getTenderTypeCode() : ?string;

    public function setTenderTypeCode(?string $value);

    public function getAccountType() : ?int;

    public function setAccountType(?int $value);

    public function getAccountNo() : ?string;

    public function setAccountNo(?string $value);

    public function getAccountName() : ?string;

    public function setAccountName(?string $value);

    public function getDifferenceGLAcc() : ?string;

    public function setDifferenceGLAcc(?string $value);

    public function getPrimaryKey() : ?string;

    public function setPrimaryKey(?string $value);

    public function getPosPickupWarningAmount() : ?float;

    public function setPosPickupWarningAmount(?float $value);

    public function getPosPickupWarningText() : ?string;

    public function setPosPickupWarningText(?string $value);

    public function getSystemid() : ?string;

    public function setSystemid(?string $value);

    public function getSystemcreatedat() : ?string;

    public function setSystemcreatedat(?string $value);

    public function getSystemcreatedby() : ?string;

    public function setSystemcreatedby(?string $value);

    public function getSystemmodifiedat() : ?string;

    public function setSystemmodifiedat(?string $value);

    public function getSystemmodifiedby() : ?string;

    public function setSystemmodifiedby(?string $value);

    public function setProcessed(?bool $processed);

    public function getProcessed() : ?bool;

    public function setIsUpdated(?bool $is_updated);

    public function getIsUpdated() : ?bool;

    public function setIsFailed(?bool $is_failed);

    public function getIsFailed() : ?bool;

    public function setCreatedAt(?string $created_at);

    public function getCreatedAt() : ?string;

    public function setUpdatedAt(?string $updated_at);

    public function getUpdatedAt() : ?string;

    public function setIdentityValue(?string $identity_value);

    public function getIdentityValue() : ?string;

    public function setChecksum(?string $checksum);

    public function getChecksum() : ?string;

    public function setProcessedAt(?string $processed_at);

    public function getProcessedAt() : ?string;
}

