<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Data;

interface ReplLscWiItemRecipeBufferInterface
{
    public function getDbColumnsMapping() : array;

    public function getParentItemNo() : ?string;

    public function setParentItemNo(?string $value);

    public function getLineNo() : ?int;

    public function setLineNo(?int $value);

    public function getType() : ?string;

    public function setType(?string $value);

    public function getNo() : ?string;

    public function setNo(?string $value);

    public function getDescription() : ?string;

    public function setDescription(?string $value);

    public function getUnitOfMeasureCode() : ?string;

    public function setUnitOfMeasureCode(?string $value);

    public function getQuantityPer() : ?string;

    public function setQuantityPer(?string $value);

    public function getLscItemNo() : ?string;

    public function setLscItemNo(?string $value);

    public function getLscExclusion() : ?string;

    public function setLscExclusion(?string $value);

    public function getLscPriceOnExclusion() : ?string;

    public function setLscPriceOnExclusion(?string $value);

    public function getRetailImageId() : ?string;

    public function setRetailImageId(?string $value);

    public function getSystemid() : ?string;

    public function setSystemid(?string $value);

    public function getSystemcreatedat() : ?\DateTime;

    public function setSystemcreatedat(?\DateTime $value);

    public function getSystemcreatedby() : ?string;

    public function setSystemcreatedby(?string $value);

    public function getSystemmodifiedat() : ?\DateTime;

    public function setSystemmodifiedat(?\DateTime $value);

    public function getSystemmodifiedby() : ?string;

    public function setSystemmodifiedby(?string $value);

    public function setProcessed(bool $processed);

    public function getProcessed() : bool;

    public function setIsUpdated(bool $is_updated);

    public function getIsUpdated() : bool;

    public function setIsFailed(bool $is_failed);

    public function getIsFailed() : bool;

    public function setCreatedAt(string $created_at);

    public function getCreatedAt() : string;

    public function setUpdatedAt(string $updated_at);

    public function getUpdatedAt() : string;

    public function setIdentityValue(string $identity_value);

    public function getIdentityValue() : string;

    public function setChecksum(string $checksum);

    public function getChecksum() : string;

    public function setProcessedAt(string $processed_at);

    public function getProcessedAt() : string;
}

