<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Central;

use Ls\Replication\Api\Central\Data\ReplLscWiDiscountsInterface;
use Magento\Framework\Api\SearchCriteriaInterface;

/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */
interface ReplLscWiDiscountsRepositoryInterface
{
    public function getList(SearchCriteriaInterface $criteria);

    public function save(ReplLscWiDiscountsInterface $page);

    public function delete(ReplLscWiDiscountsInterface $page);

    public function getById($id);

    public function deleteById($id);
}

