<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Central;

use Ls\Replication\Api\Central\Data\ReplLscDataTranslationInterface;
use Magento\Framework\Api\SearchCriteriaInterface;

/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */
interface ReplLscDataTranslationRepositoryInterface
{
    public function getList(SearchCriteriaInterface $criteria);

    public function save(ReplLscDataTranslationInterface $page);

    public function delete(ReplLscDataTranslationInterface $page);

    public function getById($id);

    public function deleteById($id);
}

