<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Api\Central;

use Ls\Replication\Api\Central\Data\ReplLscCollectionFrameworkInterface;
use Magento\Framework\Api\SearchCriteriaInterface;

/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */
interface ReplLscCollectionFrameworkRepositoryInterface
{
    public function getList(SearchCriteriaInterface $criteria);

    public function save(ReplLscCollectionFrameworkInterface $page);

    public function delete(ReplLscCollectionFrameworkInterface $page);

    public function getById($id);

    public function deleteById($id);
}

