<?php
/**
 * Registers the Alpine.data for the LS Central loyalty points discount totals segment.
 *
 * The AlpineJS scope of this file is the method `initCartTotals()`
 * in Magento_Checkout::php-cart/totals.phtml.
 */

use Hyva\Theme\ViewModel\HyvaCsp;

/** @var HyvaCsp $hyvaCsp */
?>
<script>
    function initLoyaltyDiscountSegment() {
        return {
            isLoyaltyDiscountSegment() {
                return this.segment.code === 'ls_points_discount';
            },
            formatLoyaltyDiscountValue() {
                return '-' + hyva.formatPrice(this.segment.value);
            }
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initLoyaltyDiscountSegment', initLoyaltyDiscountSegment), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
