<?php

/** @var \Ls\Customer\Block\Loyalty\Offers $this */
$should_use_block = false;
$type = $this->getType();
$offers = $this->getOffers();
$total = count($offers);
$c = 0;
?>
<div class="coupons-view">
    <h2><?php echo __('Loyalty Offers'); ?></h2>
    <?php if ($should_use_block) : ?>
        <?php echo $this->getStaticBlock(); ?>
    <?php else : ?>
        <?php if (is_array($offers) && count($offers) > 0) : ?>
            <ul class=" coupons-grid">
                <?php foreach ($offers as $offer) : ?>
                    <?php
                    $c++;
                    $images = $this->fetchImages($offer);
                    ?>
                    <li class="item <?php echo($total == $c ? ' last' : '') ?> col-sm-4 col-md-4 col-lg-4">
                        <div class="item-img-cont">
                            <?php if (count($images) && !empty($images[0])) : ?>
                                <img id="coupon-collection-image-<?php echo $c ?>"
                                     src="<?php echo $this->getMediaPathToLoad() .
                                         $images[0]; ?>" alt="<?php echo $offer->getDescription() ?> ">
                            <?php endif; ?>
                        </div>
                        <div class="coupon-info">
                            <div class="title">
                                <h3><?php echo $offer->getDescription(); ?></h3>
                            </div>
                            <div class="code">
                                <span><?php echo $offer->getId(); ?></span>
                            </div>
                            <div class="coupon-description">
                                <?php echo $offer->getDetails(); ?>
                                </br>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php if ($c < 1) : ?>
            <h4><?php echo __('No offers'); ?></h4>
        <?php endif; ?>
    <?php endif; ?>
</div>