<?php
/** @var Offers $this */

use \Ls\Customer\Block\Loyalty\Offers;

$type   = 'PointOffer';
$offers = $this->getOffers();
$total  = is_array($offers) ? count($offers) : 0;
$c      = 0;
?>

<div class="coupons-view">
    <?php if (is_array($offers) && $total > 0) : ?>
        <ul class=" coupons-grid">
            <?php foreach ($offers as $offer) : ?>
                <?php
                $offerType = $this->getOfferType($offer['Offer']->getOfferCategory());
                if ($offerType != $type) {
                    continue;
                }
                $discountType = $this->getDiscountType($offer['Offer']->getDiscountType());
                $offerProductCategory = $this->getOfferProductCategoryLink($offer);
                if (!empty($offerProductCategory)) {
                    $c++;
                    $images = $this->fetchImages($offer);
                    ?>
                    <li class="item <?php echo($total == $c ? ' last' : '') ?> col-sm-4 col-md-4 col-lg-4">
                        <div class="item-img-cont">
                            <?php
                            // @codingStandardsIgnoreStart
                            if ($images && count($images) && !empty($images[0])) :
                                // @codingStandardsIgnoreEnd
                                ?>
                                <img id="coupon-collection-image-<?php echo $c ?>"
                                     src="<?php echo $this->getMediaPathToLoad() .
                                         $images[0] ?>" alt="<?php echo $offer['Offer']->getDescription() ?> ">
                            <?php endif; ?>
                        </div>
                        <div class="coupon-info">
                            <div class="title">
                                <h3><?php echo $offer['Offer']->getDescription(); ?></h3>
                            </div>
                            <?php if ($discountType == 'Coupon') { ?>
                                <div class="code">
                                    <span><b><?php echo __("Code: "); ?></b><?php echo $offer['Offer']->getDiscountNo(); ?></span>
                                </div>
                            <?php } ?>
                            <div class="code">
                                <span><b><?php echo __("Offer Type: "); ?></b><?php echo $discountType; ?></span>
                            </div>
                            <?php if (!empty($offer['Offer']->getEndingDate())) {
                                $expiryDate = $this->getOfferExpiryDate($offer['Offer']->getEndingDate());
                                if (!empty($expiryDate)) {
                                    ?>
                                    <div class="date">
                                        <span><b><?php echo __("Expiry: "); ?></b><?php echo $expiryDate; ?></span>
                                    </div>
                                <?php }
                            }
                            ?>
                            <div class="coupon-description">
                                <p><?php echo $offer['Offer']->getSecondarytext(); ?></p>
                            </div>
                            <?php if (!empty($offerProductCategory[0])) { ?>
                                <p>
                                    <a class="action subscribe primary"
                                       href="<?php echo $offerProductCategory[0]; ?>"><?php echo __($offerProductCategory[1]); ?></a>
                                </p>
                            <?php } ?>
                        </div>
                    </li>
                <?php } ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php if ($c < 1) : ?>
        <h4><?php echo __('No offers'); ?></h4>
    <?php endif; ?>
</div>
