<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class ReplItemVariant extends AbstractDb
{

    public function _construct()
    {
        $this->_init( 'ls_replication_repl_item_variant', 'repl_item_variant_id' );
    }


}

