<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Omni\Client\Loyalty\Entity;

use Ls\Omni\Client\Loyalty\Entity\Enum\StoreHourType;
use Ls\Omni\Exception\InvalidEnumException;

class StoreHours
{

    /**
     * @property int $DayOfWeek
     */
    protected $DayOfWeek = null;

    /**
     * @property string $Description
     */
    protected $Description = null;

    /**
     * @property string $NameOfDay
     */
    protected $NameOfDay = null;

    /**
     * @property string $OpenFrom
     */
    protected $OpenFrom = null;

    /**
     * @property string $OpenTo
     */
    protected $OpenTo = null;

    /**
     * @property StoreHourType $StoreHourtype
     */
    protected $StoreHourtype = null;

    /**
     * @property string $StoreId
     */
    protected $StoreId = null;

    /**
     * @param int $DayOfWeek
     * @return $this
     */
    public function setDayOfWeek($DayOfWeek)
    {
        $this->DayOfWeek = $DayOfWeek;
        return $this;
    }

    /**
     * @return int
     */
    public function getDayOfWeek()
    {
        return $this->DayOfWeek;
    }

    /**
     * @param string $Description
     * @return $this
     */
    public function setDescription($Description)
    {
        $this->Description = $Description;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->Description;
    }

    /**
     * @param string $NameOfDay
     * @return $this
     */
    public function setNameOfDay($NameOfDay)
    {
        $this->NameOfDay = $NameOfDay;
        return $this;
    }

    /**
     * @return string
     */
    public function getNameOfDay()
    {
        return $this->NameOfDay;
    }

    /**
     * @param string $OpenFrom
     * @return $this
     */
    public function setOpenFrom($OpenFrom)
    {
        $this->OpenFrom = $OpenFrom;
        return $this;
    }

    /**
     * @return string
     */
    public function getOpenFrom()
    {
        return $this->OpenFrom;
    }

    /**
     * @param string $OpenTo
     * @return $this
     */
    public function setOpenTo($OpenTo)
    {
        $this->OpenTo = $OpenTo;
        return $this;
    }

    /**
     * @return string
     */
    public function getOpenTo()
    {
        return $this->OpenTo;
    }

    /**
     * @param StoreHourType|string $StoreHourtype
     * @return $this
     * @throws InvalidEnumException
     */
    public function setStoreHourtype($StoreHourtype)
    {
        if ( StoreHourType::isValid( $StoreHourtype) ) 
            $this->StoreHourtype = new StoreHourType( $StoreHourtype );
        elseif ( StoreHourType::isValidKey( $StoreHourtype) ) 
            $this->StoreHourtype = new StoreHourType( constant( "StoreHourType::$StoreHourtype" ) );
        else 
            throw new InvalidEnumException();
        return $this;
    }

    /**
     * @return StoreHourType
     */
    public function getStoreHourtype()
    {
        return $this->StoreHourtype;
    }

    /**
     * @param string $StoreId
     * @return $this
     */
    public function setStoreId($StoreId)
    {
        $this->StoreId = $StoreId;
        return $this;
    }

    /**
     * @return string
     */
    public function getStoreId()
    {
        return $this->StoreId;
    }


}

