<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Test\Unit\Model;

use Magento\Framework\Exception\CouldNotDeleteException;
use Magento\Framework\Exception\CouldNotSaveException;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\Api\SearchCriteriaInterface;
use Exception;
use Magento\Framework\Phrase;
use Magento\Framework\Api\SortOrder;
use PHPUnit\Framework\TestCase;
use Magento\Framework\TestFramework\Unit\Helper\ObjectManager;
use \Ls\Replication\Model\ReplLscTenderTypeRepository;
use \Ls\Replication\Model\ResourceModel\ReplLscTenderType\Collection;
use \Ls\Replication\Model\ResourceModel\ReplLscTenderType\CollectionFactory;
use \Ls\Replication\Api\ReplLscTenderTypeRepositoryInterface;
use \Ls\Replication\Api\Data\ReplLscTenderTypeInterface;
use \Ls\Replication\Api\Data\ReplLscTenderTypeSearchResultsInterface;
use \Ls\Replication\Model\ReplLscTenderTypeFactory;
use \Ls\Replication\Model\ReplLscTenderTypeSearchResultsFactory;

class ReplLscTenderTypeRepositoryTest extends TestCase
{
    /**
     * @property Ls\Omni\Client\Ecommerce\Entity\LSCTenderTypeFactory $objectFactory
     */
    protected $objectFactory = null;

    /**
     * @property CollectionFactory $collectionFactory
     */
    protected $collectionFactory = null;

    /**
     * @property ReplLscTenderTypeSearchResultsFactory $resultFactory
     */
    protected $resultFactory = null;

    /**
     * @property ReplLscTenderTypeRepository $model
     */
    private $model = null;

    /**
     * @property ReplLscTenderTypeInterface $entityInterface
     */
    private $entityInterface = null;

    /**
     * @property ReplLscTenderTypeSearchResultsInterface $entitySearchResultsInterface
     */
    private $entitySearchResultsInterface = null;

    public function setUp() : void
    {
        $this->objectFactory = $this->createPartialMock(Ls\Omni\Client\Ecommerce\Entity\LSCTenderTypeFactory::class, ['create']);
        $this->collectionFactory = $this->createMock(CollectionFactory::class);
        $this->resultFactory = $this->createMock(ReplLscTenderTypeSearchResultsFactory::class);
        $this->entityInterface = $this->createMock(ReplLscTenderTypeInterface::class);
        $this->entitySearchResultsInterface = $this->createMock(ReplLscTenderTypeSearchResultsInterface::class);
        $this->model = new ReplLscTenderTypeRepository(
            $this->objectFactory,
            $this->collectionFactory,
            $this->resultFactory
        );
    }

    public function testGetById()
    {
        $entityId = 1;
        $entityMock = $this->createMock(ReplLscTenderTypeRepository::class);
        $entityMock->method('getById')
            ->with($entityId)
            ->willReturn($entityId);
        $this->assertEquals($entityId, $entityMock->getById($entityId));
    }

    public function testGetWithNoSuchEntityException()
    {
        $this->expectExceptionMessage("Object with id 1 does not exist.");
        $this->expectException(\Magento\Framework\Exception\NoSuchEntityException::class);
        $entityId = 1;
        $entityMock = $this->createMock(ReplLscTenderTypeRepository::class);
        $entityMock->method('getById')
            ->with($entityId)
            ->willThrowException(
                new NoSuchEntityException(
                    new Phrase('Object with id ' . $entityId . ' does not exist.')
                )
            );
        $entityMock->getById($entityId);
    }

    public function testGetListWithSearchCriteria()
    {
        $searchCriteria = $this->getMockBuilder(SearchCriteriaInterface::class)->getMock();
        $entityMock = $this->createMock(ReplLscTenderTypeRepository::class);
        $entityMock->method('getList')
            ->with($searchCriteria)
            ->willReturn($this->entitySearchResultsInterface);
        $this->assertEquals($this->entitySearchResultsInterface, $entityMock->getList($searchCriteria));
    }

    public function testSave()
    {
        $entityMock = $this->createMock(ReplLscTenderTypeRepository::class);
        $entityMock->method('save')
            ->with($this->entityInterface)
            ->willReturn($this->entityInterface);
        $this->assertEquals($this->entityInterface, $entityMock->save($this->entityInterface));
    }

    public function testSaveWithCouldNotSaveException()
    {
        $this->expectExceptionMessage("Could not save entity");
        $this->expectException(\Magento\Framework\Exception\CouldNotSaveException::class);
        $entityMock = $this->createMock(ReplLscTenderTypeRepository::class);
        $entityMock->method('save')
            ->with($this->entityInterface)
            ->willThrowException(
                new CouldNotSaveException(
                    __('Could not save entity')
                )
            );
        $entityMock->save($this->entityInterface);
    }
}

