<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Ls\Omni\Block\Product\View\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $isEnableCheck = $block->isEnable();?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <?php if($isEnableCheck){?>
                    <div class="availability-link-container">
                        <a href="javascript:void()" name="checkavailability"
                           class="checkavailability"><?php echo __('Check Availability in Stores') ?></a>
                    </div>
                <?php } ?>
                <button type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <div id="map-canvas"></div>
<?php endif; ?>
<script type="text/javascript">
    var googleMapApiKey = "<?php echo $block->getGoogleMapsApiKey();?>";
    var defaultLat = "<?php echo $block->getDefaultLatitude();?>";
    var defaultLong = "<?php echo $block->getDefaultLongitude();?>";
    var defaultZoom = "<?php echo $block->getDefaultZoom();?>";
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "lsomni/stock": {}
        }
    }
</script>
