<?php
// @codingStandardsIgnoreFile
use Ls\Omni\Block\Product\View\View;

/** @var $block View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $isEnableCheck = $block->isValid(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= /* @escapeNotVerified */
                            __('Qty') ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?= /* @escapeNotVerified */
                               $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */
                               __('Qty') ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <?php if ($isEnableCheck) : ?>
                    <?= $block->getBlockHtml('ls.omni.product.availability'); ?>
                <?php endif; ?>
                <button type="submit"
                        title="<?= /* @escapeNotVerified */
                        $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */
                        $buttonTitle ?></span>
                </button>
                <?php if ($isEnableCheck) : ?>
                    <?= $block->getBlockHtml('ls.omni.product.return.policy'); ?>
                <?php endif; ?>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <div id="map-canvas"></div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
