<?php
// @codingStandardsIgnoreFile
use Magento\Framework\View\Element\Template;

/** @var $viewModel \Ls\Omni\ViewModel\GeneralViewModel */
/** @var $block Template */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isValid()) : ?>
    <div class="availability-link-container">
        <a href="javascript:void()" name="checkavailability"
           class="checkavailability"><?php echo __('Check Availability in Stores') ?></a>
    </div>
    <div id="map-canvas"></div>
    <script type="text/javascript">
        var googleMapApiKey = "<?= $viewModel->getGoogleMapsApiKey();?>",
            defaultLat = "<?= $viewModel->getDefaultLatitude();?>",
            defaultLong = "<?= $viewModel->getDefaultLongitude();?>",
            defaultZoom = "<?= $viewModel->getDefaultZoom();?>";
    </script>

    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "lsomni/stock": {
                "googleMapApiKey": "<?= $viewModel->getGoogleMapsApiKey();?>",
                "defaultLat": "<?= $viewModel->getDefaultLatitude();?>",
                "defaultLong": "<?= $viewModel->getDefaultLongitude();?>",
                "defaultZoom": "<?= $viewModel->getDefaultZoom();?>"
            }
        }
    }

    </script>
<?php endif; ?>
