<?php
// @codingStandardsIgnoreFile
use Ls\Omni\ViewModel\GeneralViewModel;
use Magento\Framework\View\Element\Template;

/** @var $viewModel GeneralViewModel */
/** @var $block Template */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isValid()) : ?>
    <div class="availability-link-container">
        <a href="javascript:void()" name="checkavailability"
           class="checkavailability"><?php echo __('Check Availability in Stores') ?></a>
    </div>
    <div id="map-canvas"></div>
    <script type="text/javascript">
        var googleMapApiKey = "<?php echo $viewModel->getGoogleMapsApiKey();?>";
        var defaultLat = "<?php echo $viewModel->getDefaultLatitude();?>";
        var defaultLong = "<?php echo $viewModel->getDefaultLongitude();?>";
        var defaultZoom = "<?php echo $viewModel->getDefaultZoom();?>";
    </script>

    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "lsomni/stock": {}
        }
    }

    </script>
<?php endif; ?>
