<?php
/** @var \Ls\Omni\Block\Product\View\Discount\Proactive $block */
// @codingStandardsIgnoreFile
$productData = $block->getData();
$productSku = $productData['data']['productSku'];
?>
    <?php
    $coupons = $block->getCoupons($productSku);
    if (!empty($discounts) || !empty($coupons)) {
        ?>
        <?php
        foreach ($coupons as $coupon) {
            if ($coupon->getCode() == 'Coupon') {
                echo "<div class='dropdown-content-wrapper content-coupon'>
                " . $block->getFormattedDescriptionCoupon($coupon) . "
            </div>";
            }
            ?>
   <?php }
    }?>