<?php
/** @var Proactive $block */
// @codingStandardsIgnoreFile
use \Ls\Omni\Block\Product\View\Discount\Proactive;
use \Ls\Omni\Client\Ecommerce\Entity\Enum\DiscountType;

$productData = $block->getData();
$productSku  = $productData['data']['productSku'];
?>
<?php
$coupons = $block->getCoupons($productSku);
if (!empty($coupons)) {
    ?>
    <?php
    foreach ($coupons as $coupon) {
        if ($coupon->getCode() == DiscountType::COUPON || $coupon->getCode() == DiscountType::PROMOTION) {
            echo "<div class='dropdown-content-wrapper content-coupon'>
                " . $block->getFormattedDescriptionCoupon($coupon) . "
            </div>";
        }
        ?>
    <?php }
} ?>