
    <?php

/** @var \Ls\Omni\Block\Product\View\Loyalty $block */

/**
 * Generate info message for user to loggedin or register in order to view discounts.
 *
 */

    if(!$block->isLoggedIn()){

        /** For the refer url redirecton. $currenturl */
        $currenturl         =   $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);

        /** Login and Registration URL links. */
        $login_url          =   $block->getUrl('customer/account/login', array('referer' => base64_encode($currenturl)));
        $registrationUrl    =   $block->getUrl('customer/account/create', array('referer' => base64_encode($currenturl)));

        ?>


        <div class="messages">

            <div class="message message-info info" role="alert">

                <?php

                $loginAnchor    =   "<a href=\"$login_url\" title=\" Login\"> Login </a> ";
                $registerAnchor    =   "<a href=\"$registrationUrl\" title=\" Register \"> Register </a> ";

                echo __(
                    "Please $loginAnchor / $registerAnchor to view available discounts on this product."
                );

                ?>
            </div>

        </div>

    <?php } ?>
