<?php
/** @var Proactive $block */
// @codingStandardsIgnoreFile
use \Ls\Omni\Block\Product\View\Discount\Proactive;
use Magento\Catalog\Model\Product\Type;

$productData = $block->getData();
$product = $block->getProductGivenSku($productData['data']['productSku']);

if ($product->getTypeId() == Type::TYPE_BUNDLE) {
    $itemId = $block->getLinkedProductsItemIds($product);
} else {
    $itemId  = $block->getLsCentralItemIdBySku($productData['data']['productSku']);
}

$coupons = $block->getCoupons([$itemId]);
$discountOffers = $mixAndMatchDiscounts = $multibuyOffers = [];
?>
<div class="proactive-discounts-container">
    <?php
    $discounts = $block->getProactiveDiscounts($itemId);

    if (!empty($discounts)) {
        list($discountOffers, $mixAndMatchDiscounts, $multibuyOffers) = $block->getRelevantDiscountOffers($discounts);
    }

    if (!empty($discounts) || !empty($coupons)): ?>
        <div class="discount-dropdown-label">
            <span><?php echo $block->escapeHtml(__("Offers and Promotions:")); ?></span>
        </div>
        <div class="discount-dropdown">
            <div data-block="dropdown" class="dropdown-wrapper">
                <button type="button" class="action primary" data-trigger="trigger">
                    <span><?php echo $block->escapeHtml(__('Find Discounts')); ?></span>
                    <i class="arrow down"></i>
                </button>
            </div>
            <div class="block block-dropdown"
                 data-mage-init='{
        "dropdownDialog": {
            "appendTo": "[data-block=dropdown]",
            "triggerTarget":"[data-trigger=trigger]",
            "timeout": 2000,
            "closeOnMouseLeave": false,
            "closeOnEscape": true,
            "autoOpen": false,
            "triggerClass": "active",
            "parentClass": "active",
            "buttons": []
        }
     }'>
            <?php foreach ($coupons as $coupon): ?>
                <?=
                    "<div class='dropdown-content-wrapper content-coupon'>
                    " . $block->getFormattedDescriptionForCoupon($coupon) . "
                    </div>";
                ?>
            <?php endforeach; ?>

            <?php foreach ($discountOffers as $discountOffer): ?>
                <?=
                "<div class='dropdown-content-wrapper content-coupon'>
                    " . $block->getFormattedDescriptionForDiscountOffer($discountOffer) . "
                    </div>";
                ?>
            <?php endforeach; ?>

            <?php foreach ($multibuyOffers as $multibuyOffer): ?>
                <?=
                "<div class='dropdown-content-wrapper content-coupon'>
                    " . $block->getFormattedDescriptionForMultibuyOffer($multibuyOffer, $discounts) . "
                </div>";
                ?>
            <?php endforeach; ?>

            <?php foreach ($mixAndMatchDiscounts as $mixAndMatchDiscount): ?>
                <?=
                "<div class='dropdown-content-wrapper content-coupon'>
                " . $block->getFormattedDescriptionForMixAndMatchOffer($mixAndMatchDiscount, $discounts, $itemId) . "
                </div>";
                ?>
            <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
</div>
<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/modal'], function ($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: $.mage.__('Items'),
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        $(".ls-click-product-promotion").on('click', function () {
            var id = $(this).attr("data-id");
            var popup = modal(options, $("#ls-popup-model-" + id));
            $("#ls-popup-model-" + id).modal("openModal");
        });
    });
</script>
