<?php
/** @var \Ls\Omni\Block\Product\View\Discount\Proactive $block */
// @codingStandardsIgnoreFile
$productData = $block->getData();
$productSku = $productData['data']['productSku'];
?>
<div class="proactive-discounts-container">
    <?php
    $discounts = $block->getProactiveDiscounts($productSku);
    $coupons = $block->getCoupons($productSku);
    if (!empty($discounts) || !empty($coupons)) {
        ?>
        <div class="discount-dropdown-label">
            <span><?php echo __("Promotions:"); ?></span>
        </div>
        <div class="discount-dropdown">
            <div data-block="dropdown" class="dropdown-wrapper">
                <button type="button" class="action primary" data-trigger="trigger">
                    <span><?php echo __('Find Discounts');?></span>
                    <i class="arrow down"></i>
                </button>
            </div>
            <div class="block block-dropdown"
                 data-mage-init='{
        "dropdownDialog": {
            "appendTo": "[data-block=dropdown]",
            "triggerTarget":"[data-trigger=trigger]",
            "timeout": 2000,
            "closeOnMouseLeave": false,
            "closeOnEscape": true,
            "autoOpen": false,
            "triggerClass": "active",
            "parentClass": "active",
            "buttons": []
        }
     }'>
                <?php
                foreach ($coupons as $coupon) {
                    if ($coupon->getCode() == 'Coupon') {
                        echo "<div class='dropdown-content-wrapper content-coupon'>
                " . $block->getFormattedDescriptionCoupon($coupon) . "
            </div>";
                    }
                }
                foreach ($discounts as $discount) {
                    echo "<div class='dropdown-content-wrapper content-discount'>
                " . $block->getFormattedDescriptionDiscount($productSku, $discount) . "
            </div>";
                }
                ?>

            </div>
        </div>
    <?php } ?>
</div>