<?php
/** @var \Ls\Omni\Block\Product\View\Recommend $block */
$mode = 'grid';
$title = __('Recommended Products for you');
$productData = $block->getData();
$productId = $productData['data']['productSku'];
if ($items = $block->getProductRecommendation($productId)) : ?>
    <div class="block">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= /* @escapeNotVerified */
                $title ?></strong>
        </div>
        <div class="block-content">
            <div class="products-<?php echo $mode; ?> <?php echo $mode; ?>">
                <ol class="product-items widget-viewed-grid">
                    <?php $iterator = 1; ?>
                    <div id="mp-list-items-lsrecommend" class="owl-carousel owl-theme">
                        <?php /** @var \Magento\Catalog\Api\Data\ProductInterface $block */ ?>
                        <?php foreach ($items as $_item) : ?>
                            <?php echo ($iterator++ == 1) ? '<li class="product-item product-slider"">' : '</li><li class="product-item product-slider"">' ?>
                            <div class="slider-product-item-info">
                                <a href="<?php echo $block->getProductUrl($_item) ?>"
                                   class="product photo slider-product-item-photo">
                                    <?php echo $block->getImage($_item,
                                        'recently_viewed_products_grid_content_widget')->toHtml(); ?>
                                </a>
                                <div class="product details slider-product-item-details">
                                    <strong class="product name product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php echo $block->getProductUrl($_item) ?>">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php echo $block->getProductPrice($_item); ?>
                                    <div class="product actions slider-product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()) : ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                                    <button class="action tocart primary mageplaza-product-slider-button"
                                                            data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}'
                                                            type="button" title="<?php echo __('Add to Cart') ?>">
                                                        <span><?php echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else : ?>
                                                    <?php
                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item),
                                                        ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary mageplaza-product-slider-button"
                                                            data-post='<?php echo $postData; ?>'
                                                            type="button" title="<?php echo __('Add to Cart') ?>">
                                                        <span><?php echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else : ?>
                                                <?php if ($_item->getIsSalable()) : ?>
                                                    <div class="stock available">
                                                        <span><?php echo __('In stock') ?></span>
                                                    </div>
                                                <?php else : ?>
                                                    <div class="stock unavailable">
                                                        <span><?php echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php // @codingStandardsIgnoreStart ?>
                            <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                            <?php // @codingStandardsIgnoreEnd ?>
                        <?php endforeach ?>
                    </div>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
