<?php
// @codingStandardsIgnoreFile
use Ls\Omni\ViewModel\GeneralViewModel;
use Magento\Framework\View\Element\Template;

/** @var $viewModel GeneralViewModel */
/** @var $block Template */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isValid()) : ?>
    <div class="return-policy-container">
        <a href="javascript:void()"
           class="return-policy"><?php echo __('Return Policy') ?></a>
    </div>
    <div id="ls-return-policy"></div>

    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "lsomni/return-policy": {}
        }
    }

    </script>
<?php endif; ?>
