<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model\Central;

use Ls\Replication\Api\Central\Data\ReplSalepriceviewSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplSalepriceviewSearchResults extends SearchResults implements ReplSalepriceviewSearchResultsInterface
{
}

