<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model\Central;

use Ls\Replication\Api\Central\Data\ReplHierarchynodesviewSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplHierarchynodesviewSearchResults extends SearchResults implements ReplHierarchynodesviewSearchResultsInterface
{
}

