<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model\Central;

use Ls\Replication\Api\Central\Data\ReplLscRetailProductGroupSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplLscRetailProductGroupSearchResults extends SearchResults implements ReplLscRetailProductGroupSearchResultsInterface
{
}

