<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model\Central;

use Ls\Replication\Api\Central\Data\ReplLscWiImageBufferSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplLscWiImageBufferSearchResults extends SearchResults implements ReplLscWiImageBufferSearchResultsInterface
{
}

