<div id="ls-coupons">
    <div class="loader">
        <img src="<?= /* @escapeNotVerified */
        $block->getViewFileUrl('images/loader-1.gif') ?>"
             alt="<?= /* @escapeNotVerified */
             __('Loading...') ?>">
        <br/>
        <div><?php echo __('Loading Coupons...'); ?></div>
    </div>
</div>
<?php
/** @var \Ls\Omni\Block\Cart\Coupons $block */
$ajaxUrl = $block->getAjaxUrl();
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Ls_Omni/js/view/checkout/cart/coupons": {
                    "ajaxUrl": "<?php echo $ajaxUrl; ?>"
                }
            }
        }
</script>