<?php
// @codingStandardsIgnoreFile
/** @var Coupons $block */

use \Ls\Omni\Block\Cart\Coupons;

$enabled = $block->isCouponEnabled();
?>
<?php if ($enabled) :?>
    <div id="ls-coupons">
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */
            $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */
                 __('Loading...') ?>">
            <br/>
            <div><?php echo __('Loading Coupons...'); ?></div>
        </div>
    </div>
    <?php
    $ajaxUrl = $block->getAjaxUrl();
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Ls_Omni/js/view/checkout/cart/coupons": {
                    "ajaxUrl": "<?= $ajaxUrl; ?>"
                }
            }
        }

    </script>
<?php endif;?>
