<?php if ($loggedIn && !empty($availableCoupons) && empty($block->getCouponCode())) { ?>
    <div class="available-coupons">
    <h2><span>OR</span></h2>
    <form id="my_radio_box">
    <fieldset id="group1">

    <?php foreach ($availableCoupons as $each) {
        echo " <div class='coupon-major'><input type='radio' value='" . $each->getOfferId() .
            "' name='group1'>" . $block->getFormattedDescription($each) . '</div>';
        ?>
    <?php }
}?>
