<?php
/** @var \Ls\Omni\Block\Cart\Coupon $block */

// @codingStandardsIgnoreFile
$availableCoupons = [];
$loggedIn = $block->isCustomerLoggedIn();
if (empty($block->getCouponCode()) && $loggedIn){
    $loggedIn = $block->isCustomerLoggedIn();
    $availableCoupons = $block->getAvailableCoupons();
}

?>
<div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Apply Discount Code') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <label for="coupon_code" class="label"><span><?= /* @escapeNotVerified */ __('Enter discount code') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?= $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?= $block->escapeHtml(__('Enter discount code')) ?>" <?php if (strlen($block->getCouponCode())): ?> disabled="disabled" <?php endif; ?> />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <?php if (!strlen($block->getCouponCode())): ?>
                        <div class="primary">
                            <button class="action apply primary" type="button" value="<?= /* @escapeNotVerified */ __('Apply Discount') ?>">
                                <span><?= /* @escapeNotVerified */ __('Apply Discount') ?></span>
                            </button>
                        </div>
                    <?php else: ?>
                        <div class="primary">
                            <button  type="button" class="action cancel primary" value="<?= /* @escapeNotVerified */ __('Cancel Coupon') ?>"><span><?= /* @escapeNotVerified */ __('Cancel Coupon') ?></span></button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
        <?php if($loggedIn && !empty($availableCoupons) && empty($block->getCouponCode())){?>
        <div class="available-coupons">
            <h2><span>OR</span></h2>
            <form id="my_radio_box">
            <fieldset id="group1">
                <?php foreach($availableCoupons as $each){
                    echo " <div class='coupon-major'><input type='radio' value='".$each->getOfferId().
                        "' name='group1'>".$block->getFormattedDescription($each).'</div>';
                    ?>
                <?php } ?>
            </fieldset>
            </form>
        </div>
        <?php } ?>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready( function() {
            $('#my_radio_box').change(function(){
                var selected_value = $("input[name='group1']:checked").val();
                var ele = $("input[name='group1']:checked");
                ele.parent().siblings().removeClass('active');
                ele.parent().addClass('active');
                $("#coupon_code").val(selected_value);
            });
            $(document).on("click", ".available-coupons .coupon-major", function(){
                $(this).find('input').attr('checked', 'checked');
                $('#my_radio_box').change();
            });
        });
    });
</script>