<?php
// @codingStandardsIgnoreFile
/**
 * @var  Ls\Omni\ViewModel\CouponsViewModel $viewModel
 */

use Magento\Checkout\Block\Cart\Coupon;

$viewModel = $block->getData("view_model");
?>
<?php if ($viewModel->isCouponsEnabled() == "1"): ?>
    <div class="block discount" id="block-discount"
         data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
        <div class="title" data-role="title">
            <strong id="block-discount-heading" role="heading" aria-level="2">
                <?= /* @noEscape */ $block->escapeHtml(__('Apply Discount Code')) ?>
            </strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-discount-heading">
            <form id="discount-coupon-form"
                  action="<?= /* @noEscape */ $block->getUrl('checkout/cart/couponPost') ?>"
                  method="post"
                  data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
                <div class="fieldset coupon<?= /* @noEscape */ !empty($block->getCouponCode()) ? ' applied' : '' ?>">
                    <input type="hidden" name="remove" id="remove-coupon" value="0"/>
                    <div class="field">
                        <label for="coupon_code" class="label">
                            <span><?= /* @noEscape */ $block->escapeHtml(__('Enter discount code')) ?></span>
                        </label>
                        <div class="control">
                            <input type="text"
                                   class="input-text"
                                   id="coupon_code"
                                   name="coupon_code"
                                   value="<?= /* @noEscape */ $block->escapeHtml($block->getCouponCode()) ?>"
                                   placeholder="<?= /* @noEscape */ $block->escapeHtml(__('Enter discount code')) ?>"
                                <?php if (!empty($block->getCouponCode())): ?> disabled="disabled" <?php endif; ?> />
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <?php if (empty($block->getCouponCode())): ?>
                            <div class="primary">
                                <button class="action apply primary"
                                        type="button"
                                        value="<?= /* @noEscape */ $block->escapeHtml(__('Apply Discount')) ?>">
                                    <span><?= /* @noEscape */ $block->escapeHtml(__('Apply Discount')) ?></span>
                                </button>
                            </div>
                        <?php else: ?>
                            <div class="primary">
                                <button type="button"
                                        class="action cancel primary"
                                        value="<?= /* @noEscape */ $block->escapeHtml(__('Cancel Coupon')) ?>">
                                        <span><?= /* @noEscape */ $block->escapeHtml(__('Cancel Coupon')) ?></span>
                                </button>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </form>
            <?= $this->getLayout()
                ->createBlock('Ls\Omni\Block\Cart\Coupons')
                ->setTemplate('Ls_Omni::cart/coupons-loader.phtml')
                ->toHtml();
            ?>
        </div>
    </div>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function ($) {
            $(document).ready(function () {
                $(document).on("change", '#my_radio_box', function () {
                    var selected_value = $("input[name='group1']:checked").val();
                    var ele = $("input[name='group1']:checked");
                    ele.parent().siblings().removeClass('active');
                    ele.parent().addClass('active');
                    $("#coupon_code").val(selected_value);
                });
                $(document).on("click", ".available-coupons .coupon-major", function () {
                    $(this).find('input').attr('checked', 'checked');
                    $('#my_radio_box').change();
                });
            });
        });
    </script>

<?php elseif (!$viewModel->isModuleEnabled()): ?>
    <?= $this->getLayout()
        ->createBlock(Coupon::class)
        ->setTemplate('Magento_Checkout::cart/coupon.phtml')
        ->toHtml(); ?>
<?php endif; ?>
