<?php
/** @var \Ls\Omni\Block\Cart\Giftcard $block */
$class = "";
// @codingStandardsIgnoreFile
if ($block->getGiftCardActive()) {
    if (!empty($block->getGiftCardAmountUsed())) {
        $class = "applied";
    } ?>
    <div class="giftcard block" id="block-giftcard"
         data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
        <div class="title" data-role="title">
            <strong id="block-giftcard-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */
                __('Apply Gift Card / Voucher') ?></strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-giftcard-heading">
            <form id="giftcard-form"
                  action="<?= /* @escapeNotVerified */
                  $block->getUrl('omni/cart/GiftCardUsed') ?>"
                  method="post"
                  data-mage-init='{"giftCard":{"GiftcardSelector": "#removegiftcard",
                                               "removeGiftCardSelector": "#removegiftcard",
                                               "applyGiftCardButton": "input.action.applygiftcard",
                                               "cancelGiftCardButton": "input.action.cancelgiftcard"}}'>
                <div class="fieldset <?php echo $class ?>">
                    <input type="hidden" name="removegiftcard" id="removegiftcard" value="0"/>
                    <div class="field gift-card-code-field">
                        <div class="control">
                            <input type="text" class="input-text" id="giftcardno" name="giftcardno"
                                   placeholder="Enter Code" value=""
                                   required="required"/>
                        </div>
                    </div>
                    <?php if ($block->isPinCodeFieldEnable()) : ?>
                        <div class="field gift-card-code-field">
                            <div class="control">
                                <input type="password" class="input-text" id="giftcardpin" name="giftcardpin"
                                        placeholder="Enter Pin" value=""
                                       required="required"/>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="field gift-card-amount-field">
                        <div class="control">
                            <input type="number" min="0" class="input-text" id="giftcardamount" name="giftcardamount"
                                   placeholder="Enter Amount" value=""
                                   required="required"/>
                        </div>
                    </div>
                    <div class="actions actions-toolbar">
                        <div class="primary">
                            <input class="action applygiftcard primary" type="submit"
                                   value="<?= __('Apply') ?>"></input>
                            <input type="submit" class="action cancelgiftcard primary"
                                   value="<?= __('Cancel') ?>" style="display:none;"></input>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <?php
} ?>
