<?php
/** @var \Ls\Omni\Block\Cart\Voucher $block */
$class = "";
// @codingStandardsIgnoreFile
if ($block->getVoucherActive()) {
    if (!empty($block->getVoucherAmountUsed())) {
        $class = "applied";
    } ?>
    <div class="voucher block" id="block-voucher"
         data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
        <div class="title" data-role="title">
            <strong id="block-voucher-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */
                __('Apply Gift Card / Voucher') ?></strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-voucher-heading">
            <form id="voucher-cart-form"
                  action="<?= /* @escapeNotVerified */
                  $block->getUrl('omni/cart/VoucherUsed') ?>"
                  method="post"
                  data-mage-init='{"voucherCard":{"VoucherSelector": "#removevoucher",
                                                "removeVoucherSelector": "#removevoucher",
                                                "applyVoucherButton": "input.action.applyvoucher",
                                                "cancelVoucherButton": "input.action.cancelvoucher"}}'>
                <div class="fieldset <?php echo $class ?>">
                    <input type="hidden" name="removevoucher" id="removevoucher" value="0"/>
                    <div class="field voucher-code-field">
                        <div class="control">
                            <input type="text" class="input-text" id="voucherno" name="voucherno"
                                   placeholder="Enter Gift Card / Voucher Code" value="<?= $block->getVoucherNo() ?>"
                                   required="required"/>
                        </div>
                    </div>
                    <?php if ($block->isPinCodeFieldEnable()) : ?>
                        <div class="field voucher-code-field">
                            <div class="control">
                                <input type="password" class="input-text" id="voucherpin" name="voucherpin"
                                       placeholder="Enter Pin" value="<?= $block->getVoucherPin() ?>"
                                       required="required"/>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="field voucher-amount-field">
                        <div class="control">
                            <input type="number" min="0" class="input-text" id="voucheramount" name="voucheramount"
                                   placeholder="Amount to Use" value="<?= $block->getVoucherAmountUsed() ?>"
                                   required="required"/>
                        </div>
                    </div>
                    <div class="actions actions-toolbar">
                        <div class="primary">
                            <?php if (empty($block->getVoucherAmountUsed())): ?>
                                <input class="action applyvoucher primary" type="submit"
                                       value="<?= __('Apply') ?>"></input>
                            <?php else: ?>
                                <input class="action applyvoucher primary" type="submit"
                                       value="<?= __('Update') ?>"></input>
                                <input type="submit" class="action cancelvoucher primary"
                                       value="<?= __('Cancel') ?>"></input>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <?php
} ?>

