<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Replication\Model\ResourceModel\ReplUnitOfMeasure;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection
{

    public function _construct()
    {
        $this->_init( 'Ls\Replication\Model\ReplUnitOfMeasure', 'Ls\Replication\Model\ResourceModel\ReplUnitOfMeasure' );
    }


}

