<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var  $block \Ls\Customer\Block\Order\History */
?>
<?php $_orders = $block->getOrderHistory(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                <th scope="col" class="col candc"><?= /* @escapeNotVerified */ __('Click & Collect') ?></th>
                <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                <th scope="col" class="col loyaltypointsused"><?= /* @escapeNotVerified */ __('Points Used') ?></th>
                <th scope="col" class="col loyaltypointsrewarded"><?= /* @escapeNotVerified */ __('Points Rewarded') ?></th>
                <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_order->getDocumentId() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->getFormattedDate($_order->getDocumentRegTime())?></td>
                    <td data-th="<?= $block->escapeHtml(__('Click & Collect')) ?>" class="col candc"><?= /* @escapeNotVerified */ $_order->getClickAndCollectOrder() ?  "true" : "false" ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShipToName() ? $block->escapeHtml($_order->getShipToName()) : '&nbsp;' ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $block->getFormattedPrice($_order->getTotalAmount()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Points Used')) ?>" class="col loyaltypointsused"><?= /* @escapeNotVerified */ $block->getFormattedLoyaltyPoints($_order->getPointsUsedInOrder()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Points Rewarded')) ?>" class="col loyaltypointsrewarded"><?= /* @escapeNotVerified */ $block->getFormattedLoyaltyPoints($_order->getPointsRewarded()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->getOrderStatus() ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                            <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
<?php endif ?>
