<?php

// @codingStandardsIgnoreFile

/** @var Items $block */
$order = $block->getMagOrder();

use \Ls\Customer\Block\Order\Items;
use Magento\Sales\Model\Order\Item;

?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?= /* @escapeNotVerified */
    __('Items Ordered') ?>">
        <caption class="table-caption"><?= /* @escapeNotVerified */
            __('Items Ordered') ?></caption>
        <thead>
        <tr>
            <th class="col name"><?= /* @escapeNotVerified */
                __('Product Name') ?></th>
            <th class="col sku"><?= /* @escapeNotVerified */
                __('SKU') ?></th>
            <?php if (!$block->getShipmentOption()) { ?>
                <th class="col price"><?= /* @escapeNotVerified */
                    __('Price') ?></th>
            <?php } ?>
            <th class="col qty"><?= /* @escapeNotVerified */
                __('Qty') ?></th>
            <?php if (!$block->getShipmentOption()) { ?>
                <th class="col subtotal"><?= /* @escapeNotVerified */
                    __('Subtotal') ?></th>
            <?php } ?>
        </tr>
        </thead>
        <?php $items = $block->getItems(); ?>
        <?php $giftMessage = '' ?>
        <?php foreach ($items as $item):
            if ($item instanceof Item  && $item->getParentItem()) :
                continue;
            endif;
            ?>
            <tbody>
            <?php if ($item instanceof Item): ?>
                <?= $block->getItemHtml($item)?>
            <?php else:?>
                <?= $block->getCustomItemRenderer($item); ?>
            <?php endif; ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot>
        <?= $block->getChildHtml('custom_order_totals') ?>
        </tfoot>
    </table>
</div>
