<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Ls\Customer\Block\Order\Info $block */
?>

<div class="order-date">
    <?= /* @escapeNotVerified */ __('<span class="label">Order Date:</span> %1', '<date>' . $block->formatDate($block->getOrder()->getDocumentRegTime(), \IntlDateFormatter::LONG) . '</date>') ?>
</div>
