<?php
// @codingStandardsIgnoreFile
use Magento\Framework\Escaper;
use \Ls\Customer\Block\Order\Totals;
/**
 * @var Totals $block
 * @var Escaper $escaper
 */
?>
<tr class="subtotal">
    <th colspan="4" class="mark" scope="row">
        <?= $escaper->escapeHtml(__('Subtotal (Inc.Tax)')) ?>
    </th>
    <td class="amount" data-th="<?= $escaper->escapeHtml(__('Subtotal (Inc.Tax)')) ?>">
        <span class="price">
            <?= $escaper->escapeHtml($block->getFormattedPrice($block->getSubtotal())); ?>
        </span>
    </td>
</tr>

<?php if (!empty($block->getTotalDiscount()) && $block->getTotalDiscount() > 0): ?>
    <tr class="discount">
        <th colspan="4" class="mark" scope="row">
            <?= $escaper->escapeHtml(__('Total Discount')) ?>
        </th>
        <td class="amount" data-th="<?= $escaper->escapeHtml(__('Total Discount')) ?>">
            <span class="price">
                -<?= $escaper->escapeHtml($block->getFormattedPrice($block->getTotalDiscount())); ?>
            </span>
        </td>
    </tr>
<?php endif; ?>

<?php if (!empty($block->loyaltyPointAmount > 0)): ?>
    <tr class="discount">
        <th colspan="4" class="mark" scope="row">
            <?= $escaper->escapeHtml(__('Loyalty Points Redeemed')) ?>
        </th>
        <td class="amount" data-th="<?= $escaper->escapeHtml(__('Loyalty Points Redeemed')) ?>">
            <span class="price">
                -<?= $escaper->escapeHtml($block->getFormattedPrice($block->loyaltyPointAmount)); ?>
            </span>
        </td>
    </tr>
<?php endif; ?>

<?php foreach ($block->giftCardEntries as $giftCardEntry): ?>
    <tr class="discount">
        <th colspan="4" class="mark" scope="row">
            <?= $escaper->escapeHtml(__('%1 Redeemed (%2)', $giftCardEntry['entry_type'], $giftCardEntry['entry_no'])) ?>
        </th>
        <td class="amount" data-th="<?= $escaper->escapeHtml(__('%1 Redeemed (%2)', $giftCardEntry['entry_type'], $giftCardEntry['entry_no'])) ?>">
            <span class="price">-<?= $escaper->escapeHtml($block->getFormattedPrice($giftCardEntry['amount'])); ?></span>
        </td>
    </tr>
<?php endforeach; ?>

<?php foreach ($block->voucherEntries as $voucherEntry): ?>
    <tr class="discount">
        <th colspan="4" class="mark" scope="row">
            <?= $escaper->escapeHtml(__('%1 Redeemed (%2)', $voucherEntry['entry_type'], $voucherEntry['entry_no'])) ?>
        </th>
        <td class="amount" data-th="<?= $escaper->escapeHtml(__('%1 Redeemed (%2)', $voucherEntry['entry_type'], $voucherEntry['entry_no'])) ?>">
            <span class="price">-<?= $escaper->escapeHtml($block->getFormattedPrice($voucherEntry['amount'])); ?></span>
        </td>
    </tr>
<?php endforeach; ?>

<tr class="shipping">
    <th colspan="4" class="mark" scope="row">
        <?= $escaper->escapeHtml(__('Shipment & Handling')) ?>
    </th>
    <td class="amount" data-th="<?= $escaper->escapeHtml(__('Shipment & Handling')) ?>">
        <span class="price">
            <?= $escaper->escapeHtml($block->getFormattedPrice($block->getShipmentChargeLineFee())); ?>
        </span>
    </td>
</tr>
<tr class="totals-tax">
    <th colspan="4" class="mark" scope="row">
        <?= $escaper->escapeHtml(__('Tax')) ?>
    </th>
    <td class="amount" data-th="<?= $escaper->escapeHtml(__('Tax')) ?>">
        <span class="price">
            <?= $escaper->escapeHtml($block->getFormattedPrice($block->getTotalTax())); ?>
        </span>
    </td>
</tr>
<tr class="grand_total">
    <th colspan="4" class="mark" scope="row">
        <strong><?= $escaper->escapeHtml(__('Total')) ?> </strong>
    </th>
    <td class="amount" data-th="<?= $escaper->escapeHtml(__('Total')) ?>">
        <strong>
            <span class="price">
                <?= $escaper->escapeHtml($block->getFormattedPrice($block->getTotalAmount())); ?>
            </span>
        </strong>
    </td>
</tr>
