<?php

// @codingStandardsIgnoreFile

/**
 * @var $block Totals
 */

use \Ls\Customer\Block\Order\Totals; ?>
<tr class="subtotal">
    <th colspan="4" class="mark" scope="row">
        <?= $block->escapeHtml('Subtotal (Inc.Tax)') ?>
    </th>
    <td class="amount" data-th="<?= $block->escapeHtml('Subtotal (Inc.Tax)') ?>">
        <span class="price"><?= $block->getFormattedPrice($block->getSubtotal()); ?></span>
    </td>
</tr>
<?php if (!empty($block->giftCardAmount > 0)) { ?>
    <tr class="discount">
        <th colspan="4" class="mark" scope="row">
            <?= $block->escapeHtml('Gift Card Redeemed') ?>
        </th>
        <td class="amount" data-th="<?= $block->escapeHtml('Gift Card Redeemed') ?>">
            <span class="price">-<?= $block->getFormattedPrice($block->giftCardAmount); ?></span>
        </td>
    </tr>
<?php } ?>

<?php if (!empty($block->loyaltyPointAmount > 0)) { ?>
    <tr class="discount">
        <th colspan="4" class="mark" scope="row">
            <?= $block->escapeHtml('Loyalty Points Redeemed') ?>
        </th>
        <td class="amount" data-th="<?= $block->escapeHtml('Loyalty Points Redeemed') ?>">
            <span class="price">-<?= $block->getFormattedPrice($block->loyaltyPointAmount); ?></span>
        </td>
    </tr>
<?php } ?>

<?php if (!empty($block->getTotalDiscount()) && $block->getTotalDiscount() > 0) { ?>
    <tr class="discount">
        <th colspan="4" class="mark" scope="row">
            <?= $block->escapeHtml('Total Discount') ?>
        </th>
        <td class="amount" data-th="<?= $block->escapeHtml('Total Discount') ?>">
            <span class="price">-<?= $block->getFormattedPrice($block->getTotalDiscount()); ?></span>
        </td>
    </tr>
<?php } ?>
<tr class="shipping">
    <th colspan="4" class="mark" scope="row">
        <?= $block->escapeHtml('Shipment & Handling') ?>
    </th>
    <td class="amount" data-th="<?= $block->escapeHtml('Shipment & Handling') ?>">
        <span class="price"><?= $block->getFormattedPrice($block->getShipmentChargeLineFee()); ?></span>
    </td>
</tr>
<tr class="totals-tax">
    <th colspan="4" class="mark" scope="row">
        <?= $block->escapeHtml('Tax') ?>
    </th>
    <td class="amount" data-th="<?= $block->escapeHtml('Tax') ?>">
        <span class="price"><?= $block->getFormattedPrice($block->getTotalTax()); ?></span>
    </td>
</tr>
<tr class="grand_total">
    <th colspan="4" class="mark" scope="row">
        <strong><?= $block->escapeHtml('Total') ?> </strong>
    </th>
    <td class="amount" data-th="<?= $block->escapeHtml('Total') ?>">
        <strong><span class="price"><?= $block->getFormattedPrice($block->getTotalAmount()); ?></span></strong>
    </td>
</tr>
