<?php
// @codingStandardsIgnoreFile
?>
<?php
/** @var $block Info */
use Ls\Customer\Block\Order\Info;
?>
<?php $_order = $block->getOrder();
$formattedLoyaltyPoints = $block->getFormattedLoyaltyPoints();
if (!empty($_order->getStoreName())):
?>
<div class="block block-order-details-view-loyalty">
    <div class="block-title">
        <strong>
            <?= /* @noEscape */ __('Useful Information') ?>
        </strong>
    </div>
    <div class="block-content">
        <?php if (!empty($_order->getStoreName())): ?>
            <div class="custom-box">
                <strong class="box-title">
                    <span><?= /* @noEscape */ __('Store Name:') ?></span>
                </strong>
                <span><?= /* @noEscape */ $_order->getStoreName() ?></span>
            </div>
        <?php endif; ?>
        <?php if ($block->canShowClickAndCollect() && $_order->getClickAndCollectOrder()): ?>
            <div class="custom-box">
                <strong class="box-title">
                    <span><?= /* @noEscape */ __('Click & Collect:') ?></span>
                </strong>
                <span><?= /* @noEscape */ __('Yes'); ?></span>
            </div>
        <?php endif; ?>
        <?php if ($formattedLoyaltyPoints > 0): ?>
        <div class="custom-box">
            <strong class="box-title">
                <span><?= /* @noEscape */ __('Loyalty Points Rewarded:') ?></span>
            </strong>
            <span><?= /* @noEscape */ $formattedLoyaltyPoints; ?></span>
        </div>
        <?php endif; ?>
        <?php if (!empty($giftCardNumber = $block->getPaymentDescription()[1])): ?>
            <div class="custom-box">
                <strong class="box-title">
                    <span><?= /* @noEscape */ __('Gift Card Code:') ?></span>
                </strong>
                <span><?= /* @noEscape */ $giftCardNumber[0]; ?></span>
            </div>
        <?php endif; ?>
        <?php if (
            $block->canShowRequestedDeliveryDate() &&
            !empty($requestedDeliveryDate = $block->getRequestedDeliveryDate())
        ): ?>
            <div class="custom-box">
                <strong class="box-title">
                    <span><?= /* @noEscape */ __('Requested Delivery Date:') ?></span>
                </strong>
                <span><?= /* @noEscape */ $requestedDeliveryDate; ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
