<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Ls\Customer\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view-loyalty">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */
            __('Useful Information') ?></strong>
    </div>
    <div class="block-content">
        <div class="custom-box">
            <strong class="box-title"><span><?= /* @escapeNotVerified */
                    __('Click & Collect:') ?></span></strong>
            <span><?= $_order->getClickAndCollectOrder() ? 'Yes' : 'No'; ?></span>
        </div>
        <div class="custom-box">
            <strong class="box-title"><span><?= /* @escapeNotVerified */
                    __('Loyalty Points Redeemed:') ?></span></strong>
            <span><?= $block->getFormattedLoyaltyPoints($_order->getPointsUsedInOrder()); ?></span>
        </div>
        <div class="custom-box">
            <strong class="box-title"><span><?= /* @escapeNotVerified */
                    __('Loyalty Points Rewarded:') ?></span></strong>
            <span><?= $block->getFormattedLoyaltyPoints($_order->getPointsRewarded()); ?></span>
        </div>
        <?php if(!empty($block->getPaymentDescription()[1])){ ?>
        <div class="custom-box">
            <strong class="box-title"><span><?= /* @escapeNotVerified */
                    __('Gift Card No:') ?></span></strong>
            <span><?= $block->getPaymentDescription()[1][0]; ?></span><br/>
            <strong class="box-title"><span><?= /* @escapeNotVerified */
                    __('Gift Card Amount Used:') ?></span></strong>
            <span><?= $block->getGiftCardFormattedPrice($block->getPaymentDescription()[1][1]); ?></span>
        </div>
        <?php } ?>
    </div>
</div>
