<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Replication\Model;

use Magento\Framework\Model\AbstractModel;
use Magento\Framework\DataObject\IdentityInterface;
use Ls\Replication\Api\Data\LoyItemInterface;

class LoyItem extends AbstractModel implements LoyItemInterface, IdentityInterface
{

    const CACHE_TAG = 'ls_replication_loy_item';

    protected $_cacheTag = 'ls_replication_loy_item';

    protected $_eventPrefix = 'ls_replication_loy_item';

    /**
     * @property ArrayOfImageView $Images
     */
    protected $Images = null;

    /**
     * @property ArrayOfRetailAttribute $ItemAttributes
     */
    protected $ItemAttributes = null;

    /**
     * @property ArrayOfPrice $Prices
     */
    protected $Prices = null;

    /**
     * @property ArrayOfUnitOfMeasure $UnitOfMeasures
     */
    protected $UnitOfMeasures = null;

    /**
     * @property ArrayOfVariantExt $VariantsExt
     */
    protected $VariantsExt = null;

    /**
     * @property ArrayOfVariantRegistration $VariantsRegistration
     */
    protected $VariantsRegistration = null;

    /**
     * @property boolean $AllowedToSell
     */
    protected $AllowedToSell = null;

    /**
     * @property string $Description
     */
    protected $Description = null;

    /**
     * @property string $Details
     */
    protected $Details = null;

    /**
     * @property boolean $IsDeleted
     */
    protected $IsDeleted = null;

    /**
     * @property string $Price
     */
    protected $Price = null;

    /**
     * @property string $ProductGroupId
     */
    protected $ProductGroupId = null;

    /**
     * @property string $SalesUomId
     */
    protected $SalesUomId = null;

    /**
     * @property string $nav_id
     */
    protected $nav_id = null;

    /**
     * @property string $scope
     */
    protected $scope = null;

    /**
     * @property int $scope_id
     */
    protected $scope_id = null;

    /**
     * @property string $processed
     */
    protected $processed = null;

    public function _construct()
    {
        $this->_init( 'Ls\Replication\Model\ResourceModel\LoyItem' );
    }

    public function getIdentities()
    {
        return [ self::CACHE_TAG . '_' . $this->getId() ];
    }

    /**
     * @param ArrayOfImageView $Images
     * @return $this
     */
    public function setImages($Images)
    {
        $this->setData( 'Images', $Images );
        $this->Images = $Images;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return ArrayOfImageView
     */
    public function getImages()
    {
        return $this->getData( 'Images' );
    }

    /**
     * @param ArrayOfRetailAttribute $ItemAttributes
     * @return $this
     */
    public function setItemAttributes($ItemAttributes)
    {
        $this->setData( 'ItemAttributes', $ItemAttributes );
        $this->ItemAttributes = $ItemAttributes;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return ArrayOfRetailAttribute
     */
    public function getItemAttributes()
    {
        return $this->getData( 'ItemAttributes' );
    }

    /**
     * @param ArrayOfPrice $Prices
     * @return $this
     */
    public function setPrices($Prices)
    {
        $this->setData( 'Prices', $Prices );
        $this->Prices = $Prices;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return ArrayOfPrice
     */
    public function getPrices()
    {
        return $this->getData( 'Prices' );
    }

    /**
     * @param ArrayOfUnitOfMeasure $UnitOfMeasures
     * @return $this
     */
    public function setUnitOfMeasures($UnitOfMeasures)
    {
        $this->setData( 'UnitOfMeasures', $UnitOfMeasures );
        $this->UnitOfMeasures = $UnitOfMeasures;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return ArrayOfUnitOfMeasure
     */
    public function getUnitOfMeasures()
    {
        return $this->getData( 'UnitOfMeasures' );
    }

    /**
     * @param ArrayOfVariantExt $VariantsExt
     * @return $this
     */
    public function setVariantsExt($VariantsExt)
    {
        $this->setData( 'VariantsExt', $VariantsExt );
        $this->VariantsExt = $VariantsExt;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return ArrayOfVariantExt
     */
    public function getVariantsExt()
    {
        return $this->getData( 'VariantsExt' );
    }

    /**
     * @param ArrayOfVariantRegistration $VariantsRegistration
     * @return $this
     */
    public function setVariantsRegistration($VariantsRegistration)
    {
        $this->setData( 'VariantsRegistration', $VariantsRegistration );
        $this->VariantsRegistration = $VariantsRegistration;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return ArrayOfVariantRegistration
     */
    public function getVariantsRegistration()
    {
        return $this->getData( 'VariantsRegistration' );
    }

    /**
     * @param boolean $AllowedToSell
     * @return $this
     */
    public function setAllowedToSell($AllowedToSell)
    {
        $this->setData( 'AllowedToSell', $AllowedToSell );
        $this->AllowedToSell = $AllowedToSell;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return boolean
     */
    public function getAllowedToSell()
    {
        return $this->getData( 'AllowedToSell' );
    }

    /**
     * @param string $Description
     * @return $this
     */
    public function setDescription($Description)
    {
        $this->setData( 'Description', $Description );
        $this->Description = $Description;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->getData( 'Description' );
    }

    /**
     * @param string $Details
     * @return $this
     */
    public function setDetails($Details)
    {
        $this->setData( 'Details', $Details );
        $this->Details = $Details;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getDetails()
    {
        return $this->getData( 'Details' );
    }

    /**
     * @param boolean $IsDeleted
     * @return $this
     */
    public function setIsDeleted($IsDeleted)
    {
        $this->setData( 'IsDeleted', $IsDeleted );
        $this->IsDeleted = $IsDeleted;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->getData( 'IsDeleted' );
    }

    /**
     * @param string $Price
     * @return $this
     */
    public function setPrice($Price)
    {
        $this->setData( 'Price', $Price );
        $this->Price = $Price;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getPrice()
    {
        return $this->getData( 'Price' );
    }

    /**
     * @param string $ProductGroupId
     * @return $this
     */
    public function setProductGroupId($ProductGroupId)
    {
        $this->setData( 'ProductGroupId', $ProductGroupId );
        $this->ProductGroupId = $ProductGroupId;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getProductGroupId()
    {
        return $this->getData( 'ProductGroupId' );
    }

    /**
     * @param string $SalesUomId
     * @return $this
     */
    public function setSalesUomId($SalesUomId)
    {
        $this->setData( 'SalesUomId', $SalesUomId );
        $this->SalesUomId = $SalesUomId;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getSalesUomId()
    {
        return $this->getData( 'SalesUomId' );
    }

    /**
     * @param string $nav_id
     * @return $this
     */
    public function setNavId($nav_id)
    {
        $this->setData( 'nav_id', $nav_id );
        $this->nav_id = $nav_id;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getNavId()
    {
        return $this->getData( 'nav_id' );
    }

    /**
     * @param string $scope
     * @return $this
     */
    public function setScope($scope)
    {
        $this->setData( 'scope', $scope );
        $this->scope = $scope;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getScope()
    {
        return $this->getData( 'scope' );
    }

    /**
     * @param int $scope_id
     * @return $this
     */
    public function setScopeId($scope_id)
    {
        $this->setData( 'scope_id', $scope_id );
        $this->scope_id = $scope_id;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return int
     */
    public function getScopeId()
    {
        return $this->getData( 'scope_id' );
    }

    /**
     * @param string $processed
     * @return $this
     */
    public function setProcessed($processed)
    {
        $this->setData( 'processed', $processed );
        $this->processed = $processed;
        $this->setDataChanges( TRUE );
        return $this;
    }

    /**
     * @return string
     */
    public function getProcessed()
    {
        return $this->getData( 'processed' );
    }


}

