<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Replication\Model;

use Ls\Replication\Api\Data\ReplCustomerSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplCustomerSearchResults extends SearchResults implements ReplCustomerSearchResultsInterface
{


}

