<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model;

use Ls\Replication\Api\Data\ReplLscGs1Barcodev1SetupSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplLscGs1Barcodev1SetupSearchResults extends SearchResults implements ReplLscGs1Barcodev1SetupSearchResultsInterface
{
}

