<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model;

use Ls\Replication\Api\Data\ReplLscInventoryMenusSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplLscInventoryMenusSearchResults extends SearchResults implements ReplLscInventoryMenusSearchResultsInterface
{
}

