<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 */


namespace Ls\Replication\Model;

use Ls\Replication\Api\Data\ReplBarcodeSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplBarcodeSearchResults extends SearchResults implements ReplBarcodeSearchResultsInterface
{


}

