<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model;

use Ls\Replication\Api\Data\ReplLscItemVariantRegistrationSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplLscItemVariantRegistrationSearchResults extends SearchResults implements ReplLscItemVariantRegistrationSearchResultsInterface
{
}

