<?php
/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY
 * @codingStandardsIgnoreFile
 */


namespace Ls\Replication\Model;

use Ls\Replication\Api\Data\ReplLscMemberContactSearchResultsInterface;
use Magento\Framework\Api\SearchResults;

class ReplLscMemberContactSearchResults extends SearchResults implements ReplLscMemberContactSearchResultsInterface
{
}

