<?php
/** @var Dashboard $this */

use \Ls\Customer\Block\Account\Dashboard;

if ($account = $this->getMembersInfo()) : ?>
    <div class="block block-club-info">
        <div class="block-title">
            <strong>Club Information</strong>
        </div>
        <div class="block-content">
            <div class="box">
                <div class="box-title">
                    <strong><span></span><?php echo __('Member Information'); ?></span></strong>
                </div>
                <div class="box-content">
                    <p>
                    <h6 class='header-inline'>
                        <?php echo __('Club Name:'); ?>
                    </h6>
                    <?php echo $account->getScheme()
                        ->getClub()
                        ->getName(); ?><br>
                    <h6 class='header-inline'>
                        <?php echo __('Loyalty Points Earned:'); ?>
                    </h6>
                    <?php echo $account->getPointBalance(); ?><br>
                    <?php if($account->getPointBalance() &&
                        ($expiry = $this->getPointBalanceExpiry($account))
                    ): ?>
                        <h6 class='header-inline'>
                            <?php echo __('Loyalty Points Expiry:'); ?>
                        </h6>
                        <?php echo $expiry; ?><br>
                    <?php endif; ?>
                    <h6 class='header-inline'>
                        <?php echo __('Loyalty Level:'); ?>
                    </h6>
                    <?php echo $account->getScheme()
                        ->getDescription(); ?>
                    </p>
                </div>
            </div>
            <div class="box">
                <div class="box-title">
                    <strong> <span></span><?php echo __('Next Level'); ?> </span></strong>
                </div>
                <div class="box-content">
                    <?php if ($account->getScheme()
                        ->getNextScheme()
                    ) : ?>
                        <p>
                        <h6 class='header-inline'>
                            <?php echo __('Level:'); ?>
                        </h6>
                        <?php
                        echo $account->getScheme()
                            ->getNextScheme()
                            ->getDescription();
                        ?>
                        <br>
                        <h6 class='header-inline'>
                            <?php echo __('Points Needed:'); ?>
                        </h6>
                        <?php echo $account->getScheme()
                            ->getPointsNeeded(); ?>
                        <br>
                        <h6 class='header-inline'>
                            <?php echo __('Benefits of Next Level:') ?>
                        </h6>
                        <?php echo $account->getScheme()
                            ->getPerks(); ?>
                        </p>
                    <?php else : ?>
                        <p>
                        <h6 class='header-inline'>
                            <?php echo __('You are at the top level.'); ?>
                        </h6>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
