<?php
/** @var Dashboard $block */

use \Ls\Customer\Block\Account\Dashboard;
$loyaltyPoints = $block->getLoyaltyPointsBalance();
if ($account = $block->getMembersInfo()) : ?>
    <div class="block block-club-info">
        <div class="block-title">
            <strong><?= __('Club Information'); ?></strong>
        </div>
        <div class="block-content">
            <div class="box member-information">
                <div class="box-title">
                    <strong><span><?= __('Member Information'); ?></span></strong>
                </div>
                <div class="box-content">
                    <div class="club-name">
                        <h6 class='header-inline'>
                            <?= __('Club Name:'); ?>
                        </h6>
                        <span>
                            <?= $account->getLscMemberClub()->getDescription(); ?>
                        </span>
                    </div>
                    <div class="loyalty-point-earned">
                        <h6 class='header-inline'>
                            <?= __('Loyalty Points Earned:'); ?>
                        </h6>
                        <span>
                            <?= $loyaltyPoints; ?>
                        </span>
                    </div>
                    <?php if (!empty($loyaltyPoints) &&
                        ($expiry = $block->getPointBalanceExpiry())
                    ): ?>
                    <div class="loyalty-points-expiry">
                        <h6 class='header-inline'>
                            <?= __('Loyalty Points Expiry:'); ?>
                        </h6>
                        <span>
                            <?= $expiry; ?>
                        </span>
                    </div>

                    <?php endif; ?>
                    <div class="loyalty-level">
                        <h6 class='header-inline'>
                            <?= __('Loyalty Level:'); ?>
                        </h6>
                        <span>
                            <?= $account->getLscMemberScheme()->getDescription(); ?>
                        </span>
                    </div>
                </div>
            </div>
            <div class="box next-level">
                <div class="box-title">
                    <strong> <span><?= __('Next Level'); ?> </span></strong>
                </div>
                <div class="box-content">
                    <?php
                    $nextScheme = $block->getNextScheme(
                        $account->getLscMemberScheme()->getClubCode(),
                        $account->getLscMemberScheme()->getUpdateSequence()
                    );
                    if ($nextScheme) : ?>
                        <div class="level">
                            <h6 class='header-inline'>
                                <?= __('Level:'); ?>
                            </h6>
                            <span>
                                <?= $nextScheme['Description']; ?>
                            </span>
                        </div>
                        <div class="points-needed">
                            <h6 class='header-inline'>
                                <?= __('Points Needed:'); ?>
                            </h6>
                            <span>
                                <?= $nextScheme['Min. Point for Upgrade']; ?>
                            </span>
                        </div>
                        <div class="perks">
                            <h6 class='header-inline'>
                                <?= __('Benefits of Next Level:') ?>
                            </h6>
                            <span>
                                <?= $account->getLscMemberScheme()->getNextSchemeBenefits(); ?>
                            </span>
                        </div>
                    <?php else : ?>
                        <h6 class='header-inline'>
                            <?= __('You are at the top level.'); ?>
                        </h6>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
